### ISSUE TITLE
utoipa-axum requires __path_ to be imported.

### ISSUE THREAD

**Issue by EinarasGar** [juhaku/utoipa#1021]
Hi. 

I am trying the new utoipa-axum crate and so far it works great, however, if my handlers are located somewhere else other than the router, I have to import the `__path_****` module.

Expected to be working:
```
use crate::handlers::portfolio_handler::get_networth_history;
...
let mut router: OpenApiRouter = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .routes(routes!(get_networth_history))
```
Error:
`failed to resolve: use of undeclared crate or module __path_get_networth_history`

Workaround:
```
use crate::handlers::portfolio_handler::get_networth_history;
use crate::handlers::portfolio_handler::__path_get_networth_history;

...
let mut router: OpenApiRouter = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .routes(routes!(get_networth_history))
```

Additionally, providing full path does not work either
```
 let mut router: OpenApiRouter = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .routes(routes!(handlers::portfolio_handler::get_networth_history))
```
Gives error  `expected punct: ':'`

Just wanted to raise it in case it is unknown. Thank you for your great job, really liking 5.0 so far

**Comment by lucasgranberg** [comment]
I see the same thing. The routes! macro assumes `__path...` is in the same module as the macro is called. The `expected punct` comes from the paste crate.

I tried looking in to how to pass a full path to the macro but it seems it is not that easy. It is tricky to separate the path(`crate::handlers::portfolio_handler::`) from the ident(`get_networth_history`) to then put the the `__path` part back. It is doable with some hacks.

Maybe there are easier ways but this is one way to do it. https://stackoverflow.com/a/77403898/959097

**Comment by juhaku** [comment]
This indeed was a biiiit tricky. But got it done. This definitely would have been easier with proc macro, however that would have been overkill for just resolving the handler `path` type.

**Comment by lucasgranberg** [comment]
This is amazing! a chonky macro for sure.

My reason for wanting to use paths from modules is that I want to keep my endpoints separated by file and then I need to put a post and a get in the same `routes!()` invocation.

**Comment by EinarasGar** [comment]
Damn, reported before I went to bed - fixed by the time im back from work.
Blazing fast speed. Kudos to you!

**Comment by juhaku** [comment]
https://github.com/juhaku/utoipa/releases/tag/utoipa-axum-0.1.0-beta.2 New beta is out

**Comment by dominictobias** [comment]
Hm I still get this on `0.2.0`. The workaround of additionally importing `__path_<modname>` works
