### ISSUE TITLE
[FEATURE REQUEST] Deeply / recursively export components into openapi

### ISSUE THREAD

**Issue by clotodex** [juhaku/utoipa#1025]
(I am using axum and the axum bindings)
I noticed that to completely export a type I also have to list all subtypes in the components.
While this offers 100% felxibility, I am trying to export generated code which means I need to import and list every single subtype manually, which is errorprone.

Example:
- assume you have an enum
```rust
// Define the structs for each shape type
struct Circle {
    radius: f64,
}

struct Rectangle {
    width: f64,
    height: f64,
}

struct Triangle {
    base: f64,
    height: f64,
}

// Define the enum that wraps the different shape structs
enum Shape {
    Circle(Circle),
    Rectangle(Rectangle),
    Triangle(Triangle),
}
```

Then I cannot just list `Shape` in the components but have to list `Shape, Rectangle, Triangle, Circle` ...

Is this feasible? I used schemars with okapi before where they somehow made this work

**Comment by juhaku** [comment]
At the moment they need to be listed manually. But I'm planning to improve this eventually to the 5.0.0 version.

**Comment by jayvdb** [comment]
I believe this is a dup of https://github.com/juhaku/utoipa/issues/465

**Comment by juhaku** [comment]
Yeah it actually touches the same topic.

**Comment by juhaku** [comment]
There is no WIP branch for work related to this one. https://github.com/juhaku/utoipa/pull/new/feature-auto-collect-schemas

**Comment by juhaku** [comment]
I could consider this as done, as all mandatory things for this is implemented excluding support for `ToReponse` and `IntoReponses`. Those can be followed in a separate issue and I link the issue here as well.
