### ISSUE TITLE
Option<Vec> is traslated with wrong type

### ISSUE THREAD

**Issue by rt-planck** [juhaku/utoipa#1027]
If I have a field of a struct of type Option<Vec<>>

e.g.

```rust
pub struct Error {
    details: Option<Vec<ErrorDetail>>,
}
```

or even
```rust
pub struct Error {
   #[schema(nullable)]
    details: Option<Vec<ErrorDetail>>,
}
```

the generated schema has type

```yml
type:
         - array
          -"null"
```           

This is wrong, it should be
```yml
type: array
nullable: true
```

See specs https://swagger.io/docs/specification/data-models/data-types/
 
The current behavior breaks and is reported as an error. The error can be easily tested using swagger editor https://editor.swagger.io/

**Comment by juhaku** [comment]
@rt-planck That spec is for Open API 3.0. However Utoipa will move to OpenAPI 3.1 with the 5.0.0 version and the type is defined differently there. That is correct behavior for OpenAPI 3.1.

The https://editor.swwagger.io/ does not support OpenAPI 3.1 spec instead need to use https://editor-next.swagger.io/ for that.

**Comment by rt-planck** [comment]
Ok, then there should be a bug in swagger UI and redoc, in both cases that line breaks the schema refs

E.g., on https://editor-next.swagger.io/ the 3.1.0 schema generated using the new definition
<img width="715" alt="image" src="https://github.com/user-attachments/assets/c9d93465-e767-4633-8d90-b63bfd1cf7ee">

and this is the nicer version 3.0.3 using nullable
![Uploading image.png…]()
or withouth nullable
<img width="696" alt="image" src="https://github.com/user-attachments/assets/4e405e9e-66da-48f9-a4c3-cd33e32ffc97">
