### ISSUE TITLE
termsOfService in Macro Openapi

### ISSUE THREAD

**Issue by ValentinColin** [juhaku/utoipa#1035]
Hi,

Would you be able to add the field `Info::termsOfService` in the macros [OpenApi](https://docs.rs/utoipa/latest/utoipa/derive.OpenApi.html#info-attribute-syntax) to avoid setting it manually, please ?

Thank you for all your work 🔥

**Comment by juhaku** [comment]
@ValentinColin Sure, this is super fast to add. I'll see if I can get this done sometime soon. But latest for the 5.0.0. Also if there is interest contributions are welcome. It eases my burden. 

>Thank you for all your work 🔥

Appreciated :slightly_smiling_face:
