### ISSUE TITLE
`utoipa-swagger-ui`: cross compile to Windows on Linux fails

### ISSUE THREAD

**Issue by cyqsimon** [juhaku/utoipa#1044]
When cross-compiling to `x86_64-pc-windows-gnu` target on Linux, `utoipa-swagger-ui` fails to build with the following error.

```
error: failed to run custom build command for `utoipa-swagger-ui v7.1.0`

Caused by:
  process didn't exit successfully: `/repo/target/release/build/utoipa-swagger-ui-a31a62fed59f60ee/build-script-build` (exit status: 101)
  --- stdout
  OUT_DIR: /repo/target/x86_64-pc-windows-gnu/release/build/utoipa-swagger-ui-31dfd8e5fc31018f/out
  SWAGGER_UI_DOWNLOAD_URL: https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.17.12.zip
  start download to : "/repo/target/x86_64-pc-windows-gnu/release/build/utoipa-swagger-ui-31dfd8e5fc31018f/out/v5.17.12.zip"
  cargo:rerun-if-env-changed=SWAGGER_UI_DOWNLOAD_URL
  reqwest feature: Err(NotPresent)

  --- stderr
  thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/utoipa-swagger-ui-7.1.0/build.rs:183:81:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

I took a quick look at `build.rs`, and it seems like the original author made some implicit assumptions about tooling availability when targeting different OSes, but did not take into account the possibility of cross-compilation.

**Comment by juhaku** [comment]
Could you provide quick setup how to reproduce this issue. Are you using `corss` for cross compiling? Or do you have some other setup to cross compile with linkers and targets?

**Comment by cyqsimon** [comment]
Sorry for the rushed issue; was in a hurry.

I was not using cross. I'm on a Linux x86_64 system, targeting `x86_64-pc-windows-gnu` using the MinGW-w64 cross-compiler. To reproduce this setup:
1. `rustup target add x86_64-pc-windows-gnu`
2. Install MinGW-w64 cross compiler. The package name depends on your distro; on Arch it's `mingw-w64-gcc`; on Fedora it's `mingw64-gcc`; not sure what it is on Debian, but search for the package that provides `/usr/bin/x86_64-w64-mingw32-gcc`.
3. `cargo build --target x86_64-pc-windows-gnu` and you should see this error.

**Comment by juhaku** [comment]
Thanks I try to check this out later.

**Comment by cyqsimon** [comment]
https://github.com/juhaku/utoipa/blob/f13d3d3909a543482b0d917d67c38fc1561a297e/utoipa-swagger-ui/README.md?plain=1#L58-L63

I'm thinking, given that Windows has shipped `curl.exe` since 2018, maybe it would be clearer to always use `curl` by default? This would get rid of a lot of the conditional compilation complexity in `build.rs`.

I'll send in a PR for this, see if you like it.
