### ISSUE TITLE
The new global config type aliases do not work well on `Option<>` types

### ISSUE THREAD

**Issue by eranrund** [juhaku/utoipa#1057]
Hi!

I've been trying out the new global config stuff on commit 576f6c129010b4f6e6445c06393cfcf2cfee30df.

I have the following test file:
```
use utoipa::ToSchema;
use chrono::{DateTime, Utc};

pub type Timestamp = DateTime<Utc>;

#[derive(ToSchema)]
pub struct S {
    d: Timestamp,
    d2: Option<Timestamp>,
}

fn main() {
    println!("Hello, world!");
}
```

and `build.rs`:
```
use utoipa_config::Config;

fn main() {
    Config::new()
        .alias_for("Timestamp", "DateTime<Utc>")
        .write_to_file();
}
````

However I am getting this error:
```
rror[E0277]: the trait bound `chrono::DateTime<Utc>: ToSchema` is not satisfied
 --> src/main.rs:9:16
  |
9 |     d2: Option<Timestamp>,
  |                ^^^^^^^^^ the trait `ToSchema` is not implemented for `chrono::DateTime<Utc>`
  |
  = help: the following other types implement trait `ToSchema`:
            &'a str
            ()
            S
            bool
            char
            f32
            f64
            i128
          and 13 others

error[E0277]: the trait bound `chrono::DateTime<Utc>: PartialSchema` is not satisfied
   --> src/main.rs:9:16
    |
9   |     d2: Option<Timestamp>,
    |                ^^^^^^^^^ the trait `ComposeSchema` is not implemented for `chrono::DateTime<Utc>`, which is required by `chrono::DateTime<Utc>: PartialSchema`
    |
    = help: the trait `ComposeSchema` is implemented for `S`
    = note: required for `chrono::DateTime<Utc>` to implement `PartialSchema`
note: required by a bound in `name`
   --> /Users/eran/.cargo/git/checkouts/utoipa-797003a51754f4fd/576f6c1/utoipa/src/lib.rs:402:21
    |
402 | pub trait ToSchema: PartialSchema {
    |                     ^^^^^^^^^^^^^ required by this bound in `ToSchema::name`
...
410 |     fn name() -> Cow<'static, str>;
    |        ---- required by a bound in this associated function

For more information about this error, try `rustc --explain E0277`.
error: could not compile `ut` (bin "ut") due to 2 previous errors
```

I know the build.rs/global config does get used because if I remove the `alias_for` line, then even `d: Timestamp` produces an error.

Thanks!

**Comment by juhaku** [comment]
I theory it should work, as the alias is actually just a rust type which is converted to utoipa's `TypeTree`. I need to investigate this a bit and see what is happening. there. But that error just indicates that `ToSchema` is not implemented for `DateTime<Utc>` This is something chrono specific and is not necessary correlated with the `utoipa` and `utoipa-config`. Like you could create alias like ` .alias_for("NullableString", "Option<String>")` to create a nullable string.

I believe that there is a need to check whether `utoipa` supports all necessary `chrono` types, as there might be changes over time an it's been a while when I have updated them. It is actually impossible to keep up with the library changes unless `chrono` would add `ToSchema` implementations directly. 

Aliases themselves doss not resolve issue with third-party types which does not implement the `ToSchema` and in such case there is a need to manually implement the `ToSchema` for such type. Or use other ways to create schema for them. Here is more details related to this https://github.com/juhaku/utoipa/issues/790#issuecomment-1787754185. Or you could do something like this as shown below in actix-generics example: https://github.com/juhaku/utoipa/blob/e0c5aa749ac548cca7fd75544293865efe5d0231/examples/generics-actix/src/main.rs#L16-L30

**Comment by eranrund** [comment]
Hi @juhaku 
I think ToSchema is implemented for `DateTime<Utc>` though, since I enabled the `chrono` feature.

This builds just fine:
```
use utoipa::ToSchema;
use chrono::{DateTime, Utc};

pub type Timestamp = DateTime<Utc>;

#[derive(ToSchema)]
pub struct S {
//    d: Timestamp,
//    d2: Option<Timestamp>,
    d: DateTime<Utc>,
    d2: Option<DateTime<Utc>>,
}

fn main() {
    println!("Hello, world!");
}

```

**Comment by juhaku** [comment]
Okay, I need to investigate what is happening here then.

**Comment by juhaku** [comment]
Fix is on the way here #1083

**Comment by eranrund** [comment]
Works great, thank you :)

**Comment by lu-zero** [comment]
I'm tripping on it in this situation:

```rust
#[derive(Debug, Clone, Copy, Serialize, Deserialize, ToSchema)]
pub struct S<T> {
    pub a: T,
    pub o: Option<T>,
}

type SDateTime = S<DateTime<Utc>>;
```

Am I wielding it wrong?

**Comment by lu-zero** [comment]
The best workaround I found is to first alias `DateTime<Utc>` and then use the alias. Maybe this is documented and I did not see it?
