### ISSUE TITLE
[5.0.0-rc.0] Errors when implementing ToSchema manually

### ISSUE THREAD

**Issue by ValentinColin** [juhaku/utoipa#1093]
Hi, I tried to migrate from v4 to v5.
I've encountered a few problems after implementing the new trait ToSchema and PartialSchema.

Implement theses trait is very easy but I had a compile error on other struct that use de the derive way to impl ToSchema with inner struct that manually impl it.

Have I missed something?

How to reproduce:
```rust
use utoipa::{openapi, PartialSchema, ToSchema};

#[derive(Debug)]
struct Newtype(String);

impl ToSchema for Newtype {
    fn name() -> std::borrow::Cow<'static, str> {
        std::borrow::Cow::Borrowed("Newtype")
    }
}

impl PartialSchema for Newtype {
    fn schema() -> openapi::RefOr<openapi::schema::Schema> {
        openapi::ObjectBuilder::new()
            .schema_type(openapi::schema::Type::String)
            .into()
    }
}

#[derive(Debug, ToSchema)]
struct Dto {
    customer: Customer, // ERROR
}
```

Error:
> the trait bound `Newtype: utoipa::__dev::SchemaReferences` is not satisfied
the trait `utoipa::__dev::SchemaReferences` is implemented for `__path_handler`

But I can't find the trait `SchemaReferences` in the doc.

**Comment by juhaku** [comment]
Yeah, the `SchemaReferences` is internal type to `utoipa` thus it is not found from the Docs. This will need some pondering nonetheless as for now I have no solution for this though. This is due to the fact that the derive `ToSchema` will automatically implement the `utoipa::__dev::SchemaReferences` trait for the type, but this is of course not valid for cases where it suppose to be manually implemented. Maybe I need just make the type public for all.

But if you really want to go about implementing this type for now, you can do it actually and it is quite simple.
```rust
impl utoipa::__dev::SchemaReferences for NewType {
    fn schemas(_schemas: &mut Vec<(String, RefOr<Schema>)>) {
         // this type does not have any reference schemas
         // if it had any fields that implement `ToSchema` they should be 
         // pushed to the `schemas` vec.
    }
}
```

**Comment by ValentinColin** [comment]
Thanks for your quick reply

In my project, we implement ToSchema manually only for newtype, so I can easily use your workaround.

Indeed we manually implement ToSchema for newtype because the derive macro is not general enough for newtype (Unnamed Field Struct).
Unnamed Field Struct have only access to: example, examples, default, title, format, value_type, as, deprecated, description.

Do you think it's possible to add others? pattern, minimum, maximum, min_length, max_length, ...
That might solve the problem (in my case at least but I don't think I'm the only one using newtypes 😅), but maybe it's not that simple 😕.

**Comment by juhaku** [comment]
@ValentinColin 
> Do you think it's possible to add others? pattern, minimum, maximum, min_length, max_length, ...

Yes, I think that should be plausible, There was this other issue related to this as well https://github.com/juhaku/utoipa/issues/572.

**Comment by juhaku** [comment]
I'll remove the need for custom impl of `SchemaReferences` in next PR.
