### ISSUE TITLE
swagger-ui is blank in `todo-axum` and `axum-utoipa-bindings`

### ISSUE THREAD

**Issue by davemo88** [juhaku/utoipa#1098]
Hello,

I'm getting stated with utoipa and axum. I ran the `todo-axum` and `axum-utoipa-bindings` examples, and the `swagger-ui` page is blank for both. For `todo-axum`, redoc and rapidoc show up fine.

Thanks

**Comment by juhaku** [comment]
Note the last slash in the url. Swagger UI is dir of files and it needs the last slash in order to serve it correctly.
![image](https://github.com/user-attachments/assets/af00bb2d-a9c6-4a3a-b58a-331a986ff91f)

**Comment by davemo88** [comment]
whoops, that did it. thanks!
