### ISSUE TITLE
Replace proc-macro-error with proc-macro-error2

### ISSUE THREAD

**Issue by kanpov** [juhaku/utoipa#1105]
As per https://github.com/rust-lang/docs.rs/issues/2595 :
- proc-macro-error is unmaintained with creator being unreachable
- syn 1.x being pulled in likely means duplication of syn

So if the conversion is easy, the affected `utoipa-gen` should be converted asap imo.

**Comment by juhaku** [comment]
`utoipa-gen` does not use `proc-macro-error` but instead it is probably coming from some inner dependency: Duplicate for https://github.com/juhaku/utoipa/issues/1028

**Comment by juhaku** [comment]
As added context, it did use it before but the latest releases does not use it. It is at least known to be used by the `rust_decimal` crate. But perhaps there are others as well.
