### ISSUE TITLE
`routes!` macro has a relative call to itself

### ISSUE THREAD

**Issue by leebenson** [juhaku/utoipa#1106]
The [routes! macro](https://github.com/juhaku/utoipa/blob/3d6b1f97d6cd6216f8b26dc9a8c86e970790ae8a/utoipa-axum/src/lib.rs#L125) calls itself relatively -- examples: [here](https://github.com/juhaku/utoipa/blob/master/utoipa-axum/src/lib.rs#L137) and [here](https://github.com/juhaku/utoipa/blob/3d6b1f97d6cd6216f8b26dc9a8c86e970790ae8a/utoipa-axum/src/lib.rs#L137).

This makes nesting this macro inside another impossible unless `routes` is already in scope.

**Comment by juhaku** [comment]
Right, I probably didn't think that, I changed it the `$crate` reference thus allowing it not to be imported.
