### ISSUE TITLE
[5.0.0-rc0] The `ToSchema` :: `bound` macro attributes is currently missing

### ISSUE THREAD

**Issue by irevoire** [juhaku/utoipa#1109]
Hello,

I’m trying to use the latest version of utoipa on a generic structure, and the documentation is a bit vague but links to a good example: https://github.com/juhaku/utoipa/blob/master/utoipa-gen/tests/schema_generics.rs
Except, when I try to use the `bound` parameter, it doesn’t work:
```
error: unexpected attribute: bound, expected any of: example, examples, xml, title, rename_all, max_properties, min_properties, as, default, deprecated, description
   --> meilisearch/src/routes/mod.rs:176:10
    |
176 | #[schema(bound = "T: ToSchema", rename_all = "camelCase")]
    |          ^^^
```

It looks like this attribute hasn’t been re-implemented in the latest rc

**Comment by juhaku** [comment]
Yes that attribute has been added in #1079 PR but the `rc` has been released earlier. If you want to use the `bound` attribute, you must point the utoipa version to master `utoipa = {git = "..." }` for time being.

**Comment by juhaku** [comment]
I guess this can be now closed, as this is already released
