### ISSUE TITLE
Add origin header to all requests in swagger doc

### ISSUE THREAD

**Issue by simbleau** [juhaku/utoipa#1117]
How can I pass the Origin header to all requests through the swagger doc that utoipa generates?

I'm setting cookies depending on this header, so I need the swagger to pass it with the request.

**Comment by juhaku** [comment]
In OpenAPI headers are in the form of params. So headers are provided as params on the handler annotated with `#[utoipa::path(...)]` https://docs.rs/utoipa/latest/utoipa/attr.path.html#params-attributes. Alternative way to provide headers to all paths is to modify the generated OpenAPI before it is being served. To this you can use Modify trait https://docs.rs/utoipa/latest/utoipa/trait.Modify.html or just directly modify the OpenAPI before serving it.

Headers can only be provided via tuple params, and not in the form of `IntoParams`.
```
params(
    ("Origin" = String, Header, description = "Origin header"),
)
```
