### ISSUE TITLE
ToSchema fails with Option

### ISSUE THREAD

**Issue by mikereid1** [juhaku/utoipa#1127]
In `5.0.0` taking the example from the README and using an Option:
```rust
#[derive(ToSchema)]
struct Account {
    id: Option<i32>,
}
```

the following error is produced:
```
no variant or associated item named `from_iter` found for enum `SchemaType` in the current scope
```

Has something else changed which is not clear in the docs or that I am missing? Thanks!

**Comment by juhaku** [comment]
That's weird, should not be, since utoipa should not compile if that is not possible. I created test project and it compiles without issues. 
![image](https://github.com/user-attachments/assets/4674e1b6-adfe-48e5-8ae1-b32456f0e9e1)

**Comment by mikereid1** [comment]
I just figured out that the difference between my working project and non-working project is the `edition` in the toml file.
my project had `edition = "2018"` and with `edition = "2021"` it works 🙈

**Comment by DenuxPlays** [comment]
> Nonetheless probably the edition `2018` compiles something differently to `2021` which cause it not work work and might be that utoipa relies on some functionality that is only available since edition `2021`.

If this is true (probably needs testing) can we document it?

**Comment by juhaku** [comment]
@mikereid1 Ah, now I know what is going on, Indeed `2021` versus `2018` editions work bit differently. If you import the `use std::iter::FromIterator;` it will work on the above cases, Seems like edition `2021` will be able to work without external import of `FromIterator` trait.
