### ISSUE TITLE
Support for older OpenAPI spec versions

### ISSUE THREAD

**Issue by sgg-jhodgson** [juhaku/utoipa#1130]
Is it possible to support 3.0.3 in utoipa 5.0? 

Unfortunately the the cpp generators I'm using don't seem to have great support for 3.1.0, none of them support `allOf` and this appears to be the method for defining nullable types in 3.1.0.

Thanks for the awesome library!

**Comment by juhaku** [comment]
It could, it just that I just ripped off the parts needed for the support. Though that support would need separate set of types per OpenAPI version which is not optimal. Also the code generation side would need some conditional logic based on selected version. Yet the could not be supported simultaneously but only via a feature flag.

Reason it does not support. is that the maintenance overhead gets quite big. The biggest eye sore for the between the OpenAPI 3.0.3 and 3.1. is the absence / presence of `nullable` field.

**Comment by sgg-jhodgson** [comment]
yeah fair enough - this is more a fault of the generator than utoipa tbh, was just hoping there might be a workaround.

Feel free to close if there's no real demand for this, hopefully generators will catch up!

**Comment by sgg-jhodgson** [comment]
Actually @juhaku  one more point on this.

`oneOf` is often better supported than `allOf`, and after a bit of reading, in nullable situations it seems like using `oneOf` might be more appropriate.

What was the motivation behind using `allOf`?

**Comment by juhaku** [comment]
> What was the motivation behind using `allOf`?

Probably a brain fart :laughing: was the motivation, true that the `oneOf` is actually better choice and has been since changed to `oneOf` in the later releases after `utoipa 5.0.0`.

**Comment by juhaku** [comment]
Closing this for now, but if there is more to this, it can be reopened of course. As of now there is no big plans for supporting supporting older OpenAPI spec versions and at least for now the demand does not seem to be high.
