### ISSUE TITLE
"identifier" field missing from license

### ISSUE THREAD

**Issue by fsasieta** [juhaku/utoipa#1139]
Great crate!

One thing I noticed while I dabbled in updating to the 5.0.0, and my pre-commit hooks found (I use lin-openapi). The license object does not support specifying an identifier, see: https://spec.openapis.org/oas/latest.html#fixed-fields-2  . This errors on that particular check, but I did notice the License object defined here https://github.com/juhaku/utoipa/blob/master/utoipa/src/openapi/info.rs#L207-L218 did not contain it. I did a quick git search for any issues that were tracking it and couldn't find it, so decided to open this

**Comment by juhaku** [comment]
Oh, thanks for reporting, this must have been missed when updating to 3.1 from 3.0 as 3.0 does not have this field. Need to add this.

**Comment by juhaku** [comment]
PR is on the way which adds identifier field. It can also be derived. But by default it is not going to be filled.
