### ISSUE TITLE
IntoParams is not satisfied

### ISSUE THREAD

**Issue by c1wren** [juhaku/utoipa#116]
I have some actix web query structs that I cannot derive IntoParams because only primitive and String types are supported. Is there a way of skipping that and just providing the query params in the params(...) section in the #[path...] derive?

**Comment by juhaku** [comment]
Currently no, then I need to make a new release for that. Can you provide bit more context in what situation the IntoParams cannot be used?

**Comment by c1wren** [comment]
I often have a sort direction and sort option in the query.

```rust

#[derive(Debug, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")] 
enum SortOption {
    None,
    Title,
    CreatedAt,
}

#[derive(Deserialize)]
#[serde(rename_all = "lowercase")]
enum SortDirection {
    Asc,
    Desc,
}

#[derive(Deserialize)]
struct MyQuery {
    ...
    sort: Option<SortOption>,
    direction: Option<SortDirection>,
    ...
}

```

**Comment by juhaku** [comment]
Oh snap.. I'll make a small change to that, so it allows other types as well. It would treat them as `String` arguments if type is not defined. What type you would define in the `params(...)` section?

**Comment by c1wren** [comment]
Option<SortDirection> and Option<SortOption>

**Comment by juhaku** [comment]
Alright. Then those types need to be `Component` wont they? Otherwise the `params(...)` will also generate "wrong" spec.
sot the `SortDirection` should be
```rust
#[derive(Deserialize, Component)]
enum SortDirection {
  Asc,
  Desc
}
```
Because the `params(...)` will use not primitive types as `$ref` to the type.

**Comment by juhaku** [comment]
I'll make it behave same way as the `params(...)` section. Just a moment

**Comment by c1wren** [comment]
> Alright. Then those types need to be `Component` wont they? Otherwise the `params(...)` will also generate "wrong" spec. sot the `SortDirection` should be
> 
> ```rust
> #[derive(Deserialize, Component)]
> enum SortDirection {
>   Asc,
>   Desc
> }
> ```
> 
> Because the `params(...)` will use not primitive types as `$ref` to the type.

Yes, I have them as a Component currently.

**Comment by juhaku** [comment]
Yeah sorry for incovenience. The next release 1.0.1 will fix this issue. And allow the `Component` type params with `IntoParams` trait.

**Comment by juhaku** [comment]
#119 #118

**Comment by c1wren** [comment]
It now works! Much appreciated!
