### ISSUE TITLE
When the same routing function exists in different mods, the `try it out` feature of the document will use the same endpoint.

### ISSUE THREAD

**Issue by saying121** [juhaku/utoipa#1170]
```rust
use std::{
    io::Error,
    net::{Ipv4Addr, SocketAddr},
};

use tokio::net::TcpListener;
use utoipa::OpenApi;
use utoipa_axum::router::OpenApiRouter;
use utoipa_swagger_ui::SwaggerUi;

const TODO_TAG: &str = "todo";

mod one {
    #[utoipa::path(
        get,
        path = "/list/one",
        responses(
            (status = 200, description = "List all todos successfully", body = ())
        )
    )]
    async fn list_todos() {
        unimplemented!()
    }
}

mod two {
    #[utoipa::path(
        get,
        path = "/list/two",
        responses(
            (status = 200, description = "List all todos successfully", body = ())
        )
    )]
    async fn list_todos() {
        unimplemented!()
    }
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    #[derive(OpenApi)]
    #[openapi(
        tags(
            (name = TODO_TAG, description = "Todo items management API")
        ),
        paths(
            one::list_todos, two::list_todos,
        )
    )]
    struct ApiDoc;

    let (router, api) = OpenApiRouter::with_openapi(ApiDoc::openapi()).split_for_parts();

    let router =
        router.merge(SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json", api.clone()));

    let address = SocketAddr::from((Ipv4Addr::UNSPECIFIED, 8080));
    let listener = TcpListener::bind(&address).await?;
    axum::serve(listener, router.into_make_service()).await
}
```

```toml
utoipa = "=5.1.3"
utoipa-swagger-ui = "=8.0.3"
```

![image](https://github.com/user-attachments/assets/3fcfd588-9f4c-4dde-94e0-7cd5584875fe)
![image](https://github.com/user-attachments/assets/86e3e716-3334-43fe-a360-093f93be87e0)

Click try it out and they request the same url

**Comment by juhaku** [comment]
I am afraid that this is bug in Swagger UI itself :thinking: The what happens when `Try it out` and `Execute` buttons are pressed is out of `utoipa`'s control. It seems that it still generates the correct API doc.

**Comment by juhaku** [comment]
Whats more, The API cannot be represented that way. Both of the endpoints will return Not Found, (maybe that is the reason why both of the results will show `list/one` in the curl call.)

As the docs state https://docs.rs/utoipa-axum/latest/utoipa_axum/router/struct.OpenApiRouter.html#method.with_openapi
> Initiates a new OpenApiRouter`...
```rust
let (router, api) = OpenApiRouter::with_openapi(ApiDoc::openapi()).split_for_parts();
```
https://docs.rs/utoipa-axum/latest/src/utoipa_axum/router.rs.html#193 It will create a new `axum::Router` only merging the OpenApi` With the above code the endpoints annotated with `#[utoipa::path(...)]` are not added to the axum Router at all.

**Comment by saying121** [comment]
This happened after upgrading utoipa version.

```
utoipa = { version = "4.2.3", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["axum"] }
```

The previous version worked just fine.

**Comment by juhaku** [comment]
Sorry for being bit unclear.

If you define the `paths` within the `#[openapi(...)]` you must still define the routes to the `router` somehow. E.g. the same way you would define them to `axum::Router` as shown below.
```rust
#[derive(OpenApi)]
    #[openapi(
        tags(
            (name = TODO_TAG, description = "Todo items management API")
        ),
        paths(
            one::list_todos, two::list_todos,
        )
    )]
    struct ApiDoc;

    let (router, api) = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .route(routing::get("/path", one::list_todos)).route(routing::get("/path2", two::list_todos))
        .split_for_parts();
```
This is not is not super efficient as you register them "two" times ones for `axum::Router` and once for `OpenApi`. Instead you can register them directly with `routes!()` macro.
```rust
#[derive(OpenApi)]
    #[openapi(
        tags(
            (name = TODO_TAG, description = "Todo items management API")
        )
    )]
    struct ApiDoc;

    let (router, api) = OpenApiRouter::with_openapi(ApiDoc::openapi())
        .routes(routes!(one::list_todos))
        .routes(routes!(two::todos))
        .split_for_parts();
```

**Comment by saying121** [comment]
I think this problem has nothing to do with route. Even if I add them to router. Swagger ui will still access the same url.

This problem occurred in another project. There was no problem before updating the version. This problem occurred after I updated to the latest version.

**Comment by juhaku** [comment]
It does seem to work with other OpenAPI spec visualization tool like `Scalar`. However the issue actually is in the `operation_id` of the endpoint. Swagger UI seems to strictly use the `operation_id` to call the actual endpoint which must be unique for the OpenAPI itself. Excerpt from the docs: https://docs.rs/utoipa/latest/utoipa/attr.path.html#path-attributes
> `operation_id = ...` Unique operation id for the endpoint. By default this is mapped to function name. The operation_id can be any valid expression (e.g. string literals, macro invocations, variables) so long as its result can be converted to a String using String::from.

If you define the endpoints with different `operation_id` they will start to work.
```rust
mod one {
    #[utoipa::path(
        get,
        path = "/list/one",
        operation_id = "list_todos_one",
        responses(
            (status = 200, description = "List all todos successfully", body = ())
        )
    )]
    pub async fn list_todos() {
        println!("list todos one")
    }
}

mod two {
    #[utoipa::path(
        get,
        path = "/list/two",
        operation_id = "list_todos_two",
        responses(
            (status = 200, description = "List all todos successfully", body = ())
        )
    )]
    pub async fn list_todos() {
        println!("list todos two")
    }
}
```

**Comment by saying121** [comment]
> It does seem to work with other OpenAPI spec visualization tool like `Scalar`. However the issue actually is in the `operation_id` of the endpoint. Swagger UI seems to strictly use the `operation_id` to call the actual endpoint which must be unique for the OpenAPI itself. Excerpt from the docs: https://docs.rs/utoipa/latest/utoipa/attr.path.html#path-attributes
> 
> > `operation_id = ...` Unique operation id for the endpoint. By default this is mapped to function name. The operation_id can be any valid expression (e.g. string literals, macro invocations, variables) so long as its result can be converted to a String using String::from.
> 
> If you define the endpoints with different `operation_id` they will start to work.
> 
> ```rust
> mod one {
>     #[utoipa::path(
>         get,
>         path = "/list/one",
>         operation_id = "list_todos_one",
>         responses(
>             (status = 200, description = "List all todos successfully", body = ())
>         )
>     )]
>     pub async fn list_todos() {
>         println!("list todos one")
>     }
> }
> 
> mod two {
>     #[utoipa::path(
>         get,
>         path = "/list/two",
>         operation_id = "list_todos_two",
>         responses(
>             (status = 200, description = "List all todos successfully", body = ())
>         )
>     )]
>     pub async fn list_todos() {
>         println!("list todos two")
>     }
> }
> ```


The problem is indeed here

**Comment by juhaku** [comment]
Duplicate for #1373
