### ISSUE TITLE
Undocumented serde_json dependency

### ISSUE THREAD

**Issue by Cschlaefli** [juhaku/utoipa#1172]
I'm a new to rust, so not sure if this is an actual issue or I missed some documentation somewhere, but I get a compile error saying `use of undeclared crate or module serde_json` when using #[schema(default = something)]] in a struct deriving ToSchema.

It's easy enough to resolve by adding serde_json manually, just couldn't find any documentation of it as a dependency or features I might be missing.

Package versions and code for minimal replication.

```
[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
utoipa = { version = "5.1.3", features = ["uuid", "axum_extras", "macros"] }
uuid = { version = "1.11.0", features = ["serde"] }
```

```
use serde::Deserialize;
use utoipa::{IntoParams, ToSchema};

#[derive(Deserialize, IntoParams, ToSchema)]
pub struct Pagable {
    #[schema(default = 0)]
    pub page: Option<i64>,
    #[schema(default = 10)]
    pub page_size: Option<i64>,
}
```

**Comment by juhaku** [comment]
Right, sure it is not mentioned, But I kind of assume that it is quite obvious to have `serde` and `serde_json` dependencies added if one is going to do anything with JSON. `serde` just adds the traits but `serde_json` does provide the implementation. And isn't it necessary if you are going to send and receive JSON by your API whether it is done with `axum` or `actix-web`.

**Comment by Cschlaefli** [comment]
This is the first crate I've run into where my crate has to explicitly declare a crate dependency that wasn't a behind a really obvious feature flag like `serde` or `uuid`. I think it's because the serde_json reference is used in  `ToSchema`  `derive_to_schema` which uses the `impl ToTokens for AnyValue` but only if the struct deriving it has fields with the `schema` attribute. 

In `axum` at least you can send and receive json with a feature flag without your crate having a direct `serde_json` dependency, at least until you need to use a `serde_json::Value` type somewhere.

Not really any issue, I was just confused by it, but I can probably just read up on `proc_macro_derive`. Closing because practically you're right. Thanks for the response.

**Comment by Sufflope** [comment]
Hello, I've been bit by this too, and yes I have projects which use `actix-web` and `utoipa` but do not need a direct dependency to `serde_json` :) Adding it would appear like an unused dependency to dependency linting tools.

The good practice I have stumbled upon in my proc-macro adventures in that case is to keep the macros "self-contained" by depending on `<dependency>` in the crate providing the derive, re-export it, and in the generated code, to reference `<crate>::<dependency>::...`

So in the case of utoipa, have feature `macros` add a dependency to `serde_json`, add a `#[cfg(feature = "macros")] #[doc(hidden)] pub use serde_json` to lib around L240 where you `pub use utoipa_gen::*;` and generate code with `utoipa::serde_json::...`.

Happy to provide a PR if that sounds reasonable to you.

**Comment by juhaku** [comment]
Great, sounds good, I was wondering something like that perhaps only a re-export for `serde_json` directly without any other modules in between. But I haven't got to it. Anyways thanks for submitting a PR.

**Comment by Sufflope** [comment]
About the intermediate module, as I said it is to not clutter your root crate. Those public re-exports are hidden in the docs but still show up e.g. in autocomplete in an IDE. So the `gen` module acts as a sort of warning `hic sunt dracones` that it's messy stuff for the messy macros system :smile: But it's a matter of style in the end, if you prefer to have a `utoipa::serde_json` module nothing forbids it.

**Comment by juhaku** [comment]
Good point
