### ISSUE TITLE
actix-web with `ResourceFiles`

### ISSUE THREAD

**Issue by ctron** [juhaku/utoipa#1173]
I am trying `utoipa_actix_web` with `ResourceFiles`, and to struggle a bit. Here is the snippet:

```rust
use actix_web_static_files::resource_files::ResourceFiles;

pub fn configure(config: &mut utoipa_actix_web::service_config::ServiceConfig, ui: &UiResources) {
    config.service(ResourceFiles::new("/", ui.resources()).resolve_not_found_to(""));
}
```

I can't add `ResourceFiles` with service, because it doesn't implement `OpenApiFactory`. Makes sense. But how do I work around this?

It's ok to just leave this out of the OpenAPI spec.

**Comment by ctron** [comment]
I came up with this:

```rust

pub fn configure(config: &mut utoipa_actix_web::service_config::ServiceConfig, ui: &UiResources) {
    config.service(NoSpecWrapper(
        ResourceFiles::new("/", ui.resources()).resolve_not_found_to(""),
    ));
}

struct NoSpecWrapper<T: HttpServiceFactory>(pub T);

impl<T: HttpServiceFactory> HttpServiceFactory for NoSpecWrapper<T> {
    fn register(self, config: &mut AppService) {
        self.0.register(config);
    }
}
impl<T: HttpServiceFactory> OpenApiFactory for NoSpecWrapper<T> {
    fn paths(&self) -> utoipa::openapi::path::Paths {
        Default::default()
    }

    fn schemas(
        &self,
        _schemas: &mut Vec<(
            String,
            utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>,
        )>,
    ) {
        Default::default()
    }
}
```

Not sure that works, need to test. But I think this should be somehow part of the crate.

**Comment by juhaku** [comment]
Yeah, I have totally ignored that it would be useful for `ServiceConfig` to also have direct access to `actix_web::web::ServiceConfig` :facepalm: 

I shortly fix this with PR and make a release for it.

**Comment by juhaku** [comment]
This PR #1174 Adds similar `map` method for `ServiceConfig` that is present in `Scope` and `UtoipaApp` which allows direct access to underlying actix_web type which in this case is `actix_web::web::ServiceConfig`.
