### ISSUE TITLE
KnownFormat disparity between utoipa and utoipa-gen

### ISSUE THREAD

**Issue by jeff-hiner** [juhaku/utoipa#1175]
I noticed this when trying to apply `#[schema(format = Ipv4)]` inside the derive for `ToSchema` to an element of type `std::net::Ipv4Addr`. I got an error message saying it wasn't one of the supported types, even though it's present in utoipa 5:

https://docs.rs/utoipa/latest/utoipa/openapi/schema/enum.KnownFormat.html

Apparently the enum inside utoipa-gen is distinct because it's in a proc-macro crate (named the same), and doesn't include this variant at all:

https://github.com/juhaku/utoipa/blob/master/utoipa-gen/src/schema_type.rs#L308

**Comment by juhaku** [comment]
Oh man, I must have missed it out, Need to check their correctness and add those missing.

**Comment by juhaku** [comment]
@jeff-hiner Now there is a PR to fix this, however you get the same result with providing custom format with literal str `#[schema(format = "ipv4")]`.
