### ISSUE TITLE
Non-working multipart example

### ISSUE THREAD

**Issue by Kimishu** [juhaku/utoipa#1220]
Hi there, I've updated this question for more concrecity.
I need to upload some data, for example a file, and although I need a documentation for it.
I've read this [example](https://docs.rs/utoipa/latest/utoipa/attr.path.html#defining-file-uploads)
So, I got something like this. Two errors appeared:
1) in `update_routes()` : ```the trait bound `fn(TestForm) -> impl Future<Output = impl IntoResponse> {test_handler::post_example}: Handler<_, _>` is not satisfied```
2) in the handler, in argument `_data: TestForm` : ``` the trait bound `TestForm: FromRequest<(), axum_core::extract::private::ViaParts>` is not satisfied
Function argument is not a valid axum extractor. ```
I tried to add a `FromRequest` but it causes more errors.
```rust
pub fn update_routes() -> OpenApiRouter {
    OpenApiRouter::new().routes(routes!(
        post_example
    ))
}

#[derive(ToSchema)]
struct TestForm {
    #[schema(content_media_type = "application/octet-stream")]
    file_bytes: Vec<u8>
}

#[utoipa::path(
    tag = "UPDATES",
    post,
    path = "/create",
    responses(
        (status = 200, description = "Done")
    ),
    request_body(content = TestForm, content_type = "multipart/form-data")
)]
#[debug_handler]
async fn post_example(_data: TestForm) -> impl IntoResponse {
    return StatusCode::OK
}
```

**Comment by juhaku** [comment]
Closing this now since the question in discussions https://github.com/juhaku/utoipa/discussions/1230
