### ISSUE TITLE
Axum extras integration

### ISSUE THREAD

**Issue by juhaku** [juhaku/utoipa#123]
Tracking issue for deeper integration between axum and utoipa. Integration is similar to one existing for actix-web and rocket frameworks. 

**Tasks**:
- [x] Add axum integration for Swagger in utoipa-swagger-ui
- [x] Add axum path and query parameter integration to utoipa (utoipa-gen) and write tests. 
- [ ] Write docs

**Comment by jacobsvante** [comment]
@juhaku Looking forward to this so much! Any concrete plans on doing an implementation?

**Comment by jacobsvante** [comment]
I completely understand! This is open source, so you don't owe anyone any apologies. Thank you for your contributions to the community thus far.

**Comment by juhaku** [comment]
@jacobsvante The axum integration will get to the next release 2.0.0 and work will be started in near future
