### ISSUE TITLE
Schema exclusive_minimum should be a boolean in OpenAPI to complement minimum

### ISSUE THREAD

**Issue by zhaohan-dong** [juhaku/utoipa#1267]
See example here: https://swagger.io/docs/specification/v3_0/data-models/data-types/

**Comment by juhaku** [comment]
> See example here: https://swagger.io/docs/specification/v3_0/data-models/data-types/

That is for OpenAPI 3.0

> OAS 3 This guide is for OpenAPI 3.0.

Open API 3.1 is compliant with JSON schema, thus the `exclusive_minimum` value is respected accordingly https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-validation-00#rfc.section.6.2.5

**Comment by zhaohan-dong** [comment]
I see. Thanks!
