### ISSUE TITLE
In a struct that derives `Component`: error: expected at least one angle bracket argument but was 0

### ISSUE THREAD

**Issue by oliver-impero** [juhaku/utoipa#138]
In a struct that derives `Component`:
```rs
error: expected at least one angle bracket argument but was 0
   |
29 |     pub ids: Option<VecParam<uuid::Uuid>>,
   |                              ^^^^
```

**Comment by juhaku** [comment]
This is know issues where path expression is not supported within generic arguments when used withing `Component` luckily it has easy work around when type is defined without the path expression like so `pub ids: Option<VecParam<Uuid>>,`.
