### ISSUE TITLE
Features are not additive

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#148]
Running `cargo check --all-features` on master currently produces the following errors:

```
error[E0119]: conflicting implementations of trait `ext::ArgumentResolver` for type `ext::PathOperations`
  --> utoipa-gen/src/ext/rocket.rs:23:1
   |
23 | impl ArgumentResolver for PathOperations {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `ext::PathOperations`
   |
  ::: utoipa-gen/src/ext/actix.rs:31:1
   |
31 | impl ArgumentResolver for PathOperations {
   | ---------------------------------------- first implementation here

error[E0119]: conflicting implementations of trait `ext::PathOperationResolver` for type `ext::PathOperations`
   --> utoipa-gen/src/ext/rocket.rs:186:1
    |
186 | impl PathOperationResolver for PathOperations {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `ext::PathOperations`
    |
   ::: utoipa-gen/src/ext/actix.rs:174:1
    |
174 | impl PathOperationResolver for PathOperations {
    | --------------------------------------------- first implementation here

error[E0119]: conflicting implementations of trait `ext::PathResolver` for type `ext::PathOperations`
   --> utoipa-gen/src/ext/rocket.rs:259:1
    |
259 | impl PathResolver for PathOperations {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `ext::PathOperations`
    |
   ::: utoipa-gen/src/ext/actix.rs:217:1
    |
217 | impl PathResolver for PathOperations {
    | ------------------------------------ first implementation here

error[E0592]: duplicate definitions with name `get_type_path`
   --> utoipa-gen/src/ext/actix.rs:108:5
    |
108 |     fn get_type_path(ty: &Type) -> &TypePath {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ duplicate definitions for `get_type_path`
    |
   ::: utoipa-gen/src/ext/rocket.rs:159:5
    |
159 |     fn get_type_path(ty: &Type) -> &TypePath {
    |     ---------------------------------------- other definition for `get_type_path`

error[E0592]: duplicate definitions with name `get_fn_args`
   --> utoipa-gen/src/ext/actix.rs:141:5
    |
141 |     fn get_fn_args(fn_args: &Punctuated<FnArg, Comma>) -> impl Iterator<Item = Arg> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ duplicate definitions for `get_fn_args`
    |
   ::: utoipa-gen/src/ext/rocket.rs:89:5
    |
89  |     fn get_fn_args(fn_args: &Punctuated<FnArg, Comma>) -> impl Iterator<Item = Arg> + '_ {
    |     ------------------------------------------------------------------------------------ other definition for `get_fn_args`
```

**Comment by juhaku** [comment]
Yes, the project cannot be "run" with `--all-features` flag set. All `*_extras` features are exclusive to each other and contains clashing implementations. This is alright since no-one should have both `rocket_extras` and `actix_extras` enabled at the same time. 

Depending on of course your development setup, how easy it is to define features needed for current set of work. But I am managing features explisitly within the project directory and changing "active" features according to the needs which allows simplified testing of different feature setups.

**Comment by juhaku** [comment]
In order to support `--all-features` there is a need to seprate all extensions to own modules and create a new library for which is global for all extensions. This is benefinicial in case someone wants to create own extension to antoher framework which does not have extension implemented. With it the extensions should define this core lib as dependency which would provide global types for all extensions. This way the main create will not contain conflicting features. This is breaking change and if done, it need to be done for next major release.

**Comment by juhaku** [comment]
@kellpossible I tried this for the previous release and it seemed quite hard (so hard that it felt like waste of effort without actual gains) to avoid having conflicting dependencies. Most likely I would have needed to split everything so small pieces and the build time would have increased and still after all changes there was no quarantees it would have worked and it appeared not to. 

For quick development I have `.vscode/settings.json` in project root which contains rust_analyzer configuration for quicly to change active features to test different feature sets. For nvim I have a similarly a `nvim/rust-analyzer.json` file in the project root which contains the active features for quick changing the features used currently for development.
_.nvim/rust-analyzer.json_
```json
  "cargo": {
    "allFeatures": false,
    "noDefaultFeatures": true,
    "features": [
      "utoipa/json",
      "utoipa/yaml",
      "utoipa/uuid",
      "utoipa/smallvec",
      "utoipa/actix_extras",
      "utoipa/chrono",
      "utoipa/debug",
      "utoipa/decimal",
      "utoipa/time"
    ]
  }
}
```
The rust-tools won't by default recognize this file but I have made some changes to the rust tools configs in order it to append features from this file to the rust analyzer.
_rust-tools server on_init configuration_
```lua
		on_init = function(client)
			local cwd = vim.fn.getcwd()
			local local_config_path = cwd .. "/.nvim/rust-analyzer.json"

			local local_config = vim.fn.system("cat " .. local_config_path)

			if string.find(local_config, "No such file or directory") ~= nil then
				return true
			end

			local cfg =
				vim.tbl_deep_extend("force", client.config.settings["rust-analyzer"], vim.fn.json_decode(local_config))
			client.config.settings["rust-analyzer"] = cfg

			client.notify("workspace/didChangeConfiguration", { settings = client.config.settings })
			return true
		end,

```

I have found out that this is probably easiest way to get around changing the active features.

**Comment by juhaku** [comment]
Closing this for now. But can be reopened if there is ever a need to.

**Comment by Zomatree** [comment]
My project uses both axum and rocket in one workspace and i require both features to be enabled. is there any possibility of this being revisited and fixed?
