### ISSUE TITLE
Inline schemas

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#149]
I'm dealing with an API that has a unique type for each response body, having them all as components is a bit of a headache, and they won't be re-used in other endpoints.  It would be nice to have a way to optionally inline schema definitions. Perhaps with a special wrapper like `inline()`, the `path` macro could insert the schema for a derived `Component` inline rather than attempting to reference it?

**Comment by kellpossible** [comment]
For reference https://swagger.io/specification/#media-type-object `schema` property is optionally a `Schema Object` or a `Reference Object`. Perhaps there are some other areas of the `path` macro that would benefit from being able to inline schemas too.

**Comment by kellpossible** [comment]
#153 implements this for the `path!()` macro, but additionally it would be good to have inline fields with the `Component` derive macro, based on a `#[component(inline)]` field attribute.

**Comment by juhaku** [comment]
Yes thats true.

**Comment by juhaku** [comment]
Closing this one since the PR has been already merged.
