### ISSUE TITLE
IntoParams style container attribute

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#151]
It would be nice to have a single attribute for all fields of a struct deriving `IntoParams` for `style`.

Perhaps something like:

```rust
#[derive(Deserialize, IntoParams)]
#[param(style = Form)]
struct Filter {
    /// Foo database id.
    id: u64,
    /// Datetime since foo is updated.
    since: Option<String>,
}
```

Also what happens when different parameters in the same path have different parameter styles? Perhaps the `style` attribute only makes sense on the container level?

**Comment by juhaku** [comment]
One could override the `style` for each parameter but specifying `style` that is not supported for `Path` arguments will result most likely corrupt OpenAPI spec and certainly will not work the way expected. But defining of a correct `style` is a responsibility of a user.
