### ISSUE TITLE
OpenApi derive `components` section does not support namespacing

### ISSUE THREAD

**Issue by HollayHorvath** [juhaku/utoipa#152]
For the OpenApi derive to work all the components must be in scope because you cannot use paths.

Taking from the Axum todo example, this is possible:
```Rust
use crate::todo::{Store, Todo, TodoError};

#[derive(OpenApi)]
#[openapi(
    handlers(
        todo::list_todos,
        todo::create_todo,
        todo::mark_done,
        todo::delete_todo,
    ),
    components(Todo, TodoError),
    modifiers(&SecurityAddon),
    tags(
        (name = "todo", description = "Todo items management API")
    )
)]
struct ApiDoc;
```

this is not:
```Rust
#[derive(OpenApi)]
#[openapi(
    handlers(
        todo::list_todos,
        todo::create_todo,
        todo::mark_done,
        todo::delete_todo,
    ),
    components(crate::todo::Todo, crate::todo::TodoError),
    modifiers(&SecurityAddon),
    tags(
        (name = "todo", description = "Todo items management API")
    )
)]
struct ApiDoc;
```
and if you have lots of `components` this gets painful quickly. The `handlers` section already supports this.

**Comment by kellpossible** [comment]
I've also run into this, I was wondering does the OpenApi spec support having names like `crate::todo::TodoError` for components?

**Comment by HollayHorvath** [comment]
I'm not sure about that at all. If not, the macro could support some kind
of renaming system maybe? Currently the only solution is polluting the
namespace.

**Comment by kellpossible** [comment]
I opted for `use x as y` aliasing syntax to work around it so far

**Comment by kellpossible** [comment]
And putting the `ApiDoc` in its own module to avoid polluting the surrounding namespace.

**Comment by HollayHorvath** [comment]
I'm doing both, but having the derive do this would be nice. I'm not sure how flexible derives are, but my dream solution would be something similar to this:
```
components(
  crate::todo::Todo as Todo,
  crate::todo::TodoError as TodoError
)
```

**Comment by juhaku** [comment]
This is relatively small change, The way it handles the components can be changed to support this path expression so that following would work as well. I can test this out in near future when I get time for this.
```rust
components(
  crate::todo::Todo,
  crate::todo::TodoError
)
```
