### ISSUE TITLE
How to configure API introduction?

### ISSUE THREAD

**Issue by oliver-impero** [juhaku/utoipa#155]
1. How can I specify what it shows for "License" / how can I remove it?

![image](https://user-images.githubusercontent.com/83573812/171586444-e6f0d165-4b42-4199-88fe-20fbffe8d075.png)

2. How can I add a custom API introduction text here (using markdown)? I tried with a doc comment (using `#[doc = include_str!("API-Intro.md")]`) for my main `ApiDoc` struct that has `#[derive(OpenApi)]`, but the doc comment seems to be ignored by the generator, any idea why?

3. How can I specify the html `<title>` for the generated doc? :)

**Comment by juhaku** [comment]
You can use custom modifier to this.
```rust
struct ApiDocInfo;
impl Modify for ApiDocInfo {
    fn modify(&self, openapi: &mut openapi::OpenApi) {
        openapi.info.description = Some(include_str!("../README.md").to_string());
    }
}
```
Also with this you can modify all the info related fields as you may wish. E.g.  You could also remove the Licence as well.

**Comment by oliver-impero** [comment]
Thanks, that's very useful :)
Btw, is it also possible to modify the CSS styling?

Or to add a search field, like in slate docs? E.g.:
https://mermade.github.io/reslate
https://bestbuyapis.github.io/api-documentation

**Comment by juhaku** [comment]
> Btw, is it also possible to specify a favicon or to modify the CSS styling?

If I'm not mistaken it is not possible with the Swagger UI. But for this you should use another OpenAPI doc "browser". For example those OpenAPI's are using https://redocly.com/redoc/. I've had a plan to support this as well as an alternative to the Swagger UI but no concrete action has been taken towards this so far.
