### ISSUE TITLE
Namespaced body in responses

### ISSUE THREAD

**Issue by RemiKalbe** [juhaku/utoipa#164]
Same issue as https://github.com/juhaku/utoipa/issues/152 but with `body` in `responses`
```rust
#[utoipa::path(
    responses(
        (status = 200, body = response::WillNotWork),
    ),
)]
```
Tried on master.

**Comment by juhaku** [comment]
Response body and request body is resolved in elsewhere thus not supporting path expression. This needs a change to current implementation. I'll note this to the project's kanban board as well.

**Comment by juhaku** [comment]
From #408 the types of response body and request body are parsed with the same logic as types of the `ToSchema` and `IntoParams` structs are. This should allow defining types with paths similarly.
