### ISSUE TITLE
Override value_type for IntoParams

### ISSUE THREAD

**Issue by RemiKalbe** [juhaku/utoipa#165]
I need to override some types in my Path struct but it's not currently possible to do that*
```rust
#[derive(Debug, Deserialize, IntoParams)]
pub struct SomeStruct {
    #[param(value_type = Uuid)]
    pub some_id: SomeUUIDWrapper,
}
```
It would be great to be able to do the same thing as with `Component`
```rust
#[derive(Debug, Deserialize, Component)]
pub struct SomeStruct {
    #[component(value_type = Uuid)]
    pub some_id: SomeUUIDWrapper,
}
```
-----
*for now I'll just remove the `IntoParams` and define `params` in `path` and stay on 1.1.0 as it's not possible on master to have a `Path<SomeStruct>` that doesn't implement IntoParams

**Comment by juhaku** [comment]
Yes, this is indeed not implemented but pretty good idea though. I'll note this one as well to the project's kanban board.
