### ISSUE TITLE
Allow `serde_json::Value` as `any` or `object`

### ISSUE THREAD

**Issue by JSH32** [juhaku/utoipa#168]
In my API I would like a way to send `any` data. Something like this
```rs
    // Optional data, can be any JSON value
    #[serde(skip_serializing_if = "Option::is_none")]
    #[component(value_type = Any)]
    data: Option<serde_json::Value>,
````
Unfortunately swagger-ui throws an error and it does not display it properly

**Comment by juhaku** [comment]
At the moment it is not possible indeed, this is being discussed here: #162.

**Comment by juhaku** [comment]
I'm closing this since this actually is same need for functionality to override the with Any value in some cases where it is explisitly wanted not to expose the actual type to the user and show only `object` instead.
