### ISSUE TITLE
Add support for API method description

### ISSUE THREAD

**Issue by ok300** [juhaku/utoipa#170]
In the sample petstore swagger[^1], there is a description for each supported API method. For example, `Add a new pet to the store` [^2].

So far I found no way to add such a method description in utoipa. I tried different ways to add a description or summary to the handler definition, or to the `#[utoipa::path(...)]` annotations, but couldn't get it to work. Looks like its currently not supported.

Can you please add support for that? Would be very useful.

Thanks.

[^1]: https://petstore.swagger.io
[^2]: https://petstore.swagger.io/#/pet/addPet

**Comment by juhaku** [comment]
It is supported, though it is not necessary clear how it works, but you just need to add doc comments over the function and it will use it as the description. No need for additional fields in the macro. Also the first line will be the summary, and the whole doc comment is the description field. You also can take a look at any of those examples in the repository and try to run them as well.  https://github.com/juhaku/utoipa/tree/master/examples
```rust
/// This is my super cool endpoint
/// 
/// More documentation
fn foobar_endpoint() {
  // ... impl here
}
```

**Comment by ok300** [comment]
Thank you sir, works.
