### ISSUE TITLE
Custom tag names for routes.

### ISSUE THREAD

**Issue by JSH32** [juhaku/utoipa#172]
Route tags/namespaces at the moment are generated by what is provided in `handlers`. Might there be a way to specify renames for these tags so that they can be more clear? For example 
```rs
	tags(
		(paths = [route::admin::user], name = "Admin", description = "Admin endpoints."),
	),
```
on `openapi` for example?

**Comment by juhaku** [comment]
The `#[openapi(...)]` is unable to access the `tags` attribute of the path operation. Instead at the moment what can be done is to define custom `tag` along with the path operation. 
```rust
#[utoipa::path(
  tag = "Admin",
...
)]
```

**Comment by JoshRudnik** [comment]
Is there a way to sort which order the tags are placed in?

**Comment by juhaku** [comment]
No they will be organized alphabethical order according to the path. Paths with same tag will be grouped together. The paths will be placed to `BTreeMap` which will contain order by itself. And also there is no way to sort them in UI. That would require additional JavaScript from the end user but there is no way to provide such unfortunately.

**Comment by juhaku** [comment]
Closing due inactivity.
