### ISSUE TITLE
todo-warp example broken

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#173]
The `todo-warp` example is currently broken, it shows an empty page on both the `http://localhost:8080/swagger-ui/` and `http://localhost:8080/swagger-ui` paths. Perhaps this is related to https://github.com/juhaku/utoipa/pull/171 ? Checking out the previous commit 13c91491c4a5f78771d881350e969069ad5e8603, the example runs successfully.

**Comment by kellpossible** [comment]
Nevermind it might be something more recent, 39c1a50465b650fa61074c638e240f5700fc9027 also works...

**Comment by kellpossible** [comment]
Okay it looks like commit 37b616df9339ab6881677a9b7b0b0d6f69028672 broke it

**Comment by juhaku** [comment]
Yeah I broke it yesteday, and simultaneously I broke all the other examples. The current swagger config management needs some care and I address it today later on. And check the rest of the PR's as well.
