### ISSUE TITLE
Unable to provide descriptions for complex enum variants that are references

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#178]
Deriving component for this enum results in an error:

```rust
#[derive(Component)]
struct Bar {
    field: String
}

#[derive(Component)]
enum Foo {
    /// Documentation
    Variant(Bar),
}
```

error:

```text
no method named `description` found for struct `utoipa::openapi::Ref` in the current scope
```

Removing the `/// Documentation` comment resolves the error.

**Comment by juhaku** [comment]
Good finding. This is a bug, It should be possible to have a description above the variant but it will not be propagated to the doc since `$ref` types cannot have description in OpenAPI 3.0 standard. I guess fixing this should be a matter of few lines of code.

**Comment by kellpossible** [comment]
@juhaku thanks for fixing!
