### ISSUE TITLE
Component derive reference to Self points to wrong name

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#179]
```rust
#[derive(Component)]
struct Foo {
    field: Option<Box<Self>>
}
```

produces:

```json
{
  "properties": {
    "field": {
      "$ref": "#/components/schemas/Self"
    }
  },
  "type": "object"
}
```

expected:

```json
{
  "properties": {
    "field": {
      "$ref": "#/components/schemas/Foo"
    }
  },
  "type": "object"
}
```

**Comment by juhaku** [comment]
Yikes, this is not taken into account that objects could have reference to itself. Support for this could be added for sure.

**Comment by kellpossible** [comment]
It seems like https://github.com/juhaku/utoipa/issues/180 could be used as a workaround?

**Comment by kellpossible** [comment]
Or just renaming the type to `Foo` but I guess that might upset some clippy lints somewhere

**Comment by juhaku** [comment]
Yes it could be used as a workaround.
