### ISSUE TITLE
Component derive override field reference name

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#180]
It would be nice to be able to override the name chosen for a reference on a given field, because the import name used for the component provided to the parent OpenAPI might be different.

Perhaps something like this to rename the reference from `Bar` to `NewBar`:

```rust
#[derive(Component)]
struct Foo {
    #[component(rename_ref = (from = Bar, to = NewBar))
    field: Bar
}
```

The `from` and `to` syntax is to provide compatibility with types that may have multiple different reference types.

**Comment by juhaku** [comment]
Or how about if we enhance `value_type` support to handle this? Now it can handle only the supported primitive types but if we allow users to override the type with anything they this behaviour would come free. Also it would be more clear by the syntax and this way we can add virtual type `Any` for those who wish to override the represented type with just generic `object` in the OpenAPI spec?

```rust
#[derive(Component)]
struct Foo {
    #[component(value_type = NewBar)]
    field: Bar
}
```

**Comment by juhaku** [comment]
Actually the `value_type` was able to do this, it was just not fully implemented and not documented well.

**Comment by kellpossible** [comment]
@juhaku that was a great idea!
