### ISSUE TITLE
Component value_type attribute doesn't support Vec, Option, Any, etc

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#191]
With #187 these attributes can be parsed (without this PR these are compile errors), but the following cases don't appear to be supported correctly:

```rust
#[derive(utoipa::Component)]
struct Post {
    #[component(value_type = Vec<String>)]
    value: i64,
}
```

```rust
#[derive(utoipa::Component)]
struct Post {
    #[component(value_type = Option<String>)]
    value: i64,
}
```

```rust
#[derive(utoipa::Component)]
struct Post {
    #[component(value_type = Vec<Any>)]
    value: i64,
}
```

```rust
#[derive(utoipa::Component)]
struct Post {
    #[component(value_type = Option<Foo>)]
    value: i64,
}
```

```rust
#[derive(utoipa::Component)]
struct Post {
    #[component(value_type = Vec<Foo>)]
    value: i64,
}
```

**Comment by juhaku** [comment]
Haven't thought someone would use `value_type` for `Vec` or `Option`. :joy: So these cases are not implemented. I guess this needs another round of enhancing to support generic types. I'll try to add a support for them.

**Comment by juhaku** [comment]
The #203  will implement support for above types for `IntoParams` but another PR is needed for `Component` support. That will be done shortly.
