### ISSUE TITLE
Component derive attribute manual implementation 

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#195]
It would be nice to have a way to override a field property derive with a manual implementation in a similar style to serde serialize_with. Perhaps the comment for the field could be passed to the user defined function as a string to allow optional easy reuse in the description.

**Comment by kellpossible** [comment]
This would also allow working around any shortcomings in the short term that the derive may have in terms of schema expressability with attributes

**Comment by kellpossible** [comment]
Same with IntoParams attributes

**Comment by kellpossible** [comment]
The would also be good to have for response and request bodies.

**Comment by juhaku** [comment]
Yeah.. this could be neat escape hatch to configure attributes which are not available via derive or to configure programmatically items directly to the compiled documentation. Definitely could be added in future :)
