### ISSUE TITLE
Response body without schema - [u8] / application/octet-stream

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#197]
I can't figure out is it possible with the path macro to specify a response that returns a binary file for the body, say with `Content-Type` as `application/octet`

**Comment by juhaku** [comment]
Yeah it is possible by overriding the `content-type` for the Response. See here: https://docs.rs/utoipa/1.1.0/utoipa/attr.path.html#responses-attributes.

Indicate to OpenAPI doc that response body is octet stream of bytes. 
```
responses(
  (status = 200, body = String, content_type = "application/octet")
)
```

**Comment by juhaku** [comment]
Closing due inactivity.

**Comment by jayvdb** [comment]
@juhaku,

That will emit openapi of
```yaml
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
```

However that will fail to be recognised as "binary" by most openapi readers, and client generators that I've tried.
 
e.g. https://github.com/oxidecomputer/progenitor fails with
```
gen fail: UnexpectedFormat("invalid schema for application/octet-stream: Item(Schema { schema_data: SchemaData { nullable: false, read_only: false, write_only: false, deprecated: false, external_docs: None, example: None, title: None, description: None, discriminator: None, default: None, extensions: {} }, schema_kind: Type(String(StringType { format: Empty, pattern: None, enumeration: [], min_length: None, max_length: None })) })")
```

What they expect is

```yaml
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
```

**Comment by jayvdb** [comment]
The solution we found was to do
```rust
use utoipa::ToSchema;

#[derive(ToSchema)]
#[schema(value_type = String, format = Binary)]
pub struct Binary(String);

#[utoipa::path(
    ...
    request_body(
        content = Binary,
    ),
```

And then add that struct `Binary` to the openapi schemas list used for generation

```rust
#[derive(OpenApi)]
#[openapi(
    ...
    components(
        schemas(
            Binary,
            ...
        ),
    ),
    ...
```

Then the openapi looks like

```yaml
...
      requestBody:
        content:
          application/octet-stream:
            schema:
              $ref: "#/components/schemas/Binary"
        required: true
...
components:
  schemas:
    Binary:
      type: string
      format: binary
    ...

**Comment by juhaku** [comment]
Great clarification.

**Comment by jayvdb** [comment]
Is there already a better way to get `{type: string, format: binary}` ?  I was hoping that `content = [u8]` would do it.
IMO using content-type `application/octet-stream` should also trigger it.

**Comment by juhaku** [comment]
> Is there already a better way to get {type: string, format: binary} ? I was hoping that content = [u8] would do it.
IMO using content-type application/octet-stream should also trigger it.

True, I will refine this implementation and make it more smooth to use.

**Comment by juhaku** [comment]
@jayvdb 
> IMO using content-type application/octet-stream should also trigger it.

Yeah, this would need some more changes on how the content type and the schema is formed. Currently it is heavily type first architecture. This means that the content type is resolved based on the type of value. Probably support for this could be added in future. It just need to be done so that it is not a hack in the current implementation. 

The PR attached to this will fix the issue so that the content type will be recognized as schema type: string, format: binary with content type as `application/octet-stream` when request body type or response body is `[u8]`.

**Comment by Cheban1996** [comment]
I have the next response (status = 200, description = "Successfully download", content_type = "application/octet-stream"),
but content_type not exist
<img width="435" alt="image" src="https://github.com/juhaku/utoipa/assets/11075696/9eea7af8-bb17-45b8-b4e2-284bd8284329">

I expect 
```
"200": {
     "description": "Successfully download",
     "content":
          "application/octet-stream": {}
}
```
