### ISSUE TITLE
Check json examples for types that implement Serialize

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#199]
It would be nice to check json examples by optionally attempting to serialize them for types that implement `Serialize`, this way examples are ensured to be valid. Perhaps a new `json_ser!()` attribute could be added to implement this feature?

**Comment by juhaku** [comment]
Not a bad idea. But how this could be implemented? And why it would not be possible to include this kind of serializable check to the existing `json!()` attribute?

**Comment by kellpossible** [comment]
@juhaku, I was thinking that perhaps some people might not want to pay the compile time cost of serializing the example for something big, but then again, I guess that's a premature optimization, and if someone is already going to the trouble of creating the example we may as well validate it

**Comment by kellpossible** [comment]
perhaps instead a `json_no_validate!()` attribute can be added later if required :slightly_smiling_face:

**Comment by juhaku** [comment]
Yeah :+1: agree

**Comment by juhaku** [comment]
But again when people define the example with `json!()` attribute it will be serialized with `serde_json` already when it will be added to the OpenAPI spec.

**Comment by kellpossible** [comment]
> But again when people define the example with json!() attribute it will be serialized with serde_json already when it will be added to the OpenAPI spec.

That's true, but that happens at runtime, rather than compile time though? If this library is used on large projects, which I imagine it will be, build times affected by using this library could become an important issue for some users. But it's premature optimisation at this stage I guess.

**Comment by juhaku** [comment]
Oh yeah.. it will be converted to `serde_json::json!(..)` call behind the scenes.. But `json!()`call is not compile time. My hypothesis is that the `json!()` will also check whether input can be serialized to JSON or not. Least minimum it checks the format of the input as it does not let users to type unstructured data into it. 

I assume when the `utoipa::path` macro will get compiled it will then output the generated code for the path operation. Same time the `example` with `json!()` will translate to call `serde_json::json!()` but what time the `serde_json::json!()` call gets executed? Doesn't it also get expanded to the serde_json::Value notation before the application is itself compiled? More over it does get expanded but in what phase it does get expanded? :smile: 

But surely if there is something more we can do in compile time or make it faster for users are welcome additions in general.

**Comment by juhaku** [comment]
Closing due inactivity.
