### ISSUE TITLE
Unify `utoipa-gen` type parsing/schema production

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#217]
Representations of types/paths which are parsed into schemas are spread throughout `utoipa-gen` and their level of parsing support varies:

+ https://github.com/juhaku/utoipa/blob/6cec1029f57e3fd81d6b2c7e4680c34e482060e6/utoipa-gen/src/ext.rs#L21
+ https://github.com/juhaku/utoipa/blob/6cec1029f57e3fd81d6b2c7e4680c34e482060e6/utoipa-gen/src/ext/rocket.rs#L118
+ https://github.com/juhaku/utoipa/blob/6cec1029f57e3fd81d6b2c7e4680c34e482060e6/utoipa-gen/src/ext/rocket.rs#L75
+ https://github.com/juhaku/utoipa/blob/6cec1029f57e3fd81d6b2c7e4680c34e482060e6/utoipa-gen/src/lib.rs#L806 which is used in  https://github.com/juhaku/utoipa/blob/6cec1029f57e3fd81d6b2c7e4680c34e482060e6/utoipa-gen/src/path/parameter.rs#L38

It would be good to unify these somehow  if possible and gain more consistent parsing and schema production support.

**Comment by juhaku** [comment]
I'm now working on refactoring the extension related types to use one argument type and resolving logic across the extensions. 

With further PR:s we could get rid of this type once and for all in and use `ComponentPart` instead which would enable us more centralized control for parsing.
https://github.com/juhaku/utoipa/blob/6cec1029f57e3fd81d6b2c7e4680c34e482060e6/utoipa-gen/src/lib.rs#L806
