### ISSUE TITLE
Vec example is incorrect

### ISSUE THREAD

**Issue by caspermeijn** [juhaku/utoipa#225]
Adding an example to a stuct field of type Vec results in a incorrect swagger example for the struct. The generated swagger example has a double pair of square brackets. I tried multiple variants of the component example macro, but each results in the same incorrect swagger example.

For example
```rust
#[derive(Deserialize, Serialize, Component, Clone, Debug)]
pub struct LogEntry {
    #[component(example = json!(["asdf", "zxcv"]))] // <---- Problematic example
    pub tags: Vec<String>,
}
```
results in the following example in swagger:
```json
{
  "tags": [
    [
      "asdf",
      "zxcv"
    ]
  ]
}
```

Here follows a minimal rust program to reproduce the problem. 
- Start with rust-script
- Open swagger via the link
- Execute the api call
- See that response is "Json deserialize error"
```rust
#!/usr/bin/env rust-script
//! ```cargo
//! [dependencies]
//! actix-web = "4"
//! utoipa = { version = "1", features = ["actix_extras"] }
//! utoipa-swagger-ui = { version="1", features = ["actix-web"] }
//! serde = { version = "1.0", features = ["derive"] }
//! serde_json = "1.0"
//! ```

use actix_web::{post, web, App, HttpResponse, HttpServer, Responder};
use serde::Deserialize;
use serde::Serialize;
use utoipa::Component;
use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;

#[derive(Deserialize, Serialize, Component, Clone, Debug)]
pub struct LogEntry {
    #[component(example = json!(["asdf", "zxcv"]))] // <---- Problematic example
    pub tags: Vec<String>,
}

#[utoipa::path(
request_body = LogEntry,
)]
#[post("/api/logs")]
async fn add_log(new_log: web::Json<LogEntry>) -> impl Responder {
    HttpResponse::Ok().json(new_log)
}

#[derive(utoipa::OpenApi)]
#[openapi(handlers(add_log,), components(LogEntry,))]
struct ApiDoc;

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    println!("Starting swagger at: http://localhost:8080/swagger-ui/");

    HttpServer::new(move || {
        App::new()
            .service(add_log)
            .service(SwaggerUi::new("/swagger-ui/{_:.*}").url("/openapi.json", ApiDoc::openapi()))
    })
    .bind(("0.0.0.0", 8080))?
    .run()
    .await
}
```

**Comment by juhaku** [comment]
Hi, this is a known issue and has not been addressed in the functionality. What happens it tries to add the json example to the string field within the Vec. For time being you could try to add example as a single string.
```rust
#[derive(Deserialize, Serialize, Component, Clone, Debug)]
pub struct LogEntry {
    #[component(example = "asdf"))]
    pub tags: Vec<String>,
}
```
Although it does not allow mutliple example values, But it should render the correct schema for time being.

**Comment by caspermeijn** [comment]
Ok, thanks for your reaction. I will use a single string for now.

Would this be fixable by a beginner?

**Comment by juhaku** [comment]
It shouldn't be too hard. To fix this there is 2 things that need to be done.
1. The Array type in `schema.rs` needs an example field. This is missing.
2. Find a way to distinct vec field from non generic field example. Currently there is no way to do that. This is a bit tricky and most likely needs some api changes to the current logic in utoipa-gen `component.rs` file. 

And then of course tests for the changed behaviour.
