### ISSUE TITLE
utoipa_swagger_ui: doesn't work with warp

### ISSUE THREAD

**Issue by trkohler** [juhaku/utoipa#246]
![image](https://user-images.githubusercontent.com/49440211/183932542-7fe0feab-99b4-4a2a-bc56-8a87140771f3.png)
What is the recommended way to add swagger ui to arp framework? If there is any?

I tried to use it like that (https://github.com/juhaku/utoipa/blob/6e3cb4b9be5072108e999b982b17ffae117d65ac/examples/todo-axum/src/main.rs#L52) but it is not type compatible.

```
 |
36 |       .merge(SwaggerUi::new("/swagger-ui/*tail").url("/api-doc/openapi.json", ApiDoc::openapi()))
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `axum::Router`, found struct `SwaggerUi`
```

**Comment by juhaku** [comment]
Yeah that syntax is the new syntax coming in version 2.0.0 once released. In 1.1.0 release the syntax is bit more complicated similar to the existing for tide and warp framework. To see how it works one need to go back in time to see the example in that point of the releases. See here 1.1.0 example https://github.com/juhaku/utoipa/blob/utoipa-1.1.0/examples/todo-axum/src/main.rs.

**Comment by trkohler** [comment]
thanks for explaining! 
I currently forked the main to be able to make the same as written in your examples, but would be waiting for the release!
