### ISSUE TITLE
Unnamed (tuple) enum variants are unsupported for internally tagged enums

### ISSUE THREAD

**Issue by michaelmattig** [juhaku/utoipa#261]
Defining the following enum:

```rust
#[derive(serde::Serialize, utoipa::ToSchema)]
#[serde(tag = "type")]
enum Foo {
    Bar,
    Baz(Payload),
}

#[derive(serde::Serialize)]
struct Payload {
    a: String,
}
```

I get the following error from utoipa:

> Unnamed (tuple) enum variants are unsupported for internally tagged enums using the `tag = ` serde attribute
Try using a different serde enum representation

While this works fine:

```rust 
#[derive(serde::Serialize, utoipa::ToSchema)]
#[serde(tag = "type")]
enum Foo2 {
    Bar,
    Baz { a: String },
}
```

Both produce the same JSON, so why is it not possible to derive the schema in the first case?

**Comment by juhaku** [comment]
This is a serde.rs limitation unfortunately.
> This representation works for struct variants, newtype variants containing structs or maps, and unit variants but does not work for enums containing tuple variants. Using a #[serde(tag = "...")] attribute on an enum containing a tuple variant is an error at compile time.

Quote from serde.rs enum representation docs https://serde.rs/enum-representations.html

**Comment by michaelmattig** [comment]
Thanks for your quick answer!

> This representation works for struct variants, **newtype variants containing structs**

and that's what I am doing in my example. So serde is not the limiting factor here.

Also, in utoipa 1.1.0 the following **did** work:

```rust
#[derive(serde::Serialize, utoipa::Component)]
#[serde(tag = "type")]
enum Foo {
    Bar,
    Baz(Payload),
}
```

but if I upgrade to 2.0.0 and replace Component with ToSchema, it no longer works.

**Comment by juhaku** [comment]
Right, it might be because of mistakenly taking `Baz(Payload)` as tuple type, when it actually should be error when `Baz` would have more arguments to it like so `Baz(Payload, AnotherType)` This should produce the error you encountered. I need to investigate this and is regression since there has been quite a few changes since the last release. I hope to resolve this asap. Thanks for your input. :slightly_smiling_face:
