### ISSUE TITLE
Support for the repr attribute

### ISSUE THREAD

**Issue by Naymoll** [juhaku/utoipa#271]
I have this type:
```
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[derive(ToSchema)]
#[repr(u8)]
pub enum OsrmVersion {
    Osrm4 = 0,
    Osrm5,
}
```
Generated output: 
```
"OsrmVersion":{
    "type":"string",
    "enum":[
        "Osrm4",
        "Osrm5" 
    ]
}
```
Expected output: 
```
"OsrmVersion":{
    "type":"integer",
    "enum":[
        0,
        1
    ]
}
```
Is this possible to add support for the repr attribute? Or did I miss something?

**Comment by juhaku** [comment]
Currently there is no support for `repr` but it could be investigated whether the support for this could be added and how much effort it would take. This is pretty nice idea though. I assume that the support should not be too difficult but cannot make any statements nor promises beforehand.

**Comment by juhaku** [comment]
I'll close this now since the PR has been merged to master.
