### ISSUE TITLE
Usage of type alias

### ISSUE THREAD

**Issue by BastienVigneron** [juhaku/utoipa#277]
Hello, I try to define a struct that refer to a type alias :

```rust
pub(super) type Did = String;

#[derive(Serialize, Deserialize, Debug, Clone, ToSchema, PartialEq, Eq)]
pub(super) struct TrustedDIDs {
    /// The list of trusted DIDs
    pub trusted_dids: Option<Vec<Did>>,
}
```

But I get an error on swagger-ui : 

```
Resolver error at paths./did.get.responses.200.content.application/json.schema.items.properties.trusted_dids.items.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/Did does not exist in document
```

As type alias don't support Macro, is there a way to declare them in a way utopia-swagger-ui can use it ?

**Comment by juhaku** [comment]
You could try to use the `value_type` attribute in `ToSchema` derive trait. For example above case you could write it like this with `value_type`:
```rust
#[schema(value_type = Option<Vec<String>>)]
pub trusted_dids: Option<Vec<Did>>
```
This would make the `Did` alias behave like a `String` in OpenAPI doc.

**Comment by BastienVigneron** [comment]
Work great thank you !

Is this kind of macro annotation available somewhere in the documentation ?

**Comment by juhaku** [comment]
Yes it is check it here: https://docs.rs/utoipa/2.0.1/utoipa/derive.ToSchema.html :slightly_smiling_face:

**Comment by BastienVigneron** [comment]
Many thanks !
I close the ticket.
