### ISSUE TITLE
Compatibility with latest version of actix-web v4.2.1

### ISSUE THREAD

**Issue by PullStackPigDev** [juhaku/utoipa#288]
When updating actix-web from 4.1 to 4.2.1, the following error gets produced:
```
error: failed to select a version for `zstd`.
    ... required by package `actix-http v3.2.2`
    ... which satisfies dependency `actix-http = "^3.2.2"` of package `actix-web v4.2.1`
    ... which satisfies dependency `actix-web = "^4.2.1"` of package `raspberry v0.1.0 (/Users/user/Desktop/Programming/flettex-chat/apps/raspberry)`
versions that meet the requirements `^0.11` are: 0.11.2+zstd.1.5.2, 0.11.1+zstd.1.5.2, 0.11.0+zstd.1.5.2

the package `zstd` links to the native library `zstd`, but it conflicts with a previous package which links to `zstd` as well:
package `zstd-safe v4.1.4+zstd.1.5.2`
    ... which satisfies dependency `zstd-safe = "=4.1.4"` of package `zstd v0.10.0+zstd.1.5.2`
    ... which satisfies dependency `zstd = "^0.10.0"` of package `zip v0.6.0`
    ... which satisfies dependency `zip = "^0.6"` of package `utoipa-swagger-ui v1.0.0`
    ... which satisfies dependency `utoipa-swagger-ui = "^1"` of package `raspberry v0.1.0 (/Users/user/Desktop/Programming/flettex-chat/apps/raspberry)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='zstd' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `zstd` which could resolve this conflict
```
This is because a dependency of the crate `utoipa-swagger-ui = "^1"` -> `zip = "^0.6"` is using a different version of zstd
Current ways to get around this include downgrading zstd to 0.5, or simply using `zip = { git = "https://github.com/zip-rs/zip" }` Since they fixed it in their Git but not release yet.

**Comment by juhaku** [comment]
Seems like you are using quite old `utoipa-swagger-ui` version `1`? There is already version `2` release train available and it is recommended to migrate. For example I tested with the `todo-actix` example and upgraded `actix-web` to `4.2` then running it worked just fine without issues.

**Comment by PullStackPigDev** [comment]
Oh, I did not realize that utoipa-swagger-ui has a version 2. I will see if it is compatible after updating the version

**Comment by juhaku** [comment]
> Oh, I did not realize that utoipa-swagger-ui has a version 2. I will see if it is compatible after updating the version

@PullStackPigDev  is it solved, by upgrading the version?

**Comment by PullStackPigDev** [comment]
Hello, I have just upgraded utoipa and utoipa-swagger-ui to v2 and everything is now working flawlessly.
Thank you!
