### ISSUE TITLE
Add support to dyn keyword

### ISSUE THREAD

**Issue by joelforte** [juhaku/utoipa#292]
Hi, I'm facing the following issue, the tool for the following function generates documentation correctly:

```
#[utoipa::path(
    post,
    path = "/api/v1/dummy-context/{dummy_id}",
    responses(
        (status = 201, description = "Dummy was successfully created", body = DummyContextResponse),
        (status = 400, description = "The request is not valid"),
    )
)]
pub async fn post_dummy_message(some_dummy_param: web::Data<SomeDummyType>) {
    // Some code here
}
```
But when i change the params and add one with that have the dyn keyword, for example the following(I just change the params, the rest is exactly the same):

```
#[utoipa::path(
    post,
    path = "/api/v1/dummy-context/{dummy_id}",
    responses(
        (status = 201, description = "Dummy was successfully created", body = DummyContextResponse),
        (status = 400, description = "The request is not valid"),
    )
)]
pub async fn post_dummy_message(some_dummy_param: web::Data<dyn SomeDummyTypeTrait>) {
    // Some code here
}
```

My code related to utopia breaks with the following message:
`unexpected type in component part get type path, expected one of: Path, Reference, Group`

I cant avoid adding the keyword because I need traits on the function.

Is this behavior expected or can be considered as a bug? I'm missing something to make this work? Thank you!

Versions:
utoipa = { version = "^2.1.0", features = ["actix_extras", "uuid", "chrono"] }
utoipa-swagger-ui = { version = "2.0.1", features = ["actix-web"] }
actix-web = "4.2.1"
rustc 1.62.0 (a8314ef7d 2022-06-27)

**Comment by juhaku** [comment]
Hi, right. This could be considered a bug, funny that no-one hasn't reported that before or they are not using dyn that much. I'll take a look at this when I get time and hopefully resolve this to the next release.

**Comment by joelforte** [comment]
Thank you, let me know if there is something i can help with (if you have an idea of how to solve it i will try)
