### ISSUE TITLE
Define default response

### ISSUE THREAD

**Issue by jacob-pro** [juhaku/utoipa#297]
Hi :)
thanks for this great crate.

I'm wondering if it is possible to define a default response?

Default responses are documented here: https://swagger.io/docs/specification/describing-responses/, for example in an API spec:

```yaml
      responses:
        '200':
          description: Success
        'default':
          "$ref": "#/components/responses/ApiError"
```

I was expecting to be able to use something like this, but it doesn't seem to work:

```
    responses(
        (status = 200, description = "Success"),
        (status = "default", description = "Error")
    ),
```

**Comment by juhaku** [comment]
Hi, anytime :slightly_smiling_face: 

> I'm wondering if it is possible to define a default response?

That is actually unimplemented feature. One way to do it would  be to allow not to define the status what would then make it the "default" response. Or add another attribute `default` which can be provided in place of the status when the default response is defined. 

This is definitely something that could be added in the future. And should not be too hard to make. PR:s are also welome :slightly_smiling_face:

**Comment by jacob-pro** [comment]
Hi @juhaku ,

Yeah I'm happy to look at writing a PR...

I'm wondering though if it would make more sense for status to just be a string?

The spec also allows for range matches as well, such as "4XX" and "5XX"

So maybe the simplest would be to allow doing?

```
    responses(
        (status = "200", description = "Success"),
        (status = "4XX", description = "Bad Request"),
        (status = "5XX", description = "Server Error"),
        (status = "default", description = "everything else")
    ),
```

**Comment by juhaku** [comment]
> I'm wondering though if it would make more sense for status to just be a string?

To be honest, originally it was just a `String` but then it was changed to a number  be more efficient via not using that much space. So it was turned to a int internally. :smile: But true, it could be a string as you proposed. Also it could be an enum internally which would provide some validation over allowed types e.g. 
```rust
enum StatusCode {
  Number(i32),
  Default,
  1XX,
  2XX,
  // .. etc
}
```
And this enum above could be parsed from the strings represented in your comment.

This change should be fairly even with tests.

**Comment by jacob-pro** [comment]
Looks like it is already a string internally?
https://github.com/juhaku/utoipa/blob/84f969e7f14b819d5f54f1fd4914ac39e6c0d21c/utoipa/src/openapi/response.rs#L25-L29

**Comment by juhaku** [comment]
Oh yeah, it is a `String` in the Rust openapi type since the actual API is expecting a string value as a status code. But it is an i32 where the value is parsed at `utoipa-gen` https://github.com/juhaku/utoipa/blob/84f969e7f14b819d5f54f1fd4914ac39e6c0d21c/utoipa-gen/src/path/response.rs#L40

`utoipa` crate is the Rust types of OpenAPI schema and the parsing and code generation is in `utoipa-gen` what provides the macros.
