### ISSUE TITLE
When inlining a request support setting title

### ISSUE THREAD

**Issue by jacob-pro** [juhaku/utoipa#306]
I am trying to generate a spec that looks like:

```yaml
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: SubmitPasswordResetRequest
              required:
                - token
                - new_password
              properties:
                token:
                  type: string
                new_password:
                  type: string
```

I can get the schema to generate inline using:

```rust
#[utoipa::path(
    request_body = inline(SubmitPasswordResetRequest),
)]
```

But I can't seem to find any way to set the title field?

The title is important because it is used by most openapi client generators to generate the client models

**Comment by juhaku** [comment]
Currently the `title` field support is incomplete. There is a support of it, but it can now only be added over enum variants. I am aware of this and there is an ongoing work to improve this functionality.

**Comment by juhaku** [comment]
There is now support for setting `title` in object level as well by this #354.
