### ISSUE TITLE
is there any way to custom a base_path?

### ISSUE THREAD

**Issue by imokoi** [juhaku/utoipa#310]
```
#[utoipa::path(
    get,
    path = "/ping",
    tag = "ping",
    responses(
        (status = 200, description = "Ping the service", body = [String])
    )
)]
async fn ping() -> &'static str {
    "pong"
}
```
Sorry to make an issue.
for example, I have a ping function; when I run the server locally, I want to use `/ping` to request the server in swagger. 
However, when I run the server in k8s, I want to request the ping function with the prefix `/test/ping` in the swagger apis.  any idea to solve this?

**Comment by juhaku** [comment]
Hi,

For the `utoipa::path` itself a `context_path` attribute can be added to prefix the path. See more here: https://docs.rs/utoipa/latest/utoipa/attr.path.html#path-attributes. However the path will be always prefixed with the context path and there is no way to have conditional context path. E.g one for running locally and another running in k8s.

Another way to solve this is to add a custom `Server` to your OpenAPI docs. You could add one for local host and one for k8s. See more here: https://docs.rs/utoipa/latest/utoipa/openapi/server/index.html.

Hope these will help you. Cheers

**Comment by imokoi** [comment]
> Hi,
> 
> For the `utoipa::path` itself a `context_path` attribute can be added to prefix the path. See more here: https://docs.rs/utoipa/latest/utoipa/attr.path.html#path-attributes. However the path will be always prefixed with the context path and there is no way to have conditional context path. E.g one for running locally and another running in k8s.
> 
> Another way to solve this is to add a custom `Server` to your OpenAPI docs. You could add one for local host and one for k8s. See more here: https://docs.rs/utoipa/latest/utoipa/openapi/server/index.html.
> 
> Hope these will help you. Cheers

it works. thanks so much! 😸
