### ISSUE TITLE
unexpected syn::Pat, expected syn::Pat::Ident, in get_fn_args, cannot get fn argument name

### ISSUE THREAD

**Issue by imokoi** [juhaku/utoipa#311]
```
#[utoipa::path(
    get,
    path = "/v1/neco-staked-info/{network}/{public_address}",
    tag = "NECO",
    params(
        ("network" = u8, Path, description = "network for blockchain"),
        ("public_address" = String, Path, description = "public address for user"),
    ),
    responses(
        (status = 200, description = "Get NECO staked info successfully", body = NECOStakedInfoResponse),
        (status = 400, description = "Bad request", body = ErrorResponse),
    )
)]
pub async fn get_neco_staked_info(
    Path((network, public_address)): Path<(u8, String)>,
) -> Json<Response<NECOStakedInfo>> {
....
}
```
<img width="877" alt="image" src="https://user-images.githubusercontent.com/16015549/193975320-830843ef-c09f-4098-a763-39e296bf1f6a.png">

if I use a tuple as a param, there is an error ``unexpected syn::Pat, expected syn::Pat::Ident, in get_fn_args, cannot get fn argument name``. 
so is there a way to use 2 parameters when I use Tuple as my param in the route function?

**Comment by imokoi** [comment]
I know another way to slove this problem. 
```
#[utoipa::path(
    get,
    path = "/v1/neco-staked-info/{network}/{public_address}",
    tag = "NECO",
    params(
        GetStakedInfoRequest 
    ),
    responses(
        (status = 200, description = "Get NECO staked info successfully", body = NECOStakedInfoResponse),
        (status = 400, description = "Bad request", body = ErrorResponse),
    )
)]
pub async fn get_neco_staked_info(
    Path(param): Path<GetStakedInfoRequest>,
) -> Json<Response<NECOStakedInfo>> {
...
}
```

define a struct that includes request parameters. and pass the struct name to params. it works well.
but just wondering. if I can use Tuple?

**Comment by juhaku** [comment]
> define a struct that includes request parameters. and pass the struct name to params as Path Params. it works well.
but just wondering. how to use a Tuple?

Yeah, I'd say that it should be possible to use tuple, but I cannot say why it is not working there. I believe that worked in actix-web. I need to troubleshoot this when I get time to.

**Comment by juhaku** [comment]
@imokoi Now I remember, did some digging and it used to be implemented for actix-web before, but later on I removed the code since changes in actix-web itself. Then it has never be implemented for other frameworks. Currently in axum the only way to define the parameter is with the new struct. Either with unnamed field struct or regular struct with named fields.

I'll try to see whether support for this can be added.
