### ISSUE TITLE
Serializing and then Deserializing is incomplete

### ISSUE THREAD

**Issue by ju6ge** [juhaku/utoipa#312]
Hey,

I have stumbled upon a problem. The yetserialization of "Schema" types fails. To showcase what I mean I have written the following test:

```rust
#![cfg(all(feature = "yaml", feature = "json"))]

use std::assert_eq;
use serde_json;
use serde_yaml;

use utoipa::openapi::{*, Schema, ObjectBuilder};
use utoipa::openapi::schema::RefOr;

#[test]
pub fn serialize_deserialize_schema() {

	let ref_or_schema = RefOr::T(
		Schema::Object(
			ObjectBuilder::new()
				.property("test", RefOr::T(Schema::Array(
				ArrayBuilder::new()
					.items(RefOr::T(
						Schema::Object(
							ObjectBuilder::new()
								.property("element", RefOr::Ref(Ref::new("#/test")))
								.build()
						)
					))
					.build()
			)))

				.build()
		));

	let yaml_str = serde_yaml::to_string(&ref_or_schema).expect("");
	println!("----------------------------");
	println!("{yaml_str}");

	let deserialized: RefOr<Schema> = serde_yaml::from_str(&yaml_str).expect("");

	let yaml_de_str = serde_yaml::to_string(&deserialized).expect("");
	println!("----------------------------");
	println!("{yaml_de_str}");

	assert_eq!(yaml_str, yaml_de_str);
}
```

This produces an assertion failed with the following std output:
`cargo test --features yaml --features json --test serde_schema -- --nocapture`

```
    Finished test [unoptimized + debuginfo] target(s) in 0.15s
     Running tests/serde_schema.rs (target/debug/deps/serde_schema-8fd331298e547711)

running 1 test
----------------------------
type: object
properties:
  test:
    type: array
    items:
      type: object
      properties:
        element:
          $ref: '#/test'

----------------------------
type: object
properties:
  test:
    type: array

thread 'serialize_deserialize_schema' panicked at 'assertion failed: `(left == right)`
  left: `"type: object\nproperties:\n  test:\n    type: array\n    items:\n      type: object\n      properties:\n        element:\n          $ref: '#/test'\n"`,
 right: `"type: object\nproperties:\n  test:\n    type: array\n"`', utoipa-gen/tests/serde_schema.rs:41:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test serialize_deserialize_schema ... FAILED

failures:

failures:
    serialize_deserialize_schema

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

It seams that nested array object structures do not get correctly de-serialized. Any Ideas how to handle this?

Kind regards,
ju6ge

**Comment by juhaku** [comment]
Oh snap.. again, there was already a similar problem and I fixed one of them earlier. The issue lies in serde itself. When it tries to deserialize a json it will mistakenly assume the underlying object is something else what it is not. Then it fails to recognize the correct type and successfully deserializes something else down in the json tree. This is kind of a pain to pin point the problem, and cure is always more or less hit or miss type of a thing. Magic lies in narrowing down the object tree to try to find which serde deserialize statement does fail and then trying to alter the openapi json schema structure so that the issue could be avoided still keeping consistency with the actual OpenAPI shcema structure.

**Comment by ju6ge** [comment]
Yea I guessed as much … Serde is awesome, but it could be a lot more transparent/debuggable :roll_eyes: 

Anyway maybe I'll get around to tinkering with it, I kind of need it to work.

**Comment by ju6ge** [comment]
I think there is a clash with the `schema_type` attribute. After some tinkering I get the following situation:

I updated the Schema enum serde attributes to enable tagged serialization.
```rust
#[non_exhaustive]
#[derive(Serialize, Deserialize, Clone)]
#[cfg_attr(feature = "debug", derive(Debug))]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum Schema {
    /// Defines object schema. Object is either `object` hodling **properties** which are other [`Schema`]s
    /// or can be a field within the [`Object`].
    Object(Object),
    /// Defines array schema from another schema. Typically used with
    /// [`Schema::Object`]. Slice and Vec types are translated to [`Schema::Array`] types.
    Array(Array),
    /// Creates a _OneOf_ type [composite Object][composite] schema. This schema
    /// is used to map multiple schemas together where API endpoint could return any of them.
    /// [`Schema::OneOf`] is created form complex enum where enum holds other than unit types.
    ///
    /// [composite]: https://spec.openapis.org/oas/latest.html#components-object
    OneOf(OneOf),

    /// Creates a _AnyOf_ type [composite Object][composite] shcema.
    ///
    /// [composite]: https://spec.openapis.org/oas/latest.html#components-object
    AllOf(AllOf),
}

```
This results in the following serialized output.
```yaml
type: object
type: object
properties:
  test:
    type: array
    type: array
    items:
      type: object
      type: object
      properties:
        element:
          $ref: '#/test'
```
The type attribute is now shown twice. This leads me to conclude that serde is using the type field to deserialize the `schema_type` field (common to Object, Array). But this results in serde always deserializing an object and never an array. Since schema_type can take the value array.

Maybe this can be circumvented by using a custom deserializer for this type of data structure. Or the handling of the `schema_type` field needs to be changed… 

Any suggestions on how to proceed?

**Comment by ju6ge** [comment]
So with #323 I got it working, I think details of the suggested fixed should be discussed in the PR Thread.

**Comment by juhaku** [comment]
Haven't had a time to think about this, but perhaps a custom serialization is need. 

> The type attribute is now shown twice. This leads me to conclude that serde is using the type field to deserialize the schema_type field (common to Object, Array).

That is true, though for `AllOf` and `OneOf` types this is not the case since they do not have a type field. I will also try to play around with this to see if there is something that can be done.
