### ISSUE TITLE
How to add 2 responses for a status code

### ISSUE THREAD

**Issue by deknowny** [juhaku/utoipa#317]
I have a status code 404 for my RESTful API, but there are 2 cases 404 response can be reproduced so how to add 2 response models to `path` macro (for axum)?

**Comment by juhaku** [comment]
Responses is a map distinct by status code thus only way to add multiple responses per status code is to wrap them in an enum like so.
```rust
#[derive(ToSchema)]
enum MyNotFoundError {
   Response1(Response1Body),
   Response2(FooBar),
}
```
This is creates a `OneOf` [composition object](https://swagger.io/specification/#reference-object). In the axum [example](https://github.com/juhaku/utoipa/blob/master/examples/todo-axum/src/main.rs#L95..L105) uses only one error response per all endpoints but of course you can have multiple. The example should get you started. :)

**Comment by deknowny** [comment]
Thank you for the reply! 

Actually, it's not what I want. Okay, it shows two kind of replies in schema detail
![Снимок экрана 2022-10-11 в 21 29 57](https://user-images.githubusercontent.com/57015939/195171447-71495db6-6b74-41e7-82c0-5da40f77df19.png)

But I want to see this like "unrolled", i.e. there are should be 2 examples
![Снимок экрана 2022-10-11 в 21 30 11](https://user-images.githubusercontent.com/57015939/195171663-638c07bf-769f-4d29-b0c5-e21d5a5cd710.png)

And I don't want to see "First" and "Second" in schema (tried with `serde(untagged)` but still the same result)

```rust
#[derive(utoipa::ToSchema, serde::Deserialize)]
#[serde(untagged)]
pub enum CreateSellerResponses409 {
    First(SuchTGIDExistsError),
    Second(InvalidTGSignError)
}
```

**Comment by deknowny** [comment]
Something like [https://medium.com/@niteshsinghal85/multiple-request-response-examples-for-swagger-ui-in-asp-net-core-864c0bdc6619](url)
![1_ZL-KWDqgu_TcI3-AvkzHGw](https://user-images.githubusercontent.com/57015939/195172952-63127105-78a7-4582-b13f-fa427d349915.png)
and with different schema

**Comment by deknowny** [comment]
@juhaku looks like multiply examples added via `examples` field, is there support of this? 
![Снимок экрана 2022-10-11 в 21 47 04](https://user-images.githubusercontent.com/57015939/195174590-8dd1550f-a27b-4ab2-8e7b-3ba7d23beaad.png)

**Comment by juhaku** [comment]
I just took a look as well and currently this is not supported. The `examples` field is not implemented at the moment. Support could be added but it needs changes to both utoipa and utoipa-gen crates. Also some design effort need to be given to get it intuitive to use. I'll add this to the kanban board for future development since I am unable to now to focus on this.
