### ISSUE TITLE
is there any way to change the example response to camelCase

### ISSUE THREAD

**Issue by imokoi** [juhaku/utoipa#318]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/16015549/194988868-54d43ac4-2ff0-42eb-a7bb-d0b537f71377.png">

hello, the style of my JSON key is camelCase; I used serde to rename_all("camelCase"). How can I change the example response in the swagger file to cameCase too?

**Comment by juhaku** [comment]
In short there is no separate renaming logic for example. If you have defined example with `json!({"foo_key": "bar"})` you  need to manually make the fields camel case as `json!(({"fooKey": "bar"})`.

Alternatively I guess if you have defined example with struct or enum `json!(MyExample{ fooKey: "bar" })` and the `MyExample` would have derive `serde::Serialize` and `#[serde(rename_all = "camelCase")]` it should rename the keys to camel case. But I am not sure whether it really does it. 

Also by default I believe the example should be rendered according to the schema objects in the OpenAPI doc. So if OpenAPI doc has a type with `camelCase` fields then the example should most likely follow the style. 

If non of the cases above applies to you then most likely there is something that hasn't been taken in to account yet in the library so far.

**Comment by juhaku** [comment]
Closing this due inactivity.
