### ISSUE TITLE
Untagged enums don't seem to work

### ISSUE THREAD

**Issue by Alfred-Mountfield** [juhaku/utoipa#320]
I've tried to create an enum with serde's `untagged` attribute:
```rust
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, ToSchema)]
#[serde(rename_all = "camelCase", untagged)]
pub enum Foo {
    Bar(String),
    Baz(u64),
    #[schema(value_type = String)]
    Qux(Bar),
}
```

then the generation looks like:
```typescript
/**
 * @type Foo
 * @export
 */
export type Foo =
  | FooOneOf
  | FooOneOf1
  | FooOneOf2;

/**
 *
 * @export
 * @interface FooOneOf
 */
export interface FooOneOf {
  /**
   *
   * @type {string}
   * @memberof FooOneOf
   */
  bar?: string;
}
/**
 *
 * @export
 * @interface FooOneOf1
 */
export interface FooOneOf1 {
  /**
   *
   * @type {number}
   * @memberof FooOneOf1
   */
  baz?: number;
}
/**
 *
 * @export
 * @interface FooOneOf2
 */
export interface FooOneOf2 {
  /**
   *
   * @type {string}
   * @memberof FooOneOf2
   */
  quz?: string;
}
```

When I'd expect either:
```typescript
export type Foo =
  | string
  | number
  | string;
```

or
```typescript
export type Foo =
  | bar
  | baz
  | quz;

export type bar = string;
export type baz = number;
export type quz = string;
```

**Comment by juhaku** [comment]
Currently the `untagged` is not supported serde attribute thus does not generate expected code. Support for this probably could be added in future but needs some planning and desinging. At the moment I am not too pleased with the current enum implementation which also needs some refactoring. It seems to be unnecessarily complicated. 

Currently supported serde attributes are listed here for the schema: file:///home/juha/development/git/utoipa/target/doc/utoipa/derive.ToSchema.html#partial-serde-attributes-support
