### ISSUE TITLE
proc-macro derive panicked

### ISSUE THREAD

**Issue by azzamsa** [juhaku/utoipa#322]
Hi.

Sometimes I get `proc-macro derive panicked` in CI machine, but can't reproduce locally.

```rust
  Compiling async-graphql v4.0.15
   Compiling utoipa-swagger-ui v2.0.1
error: proc-macro derive panicked
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/utoipa-swagger-ui-2.0.1/src/lib.rs:122:10
    |
122 | #[derive(RustEmbed)]
    |          ^^^^^^^^^
    |
    = help: message: #[derive(RustEmbed)] folder '/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/utoipa-swagger-ui-2.0.1/../target/swagger-ui-4.14.0/dist/' does not exist. cwd: '/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/utoipa-swagger-ui-2.0.1'

error[E0599]: no function or associated item named `get` found for struct `SwaggerUiDist` in the current scope
    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/utoipa-swagger-ui-2.0.1/src/lib.rs:1201:40
     |
124  | struct SwaggerUiDist;
     | -------------------- function or associated item `get` not found for this struct
...
1201 |     if let Some(file) = SwaggerUiDist::get(file_path) {
     |                                        ^^^ function or associated item not found in `SwaggerUiDist`
     |
     = help: items from traits can only be used if the trait is implemented and in scope
     = note: the following traits define an item `get`, perhaps you need to implement one of them:
             candidate #1: `SliceIndex`
             candidate #2: `RustEmbed`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `utoipa-swagger-ui` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: Recipe `test` failed on line 57 with exit code 101
Error: Process completed with exit code 101.
```

- https://github.com/azzamsa/tin/actions/runs/3259870558/jobs/5353014956#step:7:59

Thanks a lot for utoipa!

**Comment by juhaku** [comment]
Seems like it cannot run the utoipa-swagger-ui's `build.rs` file. Thus leaves the dependency in some weird incomplete state. The key might lie here: `/utoipa-swagger-ui-2.0.1/../target/swagger-ui-4.14.0/dist/`. See there is the `../target` It expects to find `../target` folder which is used for build cache by default by Rust. The question then arises where is the build cache located? When you build the app what folder it will place the build artifacts if not target? You may try to define `CARGO_BUILD_TARGET_DIR` environment variable point to the target folder. The current logic is defined here: https://github.com/juhaku/utoipa/blob/master/utoipa-swagger-ui/build.rs#L21..L31 It is ment to work with local builds and in docs.rs builder runner which uses custom target dirs. 

Hope this gives you the push need to get a step further.

> Thanks a lot for utoipa!

:slightly_smiling_face:  it's my pleasure to build this thing. Just if I had time to :laughing:

**Comment by azzamsa** [comment]
Disabling the cache `` seems to works. https://github.com/azzamsa/tin/actions/runs/3269333758/jobs/5376720667#step:5:49

I will reopen if the issue arises again.

I hope #276 will end happily. Thank you for creating utoipa!

**Comment by ChristianBeilschmidt** [comment]
It also fails a lot in our CI that uses a cache. Is there a known way to get this to work?

**Comment by azzamsa** [comment]
@ChristianBeilschmidt do you find any solution but disabling the cache?

**Comment by juhaku** [comment]
@ChristianBeilschmidt @azzamsa 

> @ChristianBeilschmidt do you find any solution but disabling the cache?

I'll make a small mod to the `build.rs` to seprate branch hopefully today, you can then try the branch out and see whether it helps to the issue. I'll update on here when there is the branch available.

**Comment by juhaku** [comment]
> I hope #276 will end happily. Thank you for creating utoipa!

Yeah, all ends well or as well the can end taking in account the circumstances. :slightly_smiling_face: Thank you for consideration.

**Comment by juhaku** [comment]
@azzamsa @ChristianBeilschmidt here's the branch what will try to recognize the `TARGET_DIR` env var. https://github.com/juhaku/utoipa/tree/test-swagger-build-attr

**Comment by azzamsa** [comment]
Looks like it works https://github.com/azzamsa/repotablo/actions/runs/3424143190/jobs/5703487017#step:6:313

I will use this branch for several days to see how it goes.

**Comment by juhaku** [comment]
There is a new release of `utoipa-swagger-ui` which should fix this issue with using the recommended `OUT_DIR` variable in build.

**Comment by azzamsa** [comment]
Okay, I will wait a new release that include a change to axum v6.0

**Comment by juhaku** [comment]
New utoipa-swagger-ui has been released containing the latest axum. https://github.com/juhaku/utoipa/discussions/371

**Comment by azzamsa** [comment]
Tried couple times. It works!

Huge thanks!
