### ISSUE TITLE
ToSchema #[schema(example = json!(...))] for HashMap doesn't work as expected

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#327]
For a simple `HashMap<String, String>` it places the `example` inside the `additionalProperties` field (which is unexpected I think?), and for a hashmap including a component as the value, it doesn't produce any example in the derived schema.

See the replication in the draft PR #326

**Comment by juhaku** [comment]
Yes that is definitely unexpected behavior. :smile:  The `additionalProperties` are also currently a bit incomplete in it's implementation meaning that if one was to use some client generator from the generated schema having the additionalProperties set it would not generate correct types. Also the enum's are unnecessary complex at the moment and is heave need of refactoring. Perhaps this could be also addressed at the same time frame.
