### ISSUE TITLE
How to get yaml and json output

### ISSUE THREAD

**Issue by npajkovsky** [juhaku/utoipa#329]
Hey,

I have a hard time understanding how I can get OpenAPI in yaml. I have used your actix web example, and I have added
YAML support in Cargo.toml.

```
utoipa = { path = "../../utoipa", features = ["actix_extras", "yaml"] }
utoipa-swagger-ui = { path = "../../utoipa-swagger-ui", features = ["actix-web"] }
```

Here is actix HttpSever.
```
    HttpServer::new(move || {
        App::new()
            ...
            .service(
                SwaggerUi::new("/swagger-ui/{_:.*}")
                    .url("/api-doc/openapi.json", openapi.clone())
                    .url("/api-doc/openapi.yaml", ...?),
            )
    })
    ...
```

The `SwaggerUi::url` takes as 2nd arg [OpenApi](https://docs.rs/utoipa/2.0.1/x86_64-unknown-linux-gnu/utoipa/openapi/struct.OpenApi.html) without any options to say what output should it be.

So, how can I get yaml output?

**Comment by juhaku** [comment]
For swagger ui point of view it does not matter whether JSON or YAML is provided as an input to it. Thus only JSON is considered enough.  If you want to expose _yaml_ version of an openapi you need to create a separate endpoint for that. E.g. something like seen below, not necessarily working example but should give an idea of how to get forward.

```rust
#[get("/api/v1/openapi.yaml")]
async fn get_openapi_yaml(openapi: Data<utoipa::openapi::OpenApi>) -> Result<HttpResponse, Error> {
    let yaml = openapi.to_yaml()?;

    HttpResponse::Ok()
        .body(yaml)
}

```

**Comment by npajkovsky** [comment]
Thanks.
