### ISSUE TITLE
ToSchema breaks on Vec<(string, String)>

### ISSUE THREAD

**Issue by 1lutz** [juhaku/utoipa#330]
I got a struct which has a field of type `Vec<(String, String)>` like this:

```Rust
#[derive(ToSchema)]
struct Demo {
        options: Vec<(String, String)>
}
```

The compiler throws a confusing error message that it needs an argument:

```
error[E0061]: this function takes 1 argument but 0 arguments were supplied
    --> src/main.rs:3:10
     |
3    | #[derive(ToSchema)]
     |          ^^^^^^^^ an argument is missing
     |
note: associated function defined here
    --> /home/lutzg/.cargo/registry/src/github.com-1ecc6299db9ec823/utoipa-2.2.0/src/openapi/schema.rs:1040:12
     |
1040 |     pub fn items<I: Into<RefOr<Schema>>>(mut self, component: I) -> Self {
     |            ^^^^^
     = note: this error originates in the derive macro `ToSchema` (in Nightly builds, run with -Z macro-backtrace for more info)
help: provide the argument
     |
3    | #[derive(ToSchema(/* value */))]
     |                  +++++++++++++
```

I expect the same schema to be derived like that of a `HashMap<String, String>`.

**Comment by juhaku** [comment]
Yeah. I am afraid that the tuple types are not fully supported at the moment thus yielding you this kind of cryptic error message. 

Actually when supported the output schema would be a array within array where inner array is only 2 items wide string array. So the representation would be something same as seen below according to: https://serde.rs/json.html
```json
[
  ["string", "string"],
]
```

**Comment by juhaku** [comment]
#390 can be used as a workaround to manually implement the schema for the fields. It works similarly to the serde's `serialize_with` as it provides a function called `schema_with` what expects a function reference that implements the schema for underlying field.

**Comment by juhaku** [comment]
Native support for tuples is coming here: #541
