### ISSUE TITLE
Derive ToSchema on Unit Structs

### ISSUE THREAD

**Issue by 1lutz** [juhaku/utoipa#332]
serde_json serializes a unit struct as null.

```rust
#[derive(Serialize)]
struct Unit;
println!("{}", serde_json::to_string(&Unit).unwrap());
// prints null
```

Currently, if you add `#[derive(ToSchema)]` the compiler throws an errror:

```
error: unexpected Field::Unit expected struct with Field::Named or Field::Unnamed
 --> services/src/bin/playground.rs:6:8
  |
6 | struct Unit;
  |        ^^^^
```

I think it would be more reasonable if utoipa generates an impl like the following:

```rust
impl ToSchema for Unit {
    fn schema() -> Schema {
        ObjectBuilder::new()
            .default(Some(serde_json::Value::Null))
            .example(Some(serde_json::Value::Null))
            .into()
    }
}
```

That serializes to:

```json
{"type":"object","default":null,"example":null}
```

**Comment by juhaku** [comment]
This is designed behavior and the `Unit` structs are not supported since they do not have a proper representation in OpenAPI schema. This could be experiemented to see how it would play out and if it will work well it could be added to the `utoipa-gen`. :slightly_smiling_face:
