### ISSUE TITLE
Provide example for `body` in `responses`

### ISSUE THREAD

**Issue by BBaoVanC** [juhaku/utoipa#348]
How can I set an example for the response body? Right now it's just saying "string" for the example.

**Comment by juhaku** [comment]
Here is actix-todo example for setting example on response: https://github.com/juhaku/utoipa/blob/master/examples/todo-actix/src/todo.rs#L94...L102

Hope this helps.

**Comment by jayvdb** [comment]
There are quite a few other examples that can be found using "body =" queries, such as https://github.com/search?q=repo%3Ajuhaku%2Futoipa%20%22body%20%3D%22&type=code

I think this issue can be closed.

**Comment by juhaku** [comment]
I agree, haven't seen any activity for a while and the above comments should point to right direction at least.
