### ISSUE TITLE
Multiline descriptions on struct fields

### ISSUE THREAD

**Issue by michael-mark** [juhaku/utoipa#358]
I noticed that the descriptions of schemas are cut off and do not use more than the first comment line. For example, if you add additional information to the Todo item in the todo-actix example:

```rust
/// Task to do.
#[derive(Serialize, Deserialize, ToSchema, Clone, Debug)]
pub(super) struct Todo {
    /// Unique id for the todo item.
    /// 
    /// This is another line of text.
    #[schema(example = 1)]
    id: i32,
    /// Description of the taks to do.
    #[schema(example = "Remember to buy groceries")]
    value: String,
    /// Mark is the task done or not
    checked: bool,
}
```
Then the openapi output will look like this:
![image](https://user-images.githubusercontent.com/64803897/203134723-b0375a57-a229-49d2-8512-c1fc1379c010.png)

Note that the "This is another line of text." part of the comment is not present.

Digging through the `utoipa-gen` code a bit, this seems to happen because only `.first()` is called in the following places:
- [impl ToTokens for NamedStructSchema<'_>](https://github.com/juhaku/utoipa/blob/9dd9023963cc68a0eb66099a02d60ea9ab45b09c/utoipa-gen/src/component/schema.rs#L311)
- [impl ToTokens for UnnamedStructSchema<'_>](https://github.com/juhaku/utoipa/blob/9dd9023963cc68a0eb66099a02d60ea9ab45b09c/utoipa-gen/src/component/schema.rs#L435)
- [impl ToTokens for EnumSchemaType<'_>](https://github.com/juhaku/utoipa/blob/9dd9023963cc68a0eb66099a02d60ea9ab45b09c/utoipa-gen/src/component/schema.rs#L545)
- [impl ToTokens for SchemaProperty<'_>](https://github.com/juhaku/utoipa/blob/9dd9023963cc68a0eb66099a02d60ea9ab45b09c/utoipa-gen/src/component/schema.rs#L1067)
- [impl ToTokens for SchemaProperty<'_>](https://github.com/juhaku/utoipa/blob/9dd9023963cc68a0eb66099a02d60ea9ab45b09c/utoipa-gen/src/component/schema.rs#L1146)

Is this an intentional decision to only use the first line of the comment? If not, then I think this could be fixed by just join the strings on the newline character to preserve all comment lines. Then the output would look something like the following:
![image](https://user-images.githubusercontent.com/64803897/203136320-e323c58d-9a6e-46e9-bac6-e2644e719d42.png)

I believe the same thing happens for the `IntoParams` derive macro as well.

**Comment by juhaku** [comment]
Yes this was originally the silent decision, but since the field supports multiline comments it sure can be changed so that it would add the whole comment as a description.

**Comment by juhaku** [comment]
> I believe the same thing happens for the IntoParams derive macro as well.

This happens everywhere the description is defined.

**Comment by michael-mark** [comment]
Thank you for the clarification. I believe I have the changes needed to add the ability for multiline descriptions. Would you like me to create a merge request with these changes, or what would be the process for getting these changes in?

**Comment by juhaku** [comment]
You can create a PR as well if you want. But I can also take a look at this at some point in future releases.
