### ISSUE TITLE
Add newline/EOL at the end of generated file

### ISSUE THREAD

**Issue by sondrelg** [juhaku/utoipa#368]
Hi,

First of all, thanks a bunch for creating and maintaining this. We use it with axum, and it's been great so far! 👏 

I noticed that the generated files don't end in a newline, which is incompatible with our linter setup. We have a dedicated [pre-commit hook](https://github.com/pre-commit/pre-commit-hooks) that adds make sure every text file ends with a newline character, and since we generated openapi docs when we run the axum server in development, we're getting this generation/fix linter loop every time we run and commit something.

I just wanted to ask, was it a conscious decision not to do this in the `utoipa` schema generation? If not, would you accept a PR that changed this behaviour?

**Comment by juhaku** [comment]
Hello,

Great that you are enjoying the library :slightly_smiling_face: 

The utoipa does not itself write anything to the file, but that is consious decision of user to write the generated document to a file. Effectively utoipa methods `to_pretty_json()` and `to_yaml()` uses serde behind the scenes to serialize the content thus whatever serde serializes can be written to the file. 

I reckon having utoipa append `\n` (new line) at the end of a string serialized by `to_pretty_json()`, `to_json()` or `to_yaml()` is not good. Reason is that having file end to a new line character is good but that is very opinoned. People can make same argument against having a new line character at the end of the file. 

I would like the library to be as neutral as possible to user preferences. And usually it is not a bad idea to ignore auto generated files from lints.

But of course if there is enough good reasons to have the new line character appended then why not though. :thinking: But perhaps then it should be behind a feature flag that allows users to decide whether they want the new line appended or not. Yet is it bit too much of a hazzle.

**Comment by sondrelg** [comment]
I suppose I can add my own newline when writing to the file - you're absolutely right :clap: Thanks!
