### ISSUE TITLE
How to reference a response body for custom serialized type

### ISSUE THREAD

**Issue by hpsjakob** [juhaku/utoipa#391]
Hi,

I've a custom type for which I defined a custom serde serialization.

```rust
pub struct GetDpResult {
    rows: Vec<(String, JsonWrapperForDpValue)>,
}

impl serde::Serialize for GetDpResult {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {
      //...
   }
}
```

The custom serialization serializes that type to a dictionary.

Now I want to declare this type as a response body. 
````
(status = 200, description = "", body = GetDpResult)
````

In https://github.com/juhaku/utoipa/issues/62 it's sugessted to add `ToSchema` to the type:

```rust
#[derive(ToSchema)]
pub struct GetDpResult {
    rows: Vec<(String, JsonWrapperForDpValue)>,
}
```

However then I get the following error:
```
error[E0061]: this function takes 1 argument but 0 arguments were supplied
    --> src/shared_handlers.rs:37:10
     |
37   | #[derive(ToSchema)]
     |          ^^^^^^^^ an argument is missing
```

I guess this is cause by a missing `Serialize`. However I can't derive `Serialize` since it's implemented explicitly. 

Does someone know kow to fix this?

The only workarround I found was to define a different type that's only used for creating an object response type:

```rust
/// This type is only used by utopia for extracting the type of the response.
#[derive(Serialize, ToSchema)]
pub struct GetDpResultType(Map<String, Value>);
```

**Comment by hpsjakob** [comment]
Wow, thanks for the super quick response.
Your PR looks like a great fix for that issue.

Will it also be possilbe to use the manually defined type directly for the `body`?

```
(status = 200, description = "", body = custom_type)
```

**Comment by hpsjakob** [comment]
So should we then close this issue?

**Comment by juhaku** [comment]
> So should we then close this issue? 

Maybe we can close this issue, as the workaround is there, not released yet though. And this has a reference to the original tuple related issues which indicate that the support for tuple types should be implemented.

**Comment by juhaku** [comment]
Native support for tuples is coming here: #541
