### ISSUE TITLE
Support `oauthInit` instance method for SwaggerUI

### ISSUE THREAD

**Issue by BenJeau** [juhaku/utoipa#417]
Thanks for such a good library, I was wondering if it's possible to add support for the `oauthInit` function for SwaggerUI (https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#instance-methods).

The use case would be to have a default `clientId` set in the UI whenever a user authenticates (so that they don't need to remember the id). I tried setting the `OAUTH_CLIENT_ID` env variable, but it does not seem to reflect in the UI.

Maybe a possible fix would be to simply be able to set that variable? Or maybe add it to the config?

**Comment by juhaku** [comment]
Any time :slightly_smiling_face: 

Actually this is supported already via [oauth config](https://docs.rs/utoipa-swagger-ui/latest/utoipa_swagger_ui/oauth/struct.Config.html). This struct implements oauth properties define here  https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md.

Here you can find examples on how to use those properties in the Swagger UI https://docs.rs/utoipa-swagger-ui/latest/utoipa_swagger_ui/struct.SwaggerUi.html#examples.

**Comment by BenJeau** [comment]
Oh I haven't seen that, thanks for pointing it out! I've just added that to my `SwaggerUI` instance, e.g.:

```rust
SwaggerUi::new("/docs")
    .url("/docs/openapi.json", openapi::ApiDoc::openapi())
    .oauth(oauth::Config::default().client_id(&app_state.config.keycloak_client_id))
```

but I'm getting the following (No layout defined):
<img width="857" src="https://user-images.githubusercontent.com/22248828/209007069-56b3100d-44fc-4e74-a2c3-91c7c128e76b.png">

I've tried setting the config itself to the default, but it is still not working. If you have any pointers, please let me know :)

**Comment by juhaku** [comment]
Oh, snap there actually is a bug in utoipa-swagger-ui that causes this. There is couple of ways to get around this.
either add `.use_base_layout()` to the Swagger UI definition. This changes the layout to a default base layout what is not very nice. Or you can create new config from the `openapi.json` file. This way the config will be created correctly but you need to define the path to the apidoc json twice. 
```rust
  SwaggerUi::new("/swagger-ui/{_:.*}")
      .url("/api-doc/openapi.json", openapi.clone())
      .config(Config::from("/api-doc/openapi.json"))
      .oauth(oauth::Config::default().client_id("this_is_id")),

```

I'll fix this to the next release.

**Comment by juhaku** [comment]
@BenJeau After the PR the config can again be created as you have defined it before by `oauth::Config::default()`

**Comment by BenJeau** [comment]
Thank you so much :) Just curious, do you have an idea when the next release will be, since I also have the problem that this fixed PR https://github.com/juhaku/utoipa/pull/388

**Comment by juhaku** [comment]
I was hoping it to land for the holidays :) What would be better than a christmas gift from utoipa to all its fans and users :sled: :santa: :gift: But let's see. There is still some things to address here before it can be released so maybe it will still take few weeks to get all things done for the release.
