### ISSUE TITLE
`utoipa::path` attribute does not work on functions with some forms of parameters

### ISSUE THREAD

**Issue by jay3332** [juhaku/utoipa#423]
Using `#[utoipa::path(...)]` on a function with some forms of parameters will error, so far I've discovered that the underscore (`_`) parameter and struct destructuring parameters do not work.

Examples:
```rs
/// Get User
///
/// Fetches information about a user by their ID.
#[utoipa::path(...)]
pub async fn get_user(_: Auth, Path(id): Path<u64>) -> RouteResult<User> {
    let user = get_pool()
        .fetch_user_by_id(id)
        .await?
        .ok_or_not_found("user", "user not found")?;

    Ok(Response::ok(user))
}
```
Here, I want to discard the `Auth` parameter, however the parameter being `_` causes `utopia::path` to error:
`unexpected syn::Pat, expected syn::Pat::Ident,in get_fn_args, cannot get fn argument name`

The workaround would be to give the unused parameter a name instead of just `_`, i.e. `_auth` will work fine.

The same error occurs when we try destructuring within the parameter list:
```rs
/// Delete User
///
/// Deletes the user account of the authenticated user. This is irreversible.
#[utoipa::path(...)]
pub async fn delete_user(
    Auth(id, flags): Auth,
    Json(DeleteUserPayload { password }): Json<DeleteUserPayload>,
) -> NoContentResult { ... }
```

The workaround here would be to move the destructuring into the function body:
```rs
pub async fn delete_user(
    Auth(id, flags): Auth,
    Json(payload): Json<DeleteUserPayload>,
) -> NoContentResult {
    let DeleteUserPayload { password } = payload;
    ... 
}
```

**Comment by juhaku** [comment]
@jay3332 Thanks for reporting. Some improvements has already been done for this, but there might be some edge cases not taken in account. I need to check these scenarios out and hopefully fix them to the next release. 

What framework you are using utoipa with? axum?

**Comment by jay3332** [comment]
> What framework you are using utoipa with? axum?

Yes, I'm using Axum

**Comment by juhaku** [comment]
Fix is on the way, and landing in next release.
