### ISSUE TITLE
Generics do not work with lifetime specifiers

### ISSUE THREAD

**Issue by buehler** [juhaku/utoipa#427]
Hey @juhaku 

Thank you for your work on this library. It is astonishing and a great developer experience.
However, I have a use-case where the behavior is a bit shakey.

I have a rocket web api for testing out some scenarios. One scenario would be to return paginated generic responses.

I have the following struct that returns a generic list of data, with a total sice and two optional links to the "next" or "prev" page.

```rust
/// Paginated response for a list of results.
/// Contains optional links to the next and previous page,
/// and the total count of items that are available.
#[derive(Debug, Serialize, ToSchema)]
pub struct Paginated<'r, TResult> {
    pub total: usize,
    pub data: Vec<TResult>,
    pub next: Option<&'r str>,
    pub prev: Option<&'r str>,
}
```

I know referenced the crate via git reference on the master branch to get the new features like "content" in the responses for multiple response types. Then I tried to use the aliases, however, they do not work since I don't have all the structs in one file.

When trying with type aliases like so:

```rust
type Test = Paginated<'static, Test<'static>>;

#[derive(OpenApi)]
// components(schemas(test::models::Test, test::models::Metadata)),
#[openapi(
    paths(test::get_all, test::get_by_id),
    components(schemas(Test))
)]
pub(super) struct ApiDoc;
```
I run into the following error:
```
Could not resolve reference: Could not resolve pointer: /components/schemas/TResult does not exist in document
```

With aliases, the references to the models are not present, in which case the compiler will not run through.

Do you have any advice or solution for this matter?
When using aliases like described (`#[aliases(PaginatedPages = Paginated<Page>)]`) it requires a "," in between. Or when I specify the lifetimes, it complains that the combination is not correct for parsing.

Regards

**Comment by buehler** [comment]
Can I do something to help with this matter? This would drastically improve the usefulness of this crate :-)

We use the lifetime specifiers to prevent copy stuff and have the pagination struct to help with DRY.

**Comment by buehler** [comment]
Thank you! :-)
I know the feeling, life happens, no pressure. I try to have a look at lifetimes, since Rust requires them even in the macros. Otherwise, this library (with swagger ui) is pretty neat and removes a lot of extra work when using openAPI spec.

I hope the PR #414 lands soon, as we have a data-scheme that requires other enum representations ;-)

Have a nice day, and thanks again for this crate!

**Comment by AlisCode** [comment]
Hey there, yes, I'm working on adressing the comments on my PR today. Sorry it took so long, I got busy with new years' and prioritized something else at work...

**Comment by buehler** [comment]
I'm digging into the syn crate to get an idea on how to parse the correct information out of it. As far as I dug until now, in `schema.rs`, we don't need "Generics" but more the effective information about the types. This would be my guess, why it still searches for "TResult" instead of the concrete type.

**Comment by buehler** [comment]
How do you guys test the macros locally? Use a demo cargo project and just git cargo build with println and stuff?

**Comment by juhaku** [comment]
With `Generics` not sure the lifetime is included to parsing and if not there is a need to parse the lifetimes as well before the generics. 

Way the `syn` crate works it converts rust code to a parseable token streams. But it is not a reflection and it does not understand context where it is living. Thus generated token streams does not understand relations to each other. This means that type like `struct Paginated<TResult> {}` does not know about possible values for the `TResult` and it does not know what are "implementations" of the `TResult`. If such parsing is needed that need to be done manually which is unnecesarily complex and not worth it. 

The way the `syn` works also makes some things not so straight forward e.g. if compared to some other langauge which has reflection support. 

Instead to achieve the lifetime support in these cases I belive there is a need to enhance the current `aliases` support in `ToSchema` derive.

> How do you guys test the macros locally? Use a demo cargo project and just git cargo build with println and stuff?

The easiest way is to write a test in `utoipa-gen/tests` folder for your usecase and test it with command line. Then also some cases use `println!` here and there where see fit and also `dbg!` macro is very useful. You can also use rust expand macro command available via rust_analyzer to expand the macro code (or cargo expand) to see if it generates correct code. That is useful as well in some cases.

**Comment by juhaku** [comment]
Seems like lifetimes are included to `Generics`. Quote from `syn::Generics`.
> Lifetimes and type parameters attached to a declaration of a function,
enum, trait, etc.

**Comment by buehler** [comment]
Yea, I played with `utoipa-gen` last evening. Turns out, parsing `syn::Type` instead of `Ident` and `Generics` is more "complete". So for starters, I changed the alias schema to:
```rust
struct AliasSchema {
  left: syn::Type,
  right: syn::Type,
}
```

and parse the types (with the `=` token in between). With this approach, all lifetime and generic information is included "for free". I managed to create the type alias again but now some part of the logic is not yet correct. (The error is something about a type alias cannot be used as constructor)

I'm investigating the matter ;-)

**Comment by buehler** [comment]
The change is bigger than expected. After refactoring to "type" instead of the manually parsed identifiers, the "into()" method of the schema is complaining about type aliases may not be used as constructors. As I can imagine, this change will introduce a big PR, wdyt?

**Comment by juhaku** [comment]
Interesting. I took a look at this today, and I was able to get quite reasonable solution with quite small amount of effort.  You can see the PR here: https://github.com/juhaku/utoipa/pull/458. 

In general it add support for aliases defined as follows. But I think this syntax should be phased out in favor of more generic Rust type alias support as  there is a need to generate schama components from aliases. This though cannot be a derive macro but instead it could be a simple macro rule or function macro.
```rust
 #[derive(ToSchema)]
 #[aliases(Paginated1<'b> = Paginated<'b, String>, Paginated2 = Paginated<'b, Value>)]
 struct Paginated<'r, TResult> {
     pub total: usize,
     pub data: Vec<TResult>,
     pub next: Option<&'r str>,
     pub prev: Option<&'r str>,
 }
```

**Comment by buehler** [comment]
It seems that I tried way to complicate 😅 
I will try it out right now and have a look if it works as expected.

**Comment by buehler** [comment]
While the lifetime identifier now works in the name, it does not in the type definition. That was the reason, why I tried to use `type` instead of a manual parsing.

`#[aliases(PaginatedBlockTypes<'a> = Paginated<'a, BlockType<'a>>)]` does not work (as an example)
This is a valid use-case if you want to use no-copy stuff.

**Comment by juhaku** [comment]
I can also check this at sometime to see whether it can be done easily.

**Comment by buehler** [comment]
No rush, I'll try again :-) If you have the time, it would be awesome, since it the only thing that's left in my use-cases.
It's fascinating to work with rust parsing...

My branch that I started uses type parsing instead of manual ident/generics parsing. It worked like a breeze to parse the whole type information. But then the generated code does not really compile.

As far as I know, other people have reported issues such as "cannot find type TResult" in the resulting json. This could be mitigated with type parsing because you have all information.

**Comment by juhaku** [comment]
> As far as I know, other people have reported issues such as "cannot find type TResult" in the resulting json. This could be mitigated with type parsing because you have all information.

I belive this happes because one might add the generic schema to the `#[openapi(components(schemas(...)))]` but one should actuallly place the aliases instead and not the type that has generics. Also if generic argument is another sized type e.g. struct like `struct Result {...}` then that should also be decorated with `#[derive(ToSchema)]` and registered in `#[openapi(components(schemas(...)))]`

**Comment by juhaku** [comment]
@buehler I also tried it out. And indeed it was not super easy at all. Somehow the `syn::Generics` does not support parsing nested generics with lifetimes which is a bummer. Perhaps there is a need to implement a better and more robust way to define type alias schemas but it is not super easy to implement and more or less this would need a centralized store for components in compiletime to make it more intuitive.

**Comment by buehler** [comment]
Yeah, the way to parse nested generics is with `syn::Type` which includes generic information about a type. As soon as I've time, I'll have a closer look into the code and maybe I'll come up with an idea. Your thought about a central component store would be a good start, one could pass an Arc (or other ref) with a component store to all parsing (and parsing alias) functions, and only at the end of all parsing generate all components. That way, even duplicates could be ruled out.

**Comment by juhaku** [comment]
I wrote another implementation now working with `syn::Type` and according to the tests it should work now with extensive use of lifetimes and even with nested generics. You can peek it here #546

**Comment by buehler** [comment]
need to try that asap :-D
