### ISSUE TITLE
[Feature Request] Serialize component properties in order of fields in struct definition

### ISSUE THREAD

**Issue by SanchithHegde** [juhaku/utoipa#428]
In certain use-cases, the order of fields in the request body (listed in the documentation) matters and having them sorted alphabetically (reference: #220) may not always be the best choice. Some fields might have to included first because they have more value compared to other fields. 

## Example

If we were to extend the `Todo` struct in the `todo-actix` example ([source code here](https://github.com/juhaku/utoipa/blob/e50da565e3b6afd5f1c2febea738b3d6057171e9/examples/todo-actix/src/todo.rs#L31-L42)) with a few more fields like so:

```rust
pub(super) struct Todo {
    id: i32,
    value: String,
    checked: bool,
    reminder: Option<OffsetDateTime>,
    tags: Vec<String>,
    repeat: Option<Duration>,
}
```

In this case, the `value` is an important field as it contains what the to-do list entry is about, while the other fields are optional and need not be provided. But sorting them alphabetically would cause them to be listed in the order: `[checked, id, reminder, repeat, tags, value]` moving the most important field to the extreme end of the list. This is just one of those cases where documenting fields in order of struct definition would have been beneficial compared to alphabetically sorted order.

## Feature Description

It would be great if the fields/properties documented for a specific struct followed the order of fields in the struct definition. Just to clarify, my request does not involve the order in which the components are listed (in the generated documentation), but only the order in which the properties of each component are listed. This should still generate meaningful and deterministic diffs that @Sytten mentioned in #210.

Let me know what you feel about this and if you'd like this change to be made, I can open a PR for it. Someone at work requested for this and I quickly made a hacky solution that just works for us ([commit](https://github.com/SanchithHegde/utoipa/commit/4ca5604f94484c7a5a7852972c9b6e68f33a871e)). My change involves storing the fields in a `Vec` of 2-tuples and serializing as a map of field-schema pairs.

**Comment by juhaku** [comment]
Sure this feature could be added here as well. In general it is enough to replace the `BTreeMap` in https://github.com/juhaku/utoipa/blob/e50da565e3b6afd5f1c2febea738b3d6057171e9/utoipa/src/openapi/schema.rs#L556 to a `IndexMap`. 

But since that field resides within a custom `builder!` macro rule the tricky part is how to do it conditionally. Preferably there should be a feature flag with name `preserve_order` to preserve schema properties order. Yet this is quite small addition with tests. 

I can also take a look at this a little later on.

**Comment by SanchithHegde** [comment]
Thanks for your suggestion, using an `IndexMap` is honestly a better solution than what I implemented.

> [...] Preferably there should be a feature flag with name preserve_order to preserve schema properties order. [...]

When you mention "feature flag", do you mean a cargo feature?

**Comment by juhaku** [comment]
> When you mention "feature flag", do you mean a cargo feature?

Yes, this way users can choose whether they want to preserve the order of properties or whether they want to have it sorted alphabetically.

**Comment by SanchithHegde** [comment]
Cool, I'll take this up and open a PR for the same.
