### ISSUE TITLE
Ability to manually implement Info struct

### ISSUE THREAD

**Issue by vikulikov** [juhaku/utoipa#430]
The docs say:
> OpenApi derive macro will also derive [Info](https://docs.rs/utoipa/latest/utoipa/openapi/info/struct.Info.html) for OpenApi specification using Cargo environment variables.

It would be great to be able to write a name and a description of a server independently of the cargo project.
Or may be this is already implemented. But I didn't find the usage example

**Comment by vikulikov** [comment]
Oh, I've found it in source code tests. I believe `info` param starts to work if `utoipa-gen` is added as dependency to the project.

**Comment by vikulikov** [comment]
So I see this functionality [was merged](https://github.com/juhaku/utoipa/pull/400) to main after the last lib release. Is it possible to build new version with these changes?

**Comment by vikulikov** [comment]
I've just realized I can reference git repo as a dependency

**Comment by juhaku** [comment]
If using a latest release from crates you need to do it manually overriding the generated info or by implementing OpenApi manually with the `OpenApiBuilder`. The other way is to use the master as a dependency version for the new functionality as you mentioned. 

> Is it possible to build new version with these changes?

There is still some things I want to include to the next release but I should be able to make it soon.

**Comment by vikulikov** [comment]
Great project by the way. Thanks a lot to maintaining! Saved me a lot of time.
