### ISSUE TITLE
Is there any way to configure servers in the docs?

### ISSUE THREAD

**Issue by Star3Lord** [juhaku/utoipa#434]
Hi,

I was trying to add servers to openapi docs but couldn't find a way in the crates's docs.

I am looking for configuration similar to this
```rs
#[derive(OpenApi)]
#[openapi(
  ...
  servers(
    (url = "/v1"),
  )
)]
```

Is there a way to do it that I overlooked, if not are there any plans to add it?

**Comment by juhaku** [comment]
> Is there a way to do it that I overlooked, if not are there any plans to add it?

There is actually in master branch, coming in next release. But currently adding servers need to be done manually with `Modify` trait or directly via OpenApi types for example like this.
```rust
#[derive(OpenApi)]
struct ApiDoc;

let doc = ApiDoc::openapi();
doc.servers = ...
```

**Comment by Star3Lord** [comment]
> 

Got it. Thanks.

**Comment by juhaku** [comment]
Closing, I assume the issue at hand is resolved. Can be reopened in future if needed.
