### ISSUE TITLE
Group and nest related paths/components

### ISSUE THREAD

**Issue by TehPers** [juhaku/utoipa#445]
It seems to me that all the routes and components need to be defined in one spot when using `#[derive(OpenApi)]`. For a larger project, this can easily balloon in size. It would be nice if we could group related paths and components into smaller API definitions and include them all at once in a nested route.

```rs
mod foo {
    #[derive(SubApi)]
    #[subapi(
        paths(get_foo, set_foo, list_foos),
        components(schemas(Foo)),
    )]
    struct FooModule;

    // Routes and struct definitions...
    #[path(get, path = "/{id}", /* ... */)]
    async fn get_foo(Path(id): Path<u32>) { todo!() }
}

mod bar {
    #[derive(SubApi)]
    #[subapi(
        paths(get_bar, set_bar, list_bars),
        components(schemas(Bar)),
    )]
    struct BarModule;

    // Routes and struct definitions...
}

#[derive(OpenApi)]
#[openapi(
    nest(
        ("/foo", FooModule),
        ("/bar", BarModule),
    ),
)]
struct ApiDoc;
```

**Comment by juhaku** [comment]
Hey @TehPers , 

Thanks for suggestion. There is coming `merge` functionality to the OpenApi just for this purpose. Bigger APIs have defined these manually by now. But this macro attribute `nest` functionality could be considered. At first there is a need to investigate whether it is possible in some reasonable way.

**Comment by echelon** [comment]
Hi @juhaku, our team finds this issue useful to our work. Is there a way to sponsor you to work on this particular ticket? 

Thanks!

**Comment by juhaku** [comment]
Now there is coming implementation for this feature #930
