### ISSUE TITLE
Support for unit type

### ISSUE THREAD

**Issue by Erisli** [juhaku/utoipa#448]
When using ToSchema for structs that contains the following type for a member, Utoipa thinks this is a tuple type that was not supported even it is a unit type.

```
Option<Result<(), CustomError>>
```

**Comment by biwecka** [comment]
Hi, I guess a first attempt in this direction was made by supporting unit structs (#392) but unfortunately this does not include the unit type `()`. I looked into the code and as far as I can tell support for the unit type cannot be implemented the same way support for unit structs was implemented because the `ToTokens` trait is imported from another library and can therefore not be implemented for the unit type.
But it would be possible to implement the `ToSchema` trait for `()` (similar to the suggestion here #332).
It would look something like this:
```rust
// utoipa/src/lib.rs

/// Implement [`ToSchema`] trait for unit type.
impl ToSchema for () {
    fn schema() -> openapi::RefOr<openapi::schema::Schema> {
        openapi::schema::ObjectBuilder::new()
            .nullable(true)
            .default(Some(serde_json::Value::Null))
            .example(Some(serde_json::Value::Null))
            .into()
    }
}
```
The only thing I'm unsure about is if the `.nullable(true)` is correct. Maybe someone can help with that.
@juhaku Would you accept a pull request containing this feature?

**Comment by juhaku** [comment]
Sure PRs are welcome. We could implement `ToSchema` for `()` but I believe first we need to see how serde is actually going to serialize the unit `()` type. `.nullable(true)` allows value be `null` OpenAPI spec which is crusial in cases if  the json serialized value is expected to be null. Depending on if `()` would not serialize to `null` then `.nullable(true)` is not needed either. 

Another thing to confirm is how the `TypeTree` is currently behaving with the unit `()` type. And whether there is something that can be done to distinct it from other types.

**Comment by biwecka** [comment]
I got the following code to compile with the changes made in my pull request draft.
```rust
#[derive(Serialize, Deserialize, Debug, Default, ToSchema)]
pub struct Data {
    pub unit_type   : (),
}

#[utoipa::path(
    get,
    path = "/root",
    responses (
        ( status = 200, description = "", body = Data)
    )
)]
pub fn root() -> () {}

#[derive(OpenApi)]
#[openapi(paths(self::root), components(schemas(Data)))]
struct ApiDoc;

fn main() {
    println!("{}", ApiDoc::openapi().to_pretty_json().unwrap());
}
```

The "components" part of the output looks like this:
```json
"components": {
    "schemas": {
      "Data": {
        "type": "object",
        "required": [
          "unit_type"
        ],
        "properties": {
          "unit_type": {
            "type": "object"
          }
        }
      }
    }
  }
```
I guess this is a first step but I'd say the goal would be to generate the following schema for `"unit_type"`:
```json
"unit_type": {
  "type": "object",
  "default": null,
  "example": null,
  "nullable": true
}
```

I tried to achieve that by implementing the `ToSchema` trait for `()` but that didn't change anything. I guess what I'm looking for happens in `utoipa-gen/src/component/schema.rs` but I don't know how the `TypeTree` gets there. Can someone help me with this?

**Comment by biwecka** [comment]
I got it to work 🎉 A unit type `()` is now represented by the following schema properties:
```json
"type": "object",
"default": null,
"example": null,
"nullable": true
```
Is this the desired behavior or should it be something else?

**Comment by juhaku** [comment]
> I got it to work :tada: 

Awesome. :partying_face: 

> Edit: I have another question. Is it possible to restrict the schema of the property further? Because `"type": "object" `probably describes any JSON object. Is it possible to specify the type as an empty object `{}`?

Yes it could be set to `{}` but the result is the same as `type: "object"`  to my knowledge. Might be wrong though. Would need to check from the openapi docs how this generic object definition went. 

> Is this the desired behavior or should it be something else?

I think that is just fine, maybe we can remove the `example: null,` since the default value is null.

**Comment by biwecka** [comment]
I removed the `example: null` as you suggested and quickly checked the OpenAPI docs for a `"type": "{}"`. But they don't mention something like this. The only thing we can specify is something like this:
```json
{
  "type": "object",
  "properties": {}
}
```
But as `properties` is set to `{}` by default I don't think we should do this as it's not necessary.

I encountered another "problem". When I tried to use the new feature in my current project this happened:
```rust
#[derive(Serialize, Deserialize, Debug, ToSchema)]
pub struct Data {
    pub unit_type   : (),
    pub generic     : DataWithRelations<()>
}

// Define data struct
#[derive(Serialize, Deserialize, Debug, Default, ToSchema)]
pub struct DataWithRelations<T: GenericDataRelation> {
    pub value: i32,
    pub relations: T,
}

// Define relation trait
pub trait GenericDataRelation {}
impl GenericDataRelation for () {}

// Root function
#[utoipa::path(
    get,
    path = "/root",
    responses (
        ( status = 200, description = "", body = Data)
    )
)]
pub fn root() -> () {}

#[derive(OpenApi)]
#[openapi(paths(self::root), components(schemas(Data, DataWithRelations<()>)))]
struct ApiDoc;

fn main() {
    println!("{}", ApiDoc::openapi().to_pretty_json().unwrap());
}
```

The important part of the output looks like this:
```json
"components": {
    "schemas": {
      "Data": {
        "type": "object",
        "required": [
          "unit_type",
          "generic"
        ],
        "properties": {
          "generic": {
            "$ref": "#/components/schemas/DataWithRelations"
          },
          "unit_type": {
            "type": "object",
            "default": null,
            "nullable": true
          }
        }
      },
      "DataWithRelations": {
        "type": "object",
        "required": [
          "value",
          "relations"
        ],
        "properties": {
          "relations": {
            "$ref": "#/components/schemas/T"
          },
          "value": {
            "type": "integer",
            "format": "int32"
          }
        }
      }
    }
  }
```
As you can see `"relations"` references `"#/components/schema/T"` which is not defined though. Is this related to my PR or is this a different issue?

**Comment by juhaku** [comment]
> As you can see "relations" references "#/components/schema/T" which is not defined though. Is this related to my PR or is this a different issue?

This is related to generics. Component what is having generic arguments should not be declared within `#[openapi(components(schemas(...)))]` but instead you should create aliases for them. This is because at compile time we cannot know what that `T` bound should be.

Here's the docs for generics: https://docs.rs/utoipa/latest/utoipa/derive.ToSchema.html#generic-schemas-with-aliases

**Comment by juhaku** [comment]
> But as properties is set to {} by default I don't think we should do this as it's not necessary.

I agree, it can be just as decided earlier

**Comment by biwecka** [comment]
> > As you can see "relations" references "#/components/schema/T" which is not defined though. Is this related to my PR or is this a different issue?
> 
> This is related to generics. Component what is having generic arguments should not be declared within `#[openapi(components(schemas(...)))]` but instead you should create aliases for them. This is because at compile time we cannot know what that `T` bound should be.
> 
> Here's the docs for generics: https://docs.rs/utoipa/latest/utoipa/derive.ToSchema.html#generic-schemas-with-aliases

Thank you! I didn't know about this. Hopefully I'll be able to solve the problem with this.

**Comment by biwecka** [comment]
@juhaku Unfortunately `#[derive(EmptyData = Data<()>)]` does not work. The compiler complains about the parentheses with `expected one of: lifetime, identifier, 'const'`.
Therefore I implemented `ToSchema<'__s>` for `()` and created a type alias like this:
```rust
type UnitType = ();

#[derive(ToSchema)]
#[aliases(EmptyData = Data<UnitType>)]
struct Data<T> {
    value: T
}


// Root function
#[utoipa::path(
    get,
    path = "/root",
    responses (
        ( status = 200, description = "", body = EmptyData)
    )
)]
pub fn root() -> () {}

#[derive(OpenApi)]
#[openapi(paths(self::root), components(schemas(EmptyData, UnitType)))]
struct ApiDoc;
```
Now I have two questions:
- Is there an alternative to using `#[aliases(...)]`. For example `type EmptyData = Data<UnitType>`? I tried that but it didn't work.
- Where is the code for `#[aliases(...)]` and is it possible to extend it to support `()`?

**Comment by juhaku** [comment]
> Is there an alternative to using #[aliases(...)]. For example type EmptyData = Data<UnitType>? I tried that but it didn't work.

Currently there is no alternative. But I am hoping to introduce a better and more robust way of declaring type aliases. But it is still quite unclear how to declare them.

> Where is the code for #[aliases(...)] and is it possible to extend it to support ()?

In theory that is posissble but it is really hard. There is also another thread about this aliases support discussing about better lifetime support https://github.com/juhaku/utoipa/issues/427. Also introducing changes for better lifetime support is also quite hard thus they also would require better way to define aliases.

I created another PR for the unit type support what should make some minor improvements to it.
