### ISSUE TITLE
#[get(..)] and #[utoipa::path(..)] fails without path =  

### ISSUE THREAD

**Issue by jayvdb** [juhaku/utoipa#451]
With `post` and `put` and likely others, I can do

```rust
#[utoipa::path(
    request_body  = MyStruct,
    responses(
        (status = 201, description = "Done something")
    ),
    security(
        ("api_key" = [])
    ),
)]
#[post("/my_endpoint")]
pub async fn foobar(req: HttpRequest, body: Json<MyStruct>) -> HttpResponse { .. }
```

However the same with `get` fails.
```rust
#[utoipa::path(
    responses(
        (status = 200, description = "Done successfully", body = MyStruct)
    ),
    security(
        ("api_key" = [])
    ),
)]
#[get("/get_props")]
pub async fn get_props() -> MyStruct { .. }
```
results in
```rust
error[E0277]: the trait bound `MyStruct: Responder` is not satisfied
   --> src/foobar.rs:68:14
    |
67  | #[get("/get_props")]
    | -------------------- required by a bound introduced by this call
68  | pub async fn get_props() -> MyStruct {
    |              ^^^^^^^^^ the trait `Responder` is not implemented for `MyStruct`
    |
    = help: the following other types implement trait `Responder`:
              &'static [u8]
              &'static str
              &std::string::String
              (R, StatusCode)
              BytesMut
              Cow<'_, str>
              CustomizeResponder<T>
              Either<L, R>
            and 13 others
note: required by a bound in `actix_web::Resource::<T>::to`
   --> /home/jayvdb/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.2.1/src/resource.rs:226:20
    |
226 |         F::Output: Responder + 'static,
    |                    ^^^^^^^^^ required by this bound in `actix_web::Resource::<T>::to`

For more information about this error, try `rustc --explain E0277`.
```

To get it working, I need to "copy" the `#[get]` info into `#[utoipa::path(..)`, like below.  This inconsistency feels quite odd.
```rust
#[utoipa::path(
    get,
    path = "/get_props",
    responses(
        (status = 200, description = "Done successfully", body = MyStruct)
    ),
    security(
        ("api_key" = [])
    ),
)]
pub async fn get_props() -> MyStruct { .. }
```

The `#[get("/get_props")]` can still be in there, but it is superfluous, at best duplicating the info, and maybe can even get out of sync which would be confusing.

Worth noting that the approach which doesnt work is used at https://github.com/juhaku/utoipa/blob/b167838/utoipa-gen/src/lib.rs#L938-L943 , and that doctest is failing at the moment because of this.

I checked at this also occurred in v2.4.2

**Comment by juhaku** [comment]
Did you run it with `actix_extras` feature flag? The project has 3 exclusive features which are `actix_extras`, `axum_extras` and `rocket_extras`. Only one can be enabled at the time. These features will add support for path and path handler argument resolving as openapi path arguments.

> Worth noting that the approach which doesnt work is used at https://github.com/juhaku/utoipa/blob/b167838/utoipa-gen/src/lib.rs#L938-L943 , and that doctest is failing at the moment because of this.

Here the `/// #[get("/pet/{id}")]` is actix web path attribute macro thus only supported in actix web. Rocket has similar macro which is supported with `rocket_extras` feature flag. Other frameworks does not have support for such macros.

**Comment by jayvdb** [comment]
Yes, I have `actix_extras` feature enabled in my project.

**Comment by juhaku** [comment]
Hey @jayvdb, 

Is this still an issue? To get back to this as what is in the `actix-todo` example in `./examples/` that declaration works on get operations as well. https://github.com/juhaku/utoipa/blob/master/examples/todo-actix/src/todo.rs#L73
```rust
#[utoipa::path(
    responses(
        (status = 200, description = "List current todo items", body = [Todo])
    )
)]
#[get("/todo")]
pub(super) async fn get_todos(todo_store: Data<TodoStore>) -> impl Responder {
    let todos = todo_store.todos.lock().unwrap();

    HttpResponse::Ok().json(todos.clone())
}
```

Did you provide the correct path to the actix-web `get` macro declaration?

**Comment by juhaku** [comment]
But that error indeed looks a bit wanky. Is there something fishy going on with cache. If you try to run command `cargo update` maybe even with `--argressive` flag. And then if nothing helps deleting the folder: `/home/jayvdb/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.2.1` which would cause the dependency to be re indexed.

**Comment by jayvdb** [comment]
I have more recently switched to using the `-> impl Responder` style, actually `-> Result<impl Responder>`, and no longer have this problem, and honestly probably couldnt re-create the precise scenario of the original report again.  So best to just close.
