### ISSUE TITLE
Vec / array descriptions go to item instead of array

### ISSUE THREAD

**Issue by mlagoma** [juhaku/utoipa#474]
When documenting a struct field that's a vector, the description is added to the item in the array instead of the array itself.

Example:
Current behavior:
```
"structField": {
  "type": "array",
  "items": {
    "type": "string",
    "description": "Description of struct field."
  }
}
```
Intended(?) behavior:
```
"structField": {
  "type": "array",
  "description": "Description of struct field.",
  "items": {
    "type": "string"
  }
}
```
At least the intended behavior is what works with https://github.com/stoplightio/elements

**Comment by juhaku** [comment]
I'll need to investigate this a bit when I get time, this smells like a bug at first sight though.

**Comment by juhaku** [comment]
Fix is on the way, and landing in the next release :slightly_smiling_face:
