### ISSUE TITLE
Support for non-required tuple type path parameters

### ISSUE THREAD

**Issue by sondrelg** [juhaku/utoipa#479]
Hi!

First of all, thanks for maintain this great library! Super useful :bow: 

I see that it is possible to generate non-required parameters by using the `Option` type, when defining parameters like this:

```rust
#[derive(IntoParams)]
pub struct Params {
    foo: Option<u8>,
}
```

However, it does not seem to work for manually documented parameters. I have a macro invocation that looks like this:

```rust
#[utoipa::path(
    get,
    path = "...",
    responses((status = 200, description = "...", body = Body)),
    params(
        ("foo" = String, Path, description = "..."),
        ("bar" = Option<String>, Path, description = "..."),
    ),
    tag="..."
)]
```

At least in my generated UI `bar` remains required :slightly_smiling_face: 

Am I missing something? Couldn't find anything in the docs about this, so thought it might just be something that still needs implementing?

**Comment by juhaku** [comment]
Hey,

Great that you have enjoyed. It should work, but there might be a bug that it behaves differently. I need to check this from the code and see what is actually going on to be sure. I'll get back to this when I have time.

**Comment by juhaku** [comment]
As of these PRs (https://github.com/juhaku/utoipa/pull/525, https://github.com/juhaku/utoipa/pull/498) the definition of `required` changes to strictly according to how serde serializes types. This means that `Option` is nullable, but always required if it has not
* serde's `skip_serializing_if` 
* and serde's `with` double option
* and field does not have default value

This implies that manual tuple style path parameters are always `required` without an option to change it. Non-required parameters can only achieved with `IntoParams` derive macro.

**Comment by sondrelg** [comment]
Ok I see, thanks for looking into it 👍

**Comment by juhaku** [comment]
@sondrelg As of some issues that have arised mentioned here #529, the `Option` field will from now on will be considered non-required as before, but can be optionally enforced to be `required` by using newly introduced `required` attribute #530.

**Comment by sondrelg** [comment]
So if I'm understanding you correctly, it will be possible to define optional variables using the both the `path` macro, and using the `IntoParams` macro after all?

**Comment by juhaku** [comment]
> So if I'm understanding you correctly, it will be possible to define optional variables using the both the path macro, and using the IntoParams macro after all?

Yes, currently with the latest master and with next release when released.

**Comment by sondrelg** [comment]
Cool, thanks!
