### ISSUE TITLE
Swagger UI file not found

### ISSUE THREAD

**Issue by EvilWatermelon** [juhaku/utoipa#482]
Hi,

I went through the rocket-todo example and implemented my own URI. Cloning the example worked but when I call the swagger UI in my project I only get `Swagger UI file not found`.

main.rs
```rust
#[launch]
fn rocket() -> Rocket<Build> {
    //Connect to mariadb
    db::init();
    redis_service::init();

    #[derive(OpenApi)]
    #[openapi(
        paths(
            controller::communication_controller::get_all_ips
        ),
        components(
            schemas(controller::communication_controller::Communication, controller::communication_controller::CommunicationError)
        ),
        tags(
            (name = "communication", description = "all uris for mqtt")
        )
    )]
    struct ApiDoc;

    rocket::build()
        .manage(controller::communication_controller::CommunicationStore::default())
        .mount("/", 
            routes![sub])
        .mount("/v1",
        SwaggerUi::new("/swagger-ui/<_..>")
                .url("/api-doc/openapi.json", ApiDoc::openapi()))
        .mount("/ip", 
            routes![get_all_ips, get_specific_ip])
        .mount("/game", 
            routes![])
        .mount("/user", 
            routes![authentication, new_user])
        .mount("/cache", 
            routes![create, get, update, delete])
}
```

communication_controller.rs
```rust
pub type CommunicationStore = Arc<Mutex<Vec<Communication>>>;

#[derive(Serialize, ToSchema, Responder, Debug)]
pub enum CommunicationError {
    /// When there is conflict creating a new todo.
    #[response(status = 409)]
    Conflict(String),

    /// When todo item is not found from storage.
    #[response(status = 404)]
    NotFound(String),

    /// When unauthorized to complete operation
    #[response(status = 401)]
    Unauthorized(String),
}

#[derive(Serialize, Deserialize, ToSchema, Clone)]
pub struct Communication {
    /// Unique todo id.
    #[schema(example = 1)]
    id: i32,
    /// Description of a tasks.
    #[schema(example = "Buy groceries")]
    value: String,
    /// Indication whether task is done or not.
    done: bool,
}

#[utoipa::path(
    context_path = "/",
    responses(
        (status = 200, description = "Get all ips", body = [Communication])
    )
)]
#[get("/all")]
pub async fn get_all_ips() -> (Status, &'static str) {
    ip_domain_service::read_ipsets().await;
    return (Status::Ok, "200 - OK");
}
```

**Comment by juhaku** [comment]
Hey,

They can reside in different files and you can organize the project how you see will best fit for your usecase. Though there is one limitation with the `SwaggerUi` when using with `rocket`, that is you need to define the path within the `SwaggerUi` from your app root to where you expect the Swagger UI and the `openapi.json` be served. 

In the example below it does not work, as expected and likewise you have found out. What happens is that the `SwaggerUi` struct will create a routes for Swagger UI and `openapi.json` according to what is defined to the `new(..)` and `url(...)` methods. To cut the chase you are telling rocket to  mount Swagger UI to `/api/v1/.....` and it will be mounted like so. Same thing happens for the `openapi.json` but the actual route will be created to path `/api-doc/openapi.json` **not** `/v1/api-doc/openapi.json`. That will cause the above situation where `Swagger UI file not found` error happens.

This situation can be avoided in axum and perhaps in actix_web as well. By providing a custom config to the SwaggerUI which explisitly defines the `openapi.json` URL that the Swagger UI should be using. Yet unfortunately that does not work in rocket.
```rust
.mount("/v1",
        SwaggerUi::new("/swagger-ui/<_..>")
                .url("/api-doc/openapi.json", ApiDoc::openapi()))
```

So currently only way to define the paths for rocket is to define them explisitly from the root of the project. If you want them to be exposed from `/v1/...` then the paths need to be prefixed with it.
```rust
.mount("/",
        SwaggerUi::new("/v1/swagger-ui/<_..>")
                .url("/v1/api-doc/openapi.json", ApiDoc::openapi()))
```

**Comment by EvilWatermelon** [comment]
Hi,
thanks, that seems to work but now I get a `500` with `thread 'rocket-worker-thread' panicked at 'byte index 15 is out of bounds of `/v1/swagger-ui`' .cargo/registry/src/github.com-1ecc6299db9ec823/utoipa-swagger-ui-3.0.2/src/rocket.rs:75:29`. Is that also a problem of utoipa?

**Comment by EvilWatermelon** [comment]
This issue is still relevant

**Comment by juhaku** [comment]
Hi, sorry haven't had much time to invest in this. I try to get back to this as soon as I get some time. There are bunch of issues pending acknowledgement as well. 

But just a quick note to the issue you are facing, it is really fascinating, because basically it should never get to the 500 error when trying to retrieve something from Swagger UI. 
```rust
        match super::serve(&request.uri().path().as_str()[path.len()..], self.1.clone()) { <!--- the error is happening on this line,
            Ok(swagger_file) => swagger_file
                .map(|file| Outcome::from(request, file))
                .unwrap_or_else(|| Outcome::from(request, NotFound("Swagger UI file not found"))),
            Err(error) => Outcome::from(
                request,
                status::Custom(Status::InternalServerError, error.to_string()),
            ),
        }
```
Do you happen to have logs about what kind of URL your API is actually receiving? 
On the above line, it should try to parse tail path from request path which is everything after and including the `<..>` tail operator in rocket. However that fails for some starge reason with index out of bounds error, which indicates that the path is not really correct for one reason or another.

**Comment by EvilWatermelon** [comment]
Hi, no problem.
I don't have any logs or I don't know which logs you mean.

But I understand the error. After deleting the `/swagger-ui` String from `/swagger-ui/<_..>` everything worked fine.
