### ISSUE TITLE
Paths in OAS contain unnecessary deprecated: false

### ISSUE THREAD

**Issue by jayvdb** [juhaku/utoipa#487]
https://github.com/juhaku/utoipa/blob/fe04203e59e259508b365593828a15845990ba4e/utoipa-gen/tests/path_response_derive_test.rs#L307 shows an example of the output containing an unnecessary `deprecated: false`, as that is the default value.

**Comment by juhaku** [comment]
Good catch, this can be removed in future release. Should not be a biggie to do.
