### ISSUE TITLE
path responses "default" for all other HTTP codes

### ISSUE THREAD

**Issue by jayvdb** [juhaku/utoipa#496]
https://swagger.io/docs/specification/describing-responses/#default allows a "default" response, for any other HTTP code, usually used to describe all error codes, like so:

```yaml
          responses:
            '200':
              description: Success
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/User'
            # Definition of all error statuses
            default:
              description: Unexpected error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Error'
```

It doesnt appear utoipa allows for this.  I tried:
```rust
#[utoipa::path(
    ...
    responses(
        (status = 200, description = "Data sent", body = MyStruct),
        (status = default, description = "Unexpected error")
    ),
    ...
)]
...
```

`git grep '"default":'` also showed nothing relevant, so this isnt appearring in any JSON in the repo.

Building support for the "default" response would make it much easier to generate the entire "responses" because `Result<Foo, Error>` then maps to two responses, one being `Foo` and the other being "default" for any error thrown in the function. c.f. https://github.com/juhaku/utoipa/issues/106

**Comment by juhaku** [comment]
This should be implemented, might be that it does not provide any relevant error message for user though. If you try to write it like this:
```rust
(status = "default", description = "Unexpected error")
````

**Comment by jayvdb** [comment]
Thank you.

I tested that, and it works.  Also it is documented at https://docs.rs/utoipa/latest/utoipa/attr.path.html#response-attributes

And I found some tests for `"default"` and `"5XX"` in `utoipa-gen/tests/path_response_derive_test.rs`
