### ISSUE TITLE
How to set default value for enum type in a struct.

### ISSUE THREAD

**Issue by grindarius** [juhaku/utoipa#499]
Hello. First of all I wanted to say thank you so much for creating this beautiful library. I wanted to ask a question about how to set default value on an enum.

I have a struct
```rust
#[derive(serde::Deserialize, serde::Serialize, utoipa::ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum GetPostListRequestQueriesOrderBy {
  LatestActivity,
  Vote,
  Time,
}

#[derive(serde::Deserialize, serde::Serialize, utoipa::ToSchema, utoipa::IntoParams)]
#[into_params(parameter_in = Query)]
pub struct GetPostListRequestQueries {
  #[param(default = json!(GetPostListRequestQueriesOrderBy::Time))]
  pub by: Option<GetPostListRequestQueriesOrderBy>,
}
```

I have tried this combination and opened it on the web. And I found that it does not show the _`Default value: ...`_ when I look in the UI.
![image](https://user-images.githubusercontent.com/60266519/221134175-d8b2e2d9-925b-4908-ad01-671275d34972.png)

Unlike primitive types that works right out the box
![image](https://user-images.githubusercontent.com/60266519/221134381-b0a14219-62e4-4156-b21b-f9253f7302d1.png)

Is this the limitation by the openapi specifications?. Thank you for any response.

**Comment by baabgai** [comment]
I stumbled upon the same problem just yesterday and as far as I could figure out it's not yet possible to set enum defaults with the param or schema macro.
My current workaround uses the Modify trait a long the lines of

```rust
struct GetPostListModifier;

impl Modify for GetPostListModifier {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        openapi.components.as_mut().map(|v| {
            v.schemas.get_mut("GetPostListRequestQueriesOrderBy").map(|z| {
                if let RefOr::T(schema) = z {
                    if let Schema::Object(obj) = schema {
                        obj.default = Some(json!("time"));
                    }
                }
            })
        });
    }
}

```

finally add the modifier to your main macro 
```rust
#[derive(OpenApi)]
#[openapi(
    paths(...),
    components(schemas(GetPostListRequestQueriesOrderBy, ...)),
    modifiers(&GetPostListModifier)
)]
struct ApiDoc;

```
This does what I want, but it would be very convenient if we could set default Values for enums as easy as for the primitive values.

**Comment by grindarius** [comment]
Closing this for now.
