### ISSUE TITLE
Can I make aliases manually instead of derive?

### ISSUE THREAD

**Issue by kvzn** [juhaku/utoipa#503]
Cause I want to setup openapi with utoipa manually like below, I can't make aliases through the way `#[aliases(BarString = Bar<String>)]`, is there any way I can achieve this by manual coding? Thank you!
```rust
#[derive(Debug, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct PageResult<T> {
    pub items: Vec<T>,
    pub total: Option<usize>,
}

fn load_openapi<'a>() -> (
    Vec<(&'a str, utoipa::openapi::PathItem)>,
    Vec<(&'a str, utoipa::openapi::RefOr<utoipa::openapi::Schema>)>,
) {
    let mut paths = vec![];

    paths.push((__path_list_public::path(), __path_list_public::path_item(None)));

    type PageResultProjectDto = PageResult<ProjectDto>;

    let schemas = vec![
        Project::schema(),
        PageResultProjectDto::schema(),
    ];

    (paths, schemas)
}

pub(crate) fn setup_openapi() -> utoipa::openapi::OpenApi {
    let mut paths = utoipa::openapi::path::Paths::new();
    let mut components = utoipa::openapi::Components::new();

    let (ps, ss) = load_openapi();

    for (k, v) in ps {
        paths.paths.insert(k.to_string(), v);
    }

    for (k, v) in ss {
        components.schemas.insert(k.to_string(), v);
    }

    utoipa::openapi::OpenApiBuilder::new()
        .info(
            utoipa::openapi::InfoBuilder::new()
                .title("Test")
                .version("0.1.1")
                .description(Some("API document!"))
                .license(Some(utoipa::openapi::License::new("MIT")))
                .contact(Some(
                    utoipa::openapi::ContactBuilder::new()
                        .name(Some("Test"))
                        .email(Some("test@gmail.com"))
                        .build(),
                ))
                .build(),
        )
        .paths(paths)
        .components(Some(components))
        .build()
}
```

**Comment by juhaku** [comment]
Currently there is no another built-in way to do that. One way one can do something like that is to use the utoipa's builder API and OpenAPI types to manually build a schema for the alias and then add it to the OpenAPI doc manually. In such case it might be useful to write a macro for it if it seems to be repetitive work.

**Comment by kvzn** [comment]
> Currently there is no another built-in way to do that. One way one can do something like that is to use the utoipa's builder API and OpenAPI types to manually build a schema for the alias and then add it to the OpenAPI doc manually. In such case it might be useful to write a macro for it if it seems to be repetitive work.

Thank you, I will try it. BTW, great job!

**Comment by KaanMol** [comment]
@juhaku, I'm wondering if it's possible to define a generic response body at the `ApiDoc` level so that Utoipa can wrap my body in the specified response body. This would be a feasible alternative to using generics, for the people who use the same response bodies. Specifically, I'm thinking of using the following response structure for all success responses:

```rust
pub struct ApiResponse<T>
where
    T: Serialize,
{
    success: bool,
    error: Option<ResponseError>,
    data: Option<T>,
}
```

**Comment by juhaku** [comment]
> I'm wondering if it's possible to define a generic response body at the ApiDoc level so that Utoipa can wrap my body in the specified response body.

I am not sure what you had in mind. Like taking your example above, the hard part is make utoipa to understand the difference between all alternatives. Like when the type is used with different types like `ApiResponse<Vec<Person>>` or `ApiResponse<Customer>`.

In utoipa, the `ToSchema` derive macro generates the OpenAPI schema for the type and it only has access to the type it is decoreated with it. If `ApiResponse` is decorated with `ToSchema` then at that point it does not know what should be possible types for `T`. 

Generally speaking of providing a way to wrap a generic response to typed response would not be out of bounds. But at least I haven't yet figured out a bulletproof way to do so. :slightly_smiling_face:

**Comment by KaanMol** [comment]
> I am not sure what you had in mind. Like taking your example above, the hard part is make utoipa to understand the difference between all alternatives. 

My proposal would be something like
```rust
#[derive(OpenApi)]
#[openapi(
    paths(
         ping
    ),
    tags(
        (name = "NAME", description = "DESC")
    ),
    response_body(ApiResponse)
)]
pub struct RootApiDoc;
```

Where ApiResponse would be the generic and if this field is set, all api routes would get wrapped around with it.
I absolutely have no clue if this is feasible or not.

Would it be possible to write something with a modifier that wraps all endpoint bodies in a specific generic?

**Comment by litcc** [comment]
So far this code meets my requirements for a generic structure, however, it may not work well enough
https://github.com/litcc/utoipa/tree/dev-generic

**Comment by juhaku** [comment]
> ```rust
> #[derive(OpenApi)]
> #[openapi(
>    paths(
>         ping
>    ),
>    tags(
>        (name = "NAME", description = "DESC")
>    ),
>    response_body(ApiResponse)
> )]
> pub struct RootApiDoc;
> ```
> Where ApiResponse would be the generic and if this field is set, all api routes would get wrapped around with it.
I absolutely have no clue if this is feasible or not.

I prefer keeping the derive macro args as close as possible to the OpenAPI specification itself. Another thing is that currently `OpenApi` derive macro does not have access to the component schemas derived with `ToSchema`. 

> Would it be possible to write something with a modifier that wraps all endpoint bodies in a specific generic?

Yes, I believe it is possible with `Modifier` trait. That is, it just needs some manual implementation e.g. looping through the schemas and then remapping them with a generic schema. 

@kvzn The manual implementation got a lot simplier with this PR #544.

**Comment by kvzn** [comment]
Super cool, thank you!

**Comment by juhaku** [comment]
@kvzn @KaanMol @litcc There is now WIP implementation #1034  for real generics support. This should solve this case as well.
> ```rust
> pub struct ApiResponse<T>
> where
>    T: Serialize,
> {
>     success: bool,
>     error: Option<ResponseError>,
>     data: Option<T>,
> }
> ```
