### ISSUE TITLE
Chrono NaiveDateTime support

### ISSUE THREAD

**Issue by pascaldanek** [juhaku/utoipa#505]
I am currently trying to add openapi support to our API. We use NaiveDateTime exclusively. Would it be possible to add support for it as part of the chrono feature ? Thanks !

**Comment by juhaku** [comment]
Hey, sure that can be added, well do for next release.

**Comment by pascaldanek** [comment]
Thanks for the quick response :) I have tried adding type annotations in the meantime, on NaiveDateTime fields on a givne struct. The struct is used by itself, but also nested in another struct in an API response. When adding struct, the schema errors for the struct in its nested version remain. Any clue ?

**Comment by juhaku** [comment]
@pascaldanek  
> When adding struct, the schema errors for the struct in its nested version remain. Any clue ?

I am not sure what do you mean. Could you provide me possible errors and or even better types as well?
