### ISSUE TITLE
Support expresions where as literal string within derive macro attributes

### ISSUE THREAD

**Issue by juhaku** [juhaku/utoipa#518]
As discussed here https://github.com/juhaku/utoipa/issues/480#issuecomment-1468866062, add support for expressions in various places of `ToSchema`, `OpenApi`, `utoipa::path`, `IntoParams`, `ToResponse`, `IntoResponses` derive macros.

Currently expresssions are not widely supported. The support should be added where applicable. 

## Example

```rust
const MY_CONST: &str = "/api";

#[utoipa::path(context_path = MY_CONST)]
async fn get_item() {}
```

**Comment by steven-joruk** [comment]
This mentions literal strings, I'd like to extend the request to include const expressions or integer literals for attributes such as max_length, min_length, min, max. Let me know if I should open a new issue. Thanks.

**Comment by juhaku** [comment]
No need to create a seprate issue for that. The implementation can be done here.
