### ISSUE TITLE
Auto-populate default values in `ToSchema` derive macro

### ISSUE THREAD

**Issue by cwatson-blackrock** [juhaku/utoipa#519]
It would be great to be able to automatically populate the default values for fields of a struct that implements `Default`.
So instead of:

```rust
#[derive(ToSchema)]
struct Foo {
    #[schema(default = 12)]
    a: u64,
    #[schema(default = "Hello")]
    b: String,
}
```

We could use:

```rust
#[derive(ToSchema)]
struct Foo {
    a: u64,
    b: String,
}

impl Default for Foo {
    fn default() -> Self {
        Self { a: 12, b: "Hello" }
    }
}
```
(Maybe with the addition of  a`#[schema(default)]` attribute or similar on the struct.)

Which would add `.default(Some(::serde_json::to_value(#struct_name::default().#field_name).unwrap()))` on every property of the generated schema.

I am using utoipa to generate schemas for structs with many default values set in `impl Default`, so this would be very useful to prevent repetition.

**Comment by cwatson-blackrock** [comment]
Thanks for the feedback!

If you would like this feature implemented, I'd be happy to put in a PR.

I'm not too sure what the cleanest approach would be however, so I would welcome any guidance. Let me know if you are interested in this, and if so I can share my current (non-working :)) idea.

**Comment by juhaku** [comment]
Sure, all contributions are very welcome. :slightly_smiling_face: 

I am confident that this would be something that others would also like to have. The implementation should be related to the `components/schema.rs`, `components/schema/features.rs` and `components/features.rs` files. For example in the `components/schema.rs` file in line 416 we are adding whatever features exist on NamedFieldStruct to the NamedFieldStruct generated schema. Features are the attributes supported by structs and enums and fields.
https://github.com/juhaku/utoipa/blob/43d345701fce6843c8436ff3a896f2cf278b9295/utoipa-gen/src/component/schema.rs#L416-L418

What needs to be achived, is to enhance the `Default` feature to accept a `TokenStream` from `Default::default()` method call of the type itself, when either `#[serde(default)]` or `#[schema(default)]` is provided.

Tests related to the ToSchema schema are located at `utoipa-gen/tests/schema_derive_test.rs`.

Please let me know if there is anything else that I can assist with.
