### ISSUE TITLE
Nested generics

### ISSUE THREAD

**Issue by kitzbergerg** [juhaku/utoipa#524]
I have a generic struct like the following:
```rust
#[derive(Debug, Serialize, Deserialize, ToSchema)]
#[aliases(BodyString = Body<String>)]
pub struct Body<T> {
    pub message: String,
    pub data: T,
}
```

I would now like to add a `Vec<String>` as a generic parameter, however something like
```rust
#[derive(Debug, Serialize, Deserialize, ToSchema)]
#[aliases(BodyVecString = Body<Vec<String>>)]
pub struct Body<T> {
    pub message: String,
    pub data: T,
}
```
doesn't seem to work.

I tried
```rust
#[derive(Debug, Serialize, Deserialize, ToSchema)]
#[aliases(BodyVecString = Body<VecString>, VecString = Vec<String>)]
pub struct Body<T> {
    pub message: String,
    pub data: T,
}
```
but that just generates
```json
{
  "data": {
    "data": "string",
    "message": "string"
  },
  "message": "string"
}
```
instead of an array.

Is it possible to have nested generics like `Body<Vec<String>>` (preferably without somehow remotely implementing an alias for Vec)?

**Comment by juhaku** [comment]
I'll need to check this when I get time, hopefully soon. The aliases functionality itself is a bit limited in capabilities thus I would not keep hopes on too high. 

It is quite hard to provide a good way to define generic aliases for schemas without actually manually implementing the type for the alias. 

The feature should be refactored and even perhaps reiterated from design perspective as well however so far I haven't figured out a good way to implement aliases.

**Comment by juhaku** [comment]
@kitzbergerg I refactored the aliases support a bit and now it should support nested generics. You can see it here #546. If you like to test it out please do.

**Comment by kitzbergerg** [comment]
Great it works just like in my second example.
