### ISSUE TITLE
Derive URL path form handler to avoid declaring it twice (axum)

### ISSUE THREAD

**Issue by lcmgh** [juhaku/utoipa#537]
Hi!

I think it is quite error prone when the URL of an API endpoint has to be declared twice.

```rust
let app = Router::new()
    .route("/users", post(create_user))
```

```rust
/// Create new user
#[utoipa::path(
    post,
    path = "/users",
    request_body = CreateUser,
    responses(
        (status = 201, description = "Create user", body = [String])
    )
)]
pub async fn create_user(
    // this argument tells axum to parse the request body
    // as JSON into a `CreateUser` type
    Json(payload): Json<CreateUser>,
) -> (StatusCode, Json<User>) {
   // .. 
}
```

Could we add an option to make utoipa derive it from the API handler declaration? If that is possible I can also imagine that the Method (GET, POST) and even the output schema can be derived to avoid boilerplate. 

Thanks!

**Comment by juhaku** [comment]
There is now coming up implementation for this to reduce the duplicate endpoint registration. Currently in experimenting phase #991
