### ISSUE TITLE
`impl ToSchema` for primitive types?

### ISSUE THREAD

**Issue by cwatson-blackrock** [juhaku/utoipa#539]
In short: Are there any plans to allow something like this?

```rust
let schema = <u32 as utoipa::ToSchema>::schema()
```
---

For context, given a similar setup to the [ToSchema trait example](https://docs.rs/utoipa/latest/utoipa/trait.ToSchema.html#examples), it would be very useful to be able to construct the schema for `Pet` with:

```rust
utoipa::openapi::ObjectBuilder::new()
    .property(
        "id",
        u64::schema(),
    )
...
```

I am doing something similar to that (using the various Builders instead of macros to define the paths in my schema) and my solution so far has been to define my own trait to build the schema for simple types.
However, I am basically re-implementing logic that is already in `utoipa-gen`, which isn't a great approach in terms of future-proofing.

**Comment by juhaku** [comment]
I actually planned to have this implemented for primitives and certain known types like `Vec` and maps. It just seems that I have forgotten about this. :sweat_smile: This is for sure something useful. I'll add this to the board so it can be tracked.

**Comment by juhaku** [comment]
@cwatson-blackrock any comments for the draft implementation? Thing I am wondering whether the implementation for `Vec`, `Option<T>` and maps are superfluous? Especially because they will get implicitly inlined schema. However that might not be the case or requirement wanted by the user.

**Comment by juhaku** [comment]
I left in place, and instead added some more, they might come handy when creating types for aliases. I need to investigate possibilities, becuase the current `#[aliases(...)]` attribute on `ToSchema` is somewhat limited.

**Comment by cwatson-blackrock** [comment]
That was a quick turnaround, thank you! From some quick testing it seems to work well at least with my application and I have been able to replace most of my manual definitions with PartialSchema::schema().

**Comment by juhaku** [comment]
You are wecome, that's good to hear.
