### ISSUE TITLE
Type Aliases in OpenApi: Resolver error

### ISSUE THREAD

**Issue by AnatolyBuga** [juhaku/utoipa#547]
My struct has a field which is a type alias.
```rust
use serde::Deserialize;
use serde::Serialize;

type MeeasureName = String;

pub fn example() {
    ()
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash, utoipa::ToSchema)]
#[serde(tag = "type")]
pub struct AggregationRequest {
    pub name: MeeasureName,
    pub measures: Vec<(String, String)>
}
```

I expose this struct to OpenApi like so:
```rust
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Ultima BI"
    ),
    paths(
        routers::execute
    ),
    components(
        schemas(AggregationRequest)
    ),
    tags(
        (name = "Ultima BI", description = "Ultimate Business Intellegence endpoints.")
    ),
)]
pub(crate) struct ApiDoc;
```

What I see in the Swagger UI(ignore irrelevant stuff):
![image](https://user-images.githubusercontent.com/60788447/228332412-ffa12b93-67be-4878-9a89-b2e19414eab5.png)

**Comment by AnatolyBuga** [comment]
Actually, this answers the question I think:
https://github.com/juhaku/utoipa/issues/429

**Comment by juhaku** [comment]
@AnatolyBuga Yes, that basically was the answer until now. There is now coming a new PR which adds global type aliases for `utoipa` #1048.
