### ISSUE TITLE
Failed to resolve `serde_json` in `3.2.0`

### ISSUE THREAD

**Issue by ChillFish8** [juhaku/utoipa#550]
It seems within the new version of Utoipa `3.2.0`, we have a breaking change where the derive macro no longer works unless you explicitly include `serde_json` as a dependency because it's seemingly no longer vendored by the macro/utoipa.

Although it's not a *major* issue, it is a breaking change and also a little bit annoying from a dependency management perspective:

```
error[E0433]: failed to resolve: could not find `serde_json` in the list of imported crates
   --> file.rs:172:34
    |
172 | #[derive(Serialize, Deserialize, utoipa::ToSchema)]
    |                                  ^^^^^^^^^^^^^^^^ could not find `serde_json` in the list of imported crates
    |
    = note: this error originates in the derive macro `utoipa::ToSchema` (in Nightly builds, run with -Z macro-backtrace for more info)
  ````

**Comment by juhaku** [comment]
Weird, it actually should work the same as previously, e.g. same as 3.1. I'll check this today later and publish a fix asap.

**Comment by juhaku** [comment]
@ChillFish8 Just created a new project and for me it all works without any other deps.
![Screenshot_20230329_172732](https://user-images.githubusercontent.com/26358664/228571364-3b81c83f-d046-4f30-b481-061d698bfe96.png)

**Comment by juhaku** [comment]
@ChillFish8 I created another release that changes the only place where serde was used differently to any other definition. This makes the code in all places similar to how it was before 3.2.0 release.

If you still encounter this issue, you might want to try to run `cargo update` or / and delete the `utoipa` releated content from `.cargo/registry`.

**Comment by ChillFish8** [comment]
Awesome I'll give it a try and see if it fixes the issue or not

**Comment by juhaku** [comment]
I assume the issue has been resolved. Closing for now, but can be reopened if needed.
