### ISSUE TITLE
Rapidoc UI support

### ISSUE THREAD

**Issue by snaggen** [juhaku/utoipa#554]
Utoipa looks interesting, but it would be nice to have rapidoc ui support, in the same way you have swagger ui support. https://rapidocweb.com/

It should be much simpler, since it just loads some JS.

**Comment by juhaku** [comment]
Sure could be added in future.

**Comment by vikigenius** [comment]
Would definitely love Rapidoc. I prefer it way more than Swagger-UI or ReDoc

**Comment by juhaku** [comment]
RapiDoc support was added in https://github.com/juhaku/utoipa/pull/723 and it has been released to the crates.io.
