### ISSUE TITLE
Construct OpenApi from YAML/JSON

### ISSUE THREAD

**Issue by gliderkite** [juhaku/utoipa#560]
I am in a situation where a am dealing with a number of types that are being defined in eternal crates for which I cannot implement `ToSchema`. I've checked possible workarounds such as those listed in [this open issue](https://github.com/juhaku/utoipa/issues/507#issuecomment-1465007714), but they remain quite verbose, especially if the types in question require to define a significant number of new schemas (for example [GeoJson](https://docs.rs/geojson/latest/geojson/enum.GeoJson.html)).

I'd be great if it was possible to construct a new [OpenApi](https://docs.rs/utoipa/latest/utoipa/openapi/struct.OpenApi.html) object from a yaml/json string/document, which would be much easier to work with.

This would allow, for example, to do things like:

```rust
 ApiDoc::openapi()
   .merge(OpenApiBuilder::parse("<MY_SCHEMA>").unwrap());
```

Even better if this would be also part of other types and reused internally, so that we could for example call also
```rust
ComponentsBuilder::parse("<MY_COMPONENT_SCHEMA>")
```

**Comment by juhaku** [comment]
You have the `components: {}` wrapper in your JSON that is unexpected field. Below is a a working schema.
```rust
let components_json = r#"
{
    "schemas": {
        "GeoJsonObject": {
            "description": "GeoJSon object",
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "Feature",
                        "FeatureCollection"
                    ]
                }
            },
            "required": [
                "type"
            ]
        }
    }
}
"#;

let components = serde_json::from_str::<openapi::Components>(components_json).unwrap();
dbg!(&components);

assert!(!components.schemas.is_empty());
```

**Comment by gliderkite** [comment]
Thanks your example works for `Components` :) I ended up removing all the unsupported fields from the YAML with the GeoJson specification and I can currently use the `Deserialize` trait as it.

**Comment by juhaku** [comment]
> Thanks your example works for `Components` :)

You are welcome
