### ISSUE TITLE
integers and minimum/maximum.etc

### ISSUE THREAD

**Issue by jayvdb** [juhaku/utoipa#565]
https://github.com/juhaku/utoipa/pull/515 had the unfortunate side effect of injecting `0.0` into our schemas for integer types, which is the intent, but it turns out that https://github.com/oxidecomputer/progenitor, which consumes our schemas, doesnt like float values for min/max/etc when the `format:` indicates it is a integer type.
The progenitor error is
```
thread 'main' panicked at 'not clear what we could usefully do here Schema {
    schema_data: SchemaData {
        nullable: false,
        read_only: false,
        write_only: false,
        deprecated: false,
        external_docs: None,
        example: None,
        title: None,
        description: None,
        discriminator: None,
        default: None,
        extensions: {},
    },
    schema_kind: Any(
        AnySchema {
            typ: Some(
                "integer",
            ),
            pattern: None,
            multiple_of: None,
            exclusive_minimum: None,
            exclusive_maximum: None,
            minimum: Some(
                0.0,
            ),
            maximum: None,
            properties: {},
            required: [],
            additional_properties: None,
            min_properties: None,
            max_properties: None,
            items: None,
            min_items: None,
            max_items: None,
            unique_items: None,
            enumeration: [],
            format: Some(
                "int32",
            ),
            min_length: None,
            max_length: None,
            one_of: [],
            all_of: [],
            any_of: [],
            not: None,
        },
    ),
}', progenitor-impl/src/to_schema.rs:550:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It would be nice if utoipa could emit integers for min/max/etc when the format indicates it is an integer type.  I see `Minimum` and friends are using `f64` , so either that needs to change to be a union of f64 and u64, or somewhere later the process  floats like `x.0` would need the `.0` dropped.

**Comment by juhaku** [comment]
It is float due to the JSON schema specification saying that it should be a `number` a.k.a not telling that it it should be an `integer`  as seen here: https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.2.4

**Comment by jayvdb** [comment]
RIght, but '0' is a valid number too, and is a more suitable number than '0.0' in the context of `format: int32` and similar.

**Comment by jayvdb** [comment]
Note progenitor has added a fix for this on their side, however IMO it is still beneficial for utoipa to use integers in the integer content.

**Comment by juhaku** [comment]
> RIght, but '0' is a valid number too, and is a more suitable number than '0.0' in the context of format: int32 and similar.

That is true. It would match better to the context. Right now utoipa considers the spec quite naively by just using number when number is expected. The options for this case could be though and tried out. 

> Note progenitor has added a fix for this on their side, however IMO it is still beneficial for utoipa to use integers in the integer content.

I also noticed. Sure the possibilities for using integer in integer context could be explored.

**Comment by rbuch703** [comment]
@juhaku what about something like #618 as a mitigation?

There are other OpenAPI spec consumers that also refuse to parse float expressions for integer types (for example I'm currently having issues with Python's `openapi_core` package). By omitting decimal zeros, virtually all min/max/multiple values that are specified for integers would become parseable as integers (while still also being valid floats).

**Comment by juhaku** [comment]
Great, this is something that has been in back of my head that should be done but I haven't just had the bandwidth.
