### ISSUE TITLE
schema creation fails when field has a module-qualified type (at least when using axum)

### ISSUE THREAD

**Issue by johnperry-math** [juhaku/utoipa#569]
## Version

latest

## Description

See subject. (Sorry if I'm using the wrong terminology for "module-qualified type".)

## Expected behavior

Schemas should be created even for module-qualified types.

## MWE
Add the following to the utoipa-axum example:
```
mod commentary {
    use utoipa::ToSchema;

    #[derive(ToSchema, serde::Serialize, serde::Deserialize, Clone)]
    pub(super) struct Commentary {
        yada_yada: String,
    }
}
```
then the following import to `mod todo`:
```
use super::commentary;
```
and then the following field to `struct Todo`:
```
        commentary: commentary::Commentary,
```
Everything compiles and runs happily, but schema creation has failed. If you open the first endpoint or the `Todo` schema you get a red box listing the following error:

> # Errors
>     Resolver error at paths./todo.get.responses.200.content.application/json.schema.items.properties.commentary.$ref
>     Could not resolve reference: Could not resolve pointer: /components/schemas/commentary.Commentary does not exist in document

A workaround is to `use super::commentary::Commentary` but this is suboptimal for large projects where, for instance, you may be importing different `Coordinate`s from different crates.

**Comment by johnperry-math** [comment]
Er... the above workaround does not actually seem to work in this case; I'm not sure why, but I still get the red Errors box. In my actual project I have a similar workaround and that works fine.

**Comment by juhaku** [comment]
For this there is a need to use `as = ` attribute to alternate the name of the type to be derived. #230 , #435 E.g. we could use the `as` to rename to the commentary type.
```rust
#[derive(ToSchema)]
#[as = commentary::Commentary]
sturct Commentary {
  value: String,
}

// .. in another type and module we can use the module path now.
#[derive(ToSchema)]
struct Foo {
  comments: commentary::Commentary,
}
```

**Comment by juhaku** [comment]
> Do you mean this?

Yes

**Comment by johnperry-math** [comment]
The real-world usage prompted a hiccup, because some crates import the type, and others import only its crate. To illustrate, suppose I modify the `Todo` struct as follows:
```
    #[derive(Serialize, Deserialize, ToSchema, Clone)]
    pub(super) struct Todo {
        id: i32,
        #[schema(example = "Buy groceries")]
        value: String,
        commentary: commentary::Commentary,
        more: Commentary, // HERE
        // ...
    }
```
Now it's the un-qualified `Commentary` that generates an error. However! this is easily solved using the `value_type` option:
```
    #[derive(Serialize, Deserialize, ToSchema, Clone)]
    pub(super) struct Todo {
        id: i32,
        #[schema(example = "Buy groceries")]
        value: String,
        commentary: commentary::Commentary,
        #[schema(value_type = commentary::Commentary)]
        more: Commentary, // HERE
        // ...
    }
```
...and I can work with this. Thank you!
