### ISSUE TITLE
Accept HashMap<(), ()> as object

### ISSUE THREAD

**Issue by leon3s** [juhaku/utoipa#576]
Hey i'm generating structures from the docker openapi spec and for some field they use `HashMap<(), ()>` for example:
```rust
volumes: HashMap<String, HashMap<(), ()>>
```
To define an empty object [see](https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerCreate) for volumes as example.

But if i want to convert it back using utoipa i get the following error:
```console
error[E0277]: the trait bound `AdditionalProperties<Schema>: From<Schema>` is not satisfied
    --> codegen/swagger/src/models.rs:6637:39
     |
6637 | #[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
     |                                       ^^^^^^^^^^^^^^^^ the trait `From<Schema>` is not implemented for `AdditionalProperties<Schema>`
     |
     = help: the following other types implement trait `From<T>`:
               <AdditionalProperties<Schema> as From<()>>
               <AdditionalProperties<Schema> as From<ObjectBuilder>>
               <AdditionalProperties<Schema> as From<utoipa::openapi::Ref>>
     = note: required for `Schema` to implement `Into<AdditionalProperties<Schema>>`
note: required by a bound in `ObjectBuilder::additional_properties`
```

I tried to do it, but i'm not familiar enough with macro

**Comment by juhaku** [comment]
In docker OpenAPI spec the `Volumes` field is defined as follows:
```yaml
Volumes:
  description: |
    An object mapping mount point paths inside the container to empty
    objects.
  type: "object"
  additionalProperties:
    type: "object"
    enum:
      - {}
    default: {}
```

But `utoipa` will render the volumes differently becuase of the unit type `()`. Unit type is by default rendered as `null` with serde and `utoipa` will create schemas for both types of the `HashMap` by the way of using `additionalProperties` resulting strictier interpretation of OpenAPI schema than what is defined in the docker OpenAPI schema.
```json
{
    "properties": {
        "volumes": {
            "additionalProperties": {
                "additionalProperties": {
                    "type": "object",
                    "default": null,
                    "nullable": true,
                },
                "type": "object"
            },
            "type": "object"
        },
    },
    "required": [
        "volumes"
    ],
    "type": "object"
}
```

I created a PR #580 that fixes the support. However it does not render exactly 1 to 1 with the docker OpenAPI spec. Most fundamentally the `additionalProperties` will look different. after serialization and re-deserialization.

**Comment by leon3s** [comment]
That's good enought! Thx for your great for on the library!
