### ISSUE TITLE
How do I add additional dictionary property equivalent to json-schema ? 

### ISSUE THREAD

**Issue by afidegnum** [juhaku/utoipa#594]
I have the following struct
```rs
#[derive(Serialize, Debug, ToSchema, Deserialize, Default)]
pub struct Name{   
   #[schema(example = "email@email.com")]  
    pub id: email,  
    pub name: String,
}
```
I would like to extract the schema in order to build a form, in jscon-schema-form, there is an additional property UI-Schema, 
is it possible to add an extra property to the current struct? if not possible, what do you suggest so i can have something like: 

```rs
#[derive(Serialize, Debug, ToSchema, Deserialize, Default)]
pub struct Name{   
   #[schema(example = "email@email.com")]  
   #[schema(ui = json!{"widget": "email-form", "pattern": "email-regex"})]  
    pub id: email,  
  #[schema(ui = json!{"widget": "textarea", "validation": "A-Za-z"})]  
    pub name: String,
}
```
I tried using the `default `and `example `attribute of the schema but  would like the custom `ui` property to be available to generate a related form. 
What do  you suggest?

**Comment by juhaku** [comment]
In general there are two ways to accomplish this.
1. Either you define the field itself on the struct.
    ```rs
    #[derive(Serialize, Debug, ToSchema, Deserialize, Default)]
    pub struct Name{   
       #[schema(example = "email@email.com")]  
        pub id: email,  
        pub name: String,
        #[schema(value_type = Value)] // <-- or you can use value_type to override the type
        pub ui: String, // <-- type should be any type you want to have it
    }
    ```
    You can use `value_type` to override the type for the field, and it supports either `Object` or `Value` virtual types. Object creates `type: object` Schema Object. and `Value` creates "AnyType" which basically accepts any JSON. 
    
    Here is an example of Value in use https://github.com/juhaku/utoipa/blob/master/examples/raw-json-actix/src/main.rs
    
    Here is docs for ToSchema value type https://docs.rs/utoipa/latest/utoipa/derive.ToSchema.html#unnamed-field-struct-optional-configuration-options-for-schema
2. Or you create the schema manually for the struct.

    ```rust
    struct Name {
        id: String,
        name: String,
    }
    
    impl<'s> ToSchema<'s> for Name {
        fn schema() -> (&'s str, RefOr<Schema>) -> {
            let o = ObjectBuilder::new()
                .property("id", String::schema())
                .required("id")
                .property("name", String::schema()
                .required("name")
                .property("ui", String::schema()) // <-- or any other schema you want it to have
                .required("ui").build()
                
            ("Name", o)
        }
    }
    ```
    
    But this way the schema does not match to the struct.

**Comment by juhaku** [comment]
Closing due inactivity
