### ISSUE TITLE
Wrong sorting in the UI

### ISSUE THREAD

**Issue by EvilWatermelon** [juhaku/utoipa#597]
Hi,

I have a problem with the depiction of my URIs in the UI. I want to sort them in `Data` and `Auth` but they are sorted in `data_controller` and `auth_controller`.

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/29424277/234533300-513d6a5d-78e0-4390-bc77-372aee4b922b.png">

```rust
#[derive(OpenApi)]
#[openapi(
    paths(
        data_controller::get_user_data,
        data_controller::get_user,
        data_controller::get_all_statistics,
        data_controller::get_specific_statistics,
        auth_controller::signup,
    ),
    components(
        schemas(
            data_controller::Data, 
            data_controller::ErrorResponse,
            auth_controller::UserData
        )
    ),
    tags(
        (name = "Data", description = "All endpoints to show the collected data."),
        (name = "Auth", description = "All endpoints for user and access management.")
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;
```
Do I have to fix the attributes which above the `ApiDoc` struct or the documentation attributes above my URI functions:

```rust
#[utoipa::path(
    context_path = "/dashboard",
    responses(
        (status = 200, description = "Endpoint to get all data from all devices for the dashboard.", body = Data)
    )
)]
#[get("/statistics/all")]
pub fn get_all_statistics() -> Json<Vec<String>> {
    let cache: RedisCache = RedisCache::default();
    let vec: Vec<String> = vec![cache.get_str("statistics").unwrap()];

    Json(vec)
}
```
I'm using `rocket 0.5`

**Comment by pongsakornsemsuwan** [comment]
I also run into this problems. I think the cause of the problem is that we use [BTreeMap](https://docs.rs/utoipa/latest/utoipa/openapi/path/struct.Paths.html) to store paths with path name (`/auth/signup`, `/dashboard/stats`/ ...) as a key. 
BTreemap will always maintain order by keys hence when we iterate over it, it's in alphanumeric order or path name?

**Comment by EvilWatermelon** [comment]
I don't have a specific order of the path names.

**Comment by dayvejones** [comment]
Same problem with axum

**Comment by EvilWatermelon** [comment]
As @pongsakornsemsuwan said, I had to change the crate name to the keyword to get the correct sorting.

**Comment by juhaku** [comment]
@EvilWatermelon 

There is also coming a new feature in next release `preserve_path_order` that can be enabled if seen valuable. That will do the same for paths as the `preserve_order` does for `ToSchema` derived struct fields which is keeping the order same as they are being declared. 

 You can already use the feature if you use the **master** as the version in your `Cargo.toml` file. 

Also to map your handler function correctly to the **tag** you must declare the tag on `#[utoipa::path(...)]` as well. The default `tag` will be the path to the registered handler e.g. `data_controller` as seen in the pictures above.
```rust
#[derive(OpenApi)]
#[openapi(
    paths(
        data_controller::get_user_data,
        data_controller::get_user,
        data_controller::get_all_statistics,
        data_controller::get_specific_statistics,
        auth_controller::signup,
    ),
    components(
        schemas(
            data_controller::Data, 
            data_controller::ErrorResponse,
            auth_controller::UserData
        )
    ),
    tags(
        (name = "Data", description = "All endpoints to show the collected data."),
        (name = "Auth", description = "All endpoints for user and access management.")
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;

#[utoipa::path(
    context_path = "/dashboard",
    tag = "Data", // <-- ........ see here
    responses(
        (status = 200, description = "Endpoint to get all data from all devices for the dashboard.", body = Data)
    )
)]
#[get("/statistics/all")]
pub fn get_all_statistics() -> Json<Vec<String>> {
   // ... 
}
```

**Comment by EvilWatermelon** [comment]
Ok, thanks! I will wait for the new stable release.
