### ISSUE TITLE
How do i display only the url without the UI path?

### ISSUE THREAD

**Issue by afidegnum** [juhaku/utoipa#598]
With `swagger-ui` I would like to return only the openapi schema without the UI, 

the following code still returns the ui interface. 
` SwaggerUi::new("").url("/api-docs/openapi.json", openapi.clone()),
`

**Comment by juhaku** [comment]
For such case you need to serve it through an enpoint as you would do with any other content. And also with that you do not need the `utoipa-swagger-ui` library to be there.
```rust
async fn get_api_doc(....) -> Json<utoipa::openapi::OpenApi> {
    let doc = // .... load the doc somewhere or from fn arguments
    Json(doc)
}
```

**Comment by afidegnum** [comment]
Can you please give an example? i'm a bit confused.

**Comment by juhaku** [comment]
Sure,

For example if you take a look at the `warp` example you can find that the  apidoc.json is served via regular http endpoint handler (whatever handles the incoming requests). https://github.com/juhaku/utoipa/blob/489ddd663051a578e9285f5f4b5d87c0f626d6c0/examples/todo-warp/src/main.rs#L46-L48

Or with `actix_web` same example might look something like this:
```rust
#[get("/api-docs/openapi.json")]
async fn get_api_doc(apidoc: Data<OpenApi>) -> impl Responder {
    let doc = apidoc.lock().unwrap();
    HttpResponse::Ok().json(doc)
}
```

If you want to return only the `openapi` schema then you need to create a custom endpoint for it according to the framework of your choise. You cannot use the `SwaggerUi` type without exposing the Swagger UI to the public. 

Does this help? Or have I understood your question totally wrong?

**Comment by afidegnum** [comment]
Thanks a lot.

**Comment by afidegnum** [comment]
Sorry for bothering again, 

let's say I have the following struct:

```rs
/// Task to do.
#[derive(Serialize, Deserialize, ToSchema, Clone, Debug)]
#[schema(title = "Register")]
pub(super) struct Todo {
    /// Unique id for the todo item.
    #[schema(example = 1)]
    id: i32,
    /// Description of the tasks to do.
    #[schema(example = "Remember to buy groceries")]
    value: String,
    /// Mark is the task done or not
    checked: bool,
}

```
I noticed I cannot add a `description` to the Struct. 
What I wanted to do is obtain a custom schema label which would be used at the front end from different request paths. 

so if using actix, on `#[post("/todo")]` I would have a _TodoAdd_ and #[get("/todo")] I can have _Todo_ but posting a form data should point to the same struct.
also I would like to have a custom label to each of the request pats. using description seems to be restrictive, I couldn't make use of the `summary` feature of the OpenAPI Specification. 

can you please adivse?

**Comment by EvilWatermelon** [comment]
Does this also work with rocket?

**Comment by juhaku** [comment]
Closed due inactivity.
