### ISSUE TITLE
[Feature Request] Serialize paths in order of openapi paths definition

### ISSUE THREAD

**Issue by Chethan-rao** [juhaku/utoipa#602]
In some use-cases, the order in which paths are defined in the OpenAPI specification is significant, especially when certain paths must be included first due to their higher value over other paths. However, the current implementation of serializing OpenAPI paths alphabetically may not always be the optimal choice.

To address this, I propose adding an option to serialize OpenAPI paths in the order defined in the specification, rather than alphabetically. This would allow users to better control the order of paths and ensure they are sent in the appropriate order for their specific use-case. Issue is similar to [#428](https://github.com/juhaku/utoipa/issues/428).

### **Feature Description** 
I would like to suggest an improvement in the OpenAPI paths field where the paths are documented in the same order as they appear in the specification. 
I would appreciate your feedback on this suggestion. If you believe this change would be beneficial, I have already made the necessary changes and tested it, I would be happy to create a pull request. Please let me know your thoughts on this matter.

**Comment by juhaku** [comment]
Sure, please open a pull request and let's get the show on the road. I belive it it would be in similar fashion via some feature flag that will enable this behavior.
