### ISSUE TITLE
Custom entries for the path items

### ISSUE THREAD

**Issue by afidegnum** [juhaku/utoipa#605]
How do i write a custom `summary` and `description` for `paths` and `request_body`. 

```rs
[utoipa::path(
   summary = "Registration",
    request_body(content = CreateUser, summary="Add User", description = "Create User", content_type = "application/json",  example = json!({"id": 1, "name": "bob the cat"})),
    )
)]

```
This doesn't seems to work as the said parameters are not available using actix. 

Is there also a way of passing custom headers based on this [specification? ](https://swagger.io/docs/specification/describing-parameters/)

**Comment by juhaku** [comment]
The description and summary is resolved from the doc comment above the function. However now there is a PR to support description and summary overriding via attributes https://github.com/juhaku/utoipa/pull/948. 

Custom headers are parameters the same way as they are in the OpenAPI specification. At the moment the headers can be defined with tuple style parameter definition on #[utoipa::path(...)]` attribute macro. https://docs.rs/utoipa/latest/utoipa/attr.path.html#params-attributes. E.g.
```rust
#[utoipa::path(
  params(
    ("x-custom-header" = String, Header, description = "Custom header that is mandatory")
  )
)]
```
