### ISSUE TITLE
Is it possible to add an Authorize button?

### ISSUE THREAD

**Issue by ovidiu-ionescu** [juhaku/utoipa#606]
I need to add a header with the JWT token for authentication. Normally, that's an Authorize button that opens a dialog which can take a token in a text field.

How can I do that with utoipa?

**Comment by ovidiu-ionescu** [comment]
After reading a bit of the source, I don't think it can be done only with macros. The only way seems to be the one in the examples, where you code a SecurityAddon in Rust and declare it in the proc macro as a modifier.

**Comment by juhaku** [comment]
Yes, that is true, it cannot be done just with macro attributes. The security schema need to be added manually to the OpenApi via code. This can either be done with `Modifier` trait or just directly mutating the `OpenApi` type after calling `openapi()` method on struct derived from `#[utoipa(OpenApi)]`. 

The button comes to the UI naturally when a security scheme is added to the OpenAPI doc and when matching security scheme requirement is added to the path (OpenAPI path handler) or globally to the whole API.

**Comment by GetcharZp** [comment]
> Yes, that is true, it cannot be done just with macro attributes. The security schema need to be added manually to the OpenApi via code. This can either be done with `Modifier` trait or just directly mutating the `OpenApi` type after calling `openapi()` method on struct derived from `#[utoipa(OpenApi)]`.
> 
> The button comes to the UI naturally when a security scheme is added to the OpenAPI doc and when matching security scheme requirement is added to the path (OpenAPI path handler) or globally to the whole API.

Excuse me, do you have any relevant sample code?
