### ISSUE TITLE
Loading the UI with rocket in an own function

### ISSUE THREAD

**Issue by EvilWatermelon** [juhaku/utoipa#611]
Hi,

is it possible to load the UI in a separated function instead of:

```rust
.mount("/",
            SwaggerUi::new("/<_..>")
                .url("/api-doc/openapi.json", swagger::ApiDoc::openapi()))
```
That I can go like this:

```rust
#[get("/swagger-ui/<_..>")]
pub fn get_ui() {
       //some code 
}
```

Because the first code snippet gives me an error I already showed here #482 [this answer](https://github.com/juhaku/utoipa/issues/482#issuecomment-1430798036)

**Comment by EvilWatermelon** [comment]
I switched to `actix-web` and `/swagger-ui` works there

**Comment by juhaku** [comment]
Hey, it should be possible according to the rocket 0.4 hello world example. https://github.com/juhaku/utoipa/blob/489ddd663051a578e9285f5f4b5d87c0f626d6c0/examples/rocket-0_4-hello/src/main.rs#L24-L45
