### ISSUE TITLE
Generate the schema of a Structure as a primitive type ( like impl_partial_schema_primitive! )

### ISSUE THREAD

**Issue by rxdiscovery** [juhaku/utoipa#615]
Hello,
Thank you for this great work, Utoipa is one of the most important libs for the realization of an Enterprise Web Services project.

I use it since a long time, but now I met a little blockage, I want a struct to be considered as a primitive type, like String, and without having to add it to the definition `#[openapi(.. components(schemas(...)), .. ]`

I tried with `impl<'__s, 'a> utoipa::ToSchema<'__s> for ID<'a, 0>` but it's still considered as an object , and if I rename it I get this error on Swagger-ui  :  `Could not resolve reference: Could not resolve pointer: /components/schemas/ID does not exist in document.`
I want the structure to be considered as a String, even if it contains fields, as this internal macro does  :  `impl_partial_schema_primitive!`

Here is a simplified example :
```rust
#[derive(ToSchema, Serialize, Deserialize, Default, Clone, Debug)]
struct ID {
     salt : String,
     value : String,
}

#[derive(ToSchema, Serialize, Deserialize, Default, Clone, Debug)]
struct TestDTO {
    #[serde(rename = "id")]
    id : ID,
    #[serde(rename = "name")]
    name : String,
}
```
I want it to generate this : 
```json
 "TestDTO": {
        "type": "object",
        "required": [
          "id",
          "name"
        ],
        "properties": {
          "id": {
            "type": "string"   <------------------------------
          },
         "name": {
            "type": "string"
          },
```
         

Thank you in advance for your help.

**Comment by juhaku** [comment]
Hey,

The only way at the moment to get that behavior is to use `value_type = ...` attribute above the field of the struct. 
```rust
#[derive(ToSchema, Serialize, Deserialize, Default, Clone, Debug)]
struct ID {
     salt : String,
     value : String,
}

#[derive(ToSchema, Serialize, Deserialize, Default, Clone, Debug)]
struct TestDTO {
    #[serde(rename = "id")]
    #[schema(value_type = String)] // ... <-- here
    id : ID,
    #[serde(rename = "name")]
    name : String,
}
```

It is not possible to declare at struct level that it suppose to be a string because the referenced fields only knows the name of the type.

**Comment by rxdiscovery** [comment]
Thank you for your quick answer, so if I understood correctly we can't do it globally as for the primitives, but we have to do it for each field declared manually ?

**Comment by juhaku** [comment]
> Thank you for your quick answer, so if I understood correctly we can't do it globally as for the primitives, but we have to do it for each field declared manually ?

Yes. The reason is that when `utoipa` is looping through the fields of a struct, it knows the type of the field but it cannot know if the type should be rendered as something else. 

Though there might be possibility to implement this kind of global support but that would be a breaking change to the library, if even possible.

**Comment by rxdiscovery** [comment]
Thank you so much,  I will do as you suggested :+1:

**Comment by juhaku** [comment]
Anytime :slightly_smiling_face:
