### ISSUE TITLE
`response()` attribute for IntoResponses macro does not separate arguments with commas on enum variants

### ISSUE THREAD

**Issue by emanguy** [juhaku/utoipa#629]
Hey there! This crate seems really promising and I'd love to help out if I could, I'm just not super familiar with writing proc_macros.

I was trying to derive IntoRespnoses on an enum when I realized I was getting compiler errors passing arguments to `response()` on an enum variant. The following code produces an `identifier expected` error on utoipa 3.3.0 with the "axum_extras" feature (and to my understanding this should be valid code based on the "into_response" documentation):

<details>
<summary>Code that produces unexpected error</summary>

```rust
/// Response type that wraps database errors and turns them into [BasicErrorResponse]s
#[derive(utoipa::IntoResponses)]
pub enum DbErrorResponse {
    /// The requested entity could not be found
    #[response(
        status = StatusCode::NOT_FOUND,
        example = json!(
        {
            "error_code": "not_found",
            "error_description": "The requested entity could not be found.",
            "extra_info": null
        }
    ))]
    NoResults,

    /// There was an issue communicating with the database
    #[response(
        status = StatusCode::INTERNAL_SERVER_ERROR,
        example = json!(
        {
            "error_code": "internal_error",
            "error_description": "Could not access data to complete your request",
            "extra_info": null
        }
    ))]
    QueryFailure,
}
```

</details>

This is the error produced by the compiler on Rust 1.68.1:

```
error: expected identifier
  --> src/routing_utils.rs:32:39
   |
32 |         status = StatusCode::NOT_FOUND,
   |                                       ^
```

Based on this, I tried removing the commas between `response()` arguments, and somehow that ended up compiling:

<details>
<summary>Working version of above code</summary>

**Notice that the commas after `status` are removed:**

```rust
/// Response type that wraps database errors and turns them into [BasicErrorResponse]s
#[derive(utoipa::IntoResponses)]
pub enum DbErrorResponse {
    /// The requested entity could not be found
    #[response(
        status = StatusCode::NOT_FOUND
        example = json!(
        {
            "error_code": "not_found",
            "error_description": "The requested entity could not be found.",
            "extra_info": null
        }
    ))]
    NoResults,

    /// There was an issue communicating with the database
    #[response(
        status = StatusCode::INTERNAL_SERVER_ERROR
        example = json!(
        {
            "error_code": "internal_error",
            "error_description": "Could not access data to complete your request",
            "extra_info": null
        }
    ))]
    QueryFailure,
}
```

</details>

Reading through the code of the `utoipa_gen` crate, I would guess that the issue happens somewhere around here: https://github.com/juhaku/utoipa/blob/970e10f4203edc8af68c78a009dbb8dc935703bb/utoipa-gen/src/path/response/derive.rs#L159

but again, I don't have that much procedural macro experience. Let me know if you need more info or if I can contribute in any way!

**Comment by emanguy** [comment]
Never mind, I think I figured it out. We're not parsing a comma here after we ingest the "status" attribute: https://github.com/juhaku/utoipa/blob/970e10f4203edc8af68c78a009dbb8dc935703bb/utoipa-gen/src/path/response.rs#L519

I'll put up a PR shortly.

**Comment by juhaku** [comment]
Yeah, seems like it is being missed from there. 

Please do, all contributions are welcome.  :slightly_smiling_face:
