### ISSUE TITLE
oas3-valid-oas-content-example 'example' property should match exactly one schema in oneOf

### ISSUE THREAD

**Issue by Weshnaw** [juhaku/utoipa#63]
I'm not very fluent in the OpenAPI specifications, so I wanted to see if I was doing something wrong.

Using the example code, but saving the json to a file instead of using the swagger ui

When adding the OpenAPI json into insomnia it reports the error for each of the ErrorResponse examples:
oas3-valid-oas-content-example 'example' property should match exactly one schema in oneOf

![image](https://user-images.githubusercontent.com/3748858/162244285-239e1b03-e147-41cb-842a-2c9a1c3373d7.png)

**Comment by juhaku** [comment]
Interesting. Actually it should be valid schema. For what I have used to double check the spec is correct is this tool: https://editor.swagger.io/. I pasted the schema from Todo example there and it did not error out anything there. 

What the error is saying is that the `example` field does not match to a `property` in `TodoErrorResponse` component in spec.
Do you have a typo somewhere there? Or have you changed the types somehow?

The original schema looks like this:
![image](https://user-images.githubusercontent.com/26358664/162256268-8a283994-b8de-4bbf-b64e-19acac62dd10.png)
And the matching `ErrorResponse` component:
![image](https://user-images.githubusercontent.com/26358664/162256428-2c6b4f4d-742f-43aa-9083-5f0e628cdfbb.png)

**Comment by Weshnaw** [comment]
I changed the ErrorResponse struct name to TodoErrorResponse, but as far as I can see everything else is correct.

using https://editor.swagger.io/ and the OpenAPI.json I generated; there doesn't appear to have any errors, so this could just be a case of Insomnia being hyper specific/incorrect in verifying the OpenAPI document.

**Comment by juhaku** [comment]
Yeah.. Okay.. very weird indeed. I guess it is anomaly in the tool itself. Since anyhow the document outputs correct info. For example if there was an actual error in the spec itself the Swagger UI would complain or at least not work the expected way.

**Comment by Weshnaw** [comment]
Unrelated I did just notice what I think is a typo:
https://github.com/juhaku/utoipa/blob/master/examples/todo-actix/src/todo.rs#L63'
Unauhtorized -> Unauthorized

**Comment by juhaku** [comment]
Thanks for noticing. :bow:  Need to fix it.
