### ISSUE TITLE
Accept const &str as argument to path and context_path in the path macro

### ISSUE THREAD

**Issue by Nahuel-M** [juhaku/utoipa#632]
Currently, only string literals are accepted in the path attribute macro for the `path` and `context_path` fields:
```rust
#[utoipa::path(get, path = "/operation")]
fn operation() {}
``` 

I'm trying to get a different path depending on whether I'm building locally or on a server, which I would like to pass with environment variables:

```rust
const CONTEXT_PATH: &str = env!("CONTEXT_PATH");
#[utoipa::path(get, path = "/operation", context_path=CONTEXT_PATH)]
fn operation() {}
``` 
However, this doesn't currently work, since string literals are the only accepted input for path and context_path.

Is this the best way to approach this issue. and is this a lot of work to implement?

Thanks in advance!

**Comment by juhaku** [comment]
Hey,

This is actually related to this https://github.com/juhaku/utoipa/issues/518. I belive this shouldn't be a too big of an issue and frankly quite easy to implement. Only one thing need to be careful with, that is when implemented, the support would not be added to too many places.

I am planning to have this done sometime in future. 

Currently the only feasible wayt around this is to manually implement the paths but that is a lot of cumbersome work at the moment. But then macros should be leveraged there as well. One could also change the path with `Modifier` but that would also be somewhat clumsy.

**Comment by Nahuel-M** [comment]
Hi,

I think you're right. This is definitely the same issue. Are you accepting PR's? What scope would I have to cover to make an addition?

Thanks!

**Comment by juhaku** [comment]
Sorry for late reply, sure though there is a PR coming soon that provides this implementation. The support came out relatively easily.
