### ISSUE TITLE
Using actix_web HttpResponseBuilder as a path response body

### ISSUE THREAD

**Issue by EvilWatermelon** [juhaku/utoipa#636]
Hi,

I want to use `responses(status = 200 ... body = actix_web::response::builder::HttpResponseBuilder`. Is it possible to use it or do I have to use a primitive data type instead? I'm getting a `ResolverError`.

**Comment by juhaku** [comment]
> I want to use `responses(status = 200 ... body = actix_web::response::builder::HttpResponseBuilder`. Is it possible to use it or do I have to use a primitive data type instead? I'm getting a `ResolverError`.

At the moment you can use type that resolves to a Schema. E.g. The catch is, that when macros are evaluated, they only have access to whatever is provided to `body = ....` attribute as value. The macros are unaware types and how they would resolve when application is run. That said with above `HttpResponseBuilder` the utoipa would only know that response is some type of `HttpResponseBuilder` but it would not have a way to find what kind of response it actually would be.
