### ISSUE TITLE
generate type: object

### ISSUE THREAD

**Issue by incker** [juhaku/utoipa#642]
Hello!

If i need to generate someting like 

    lg:
        type: object

My rust code:

    #[derive(Serialize, Deserialize, ToSchema, Debug, Clone)]
    pub struct Layout {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub lg: Option<serde_json::Value>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub md: Option<serde_json::Value>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub sm: Option<serde_json::Value>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub xs: Option<serde_json::Value>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub xxs: Option<serde_json::Value>,
    }

My swagger generated code:

    "layout": {
        "lg": "string",
        "md": "string",
        "sm": "string",
        "xs": "string",
        "xxs": "string"
    },

Thank you !

**Comment by JMLX42** [comment]
Answer here IMHO: https://github.com/juhaku/utoipa/issues/383#issuecomment-1335152273
