### ISSUE TITLE
How do I add custom x-properties

### ISSUE THREAD

**Issue by coffeebe4code** [juhaku/utoipa#643]
I am using the actix example essentially.

We have custom requirements at our company to add several extra fields, usually for certain blocks. like the server block, or extra x-properties in the info block.

```rs
#[utoipa::path(
    get,
    path = "/echo",
    responses(
        (status = 200, description = "echos back all headers and request body in response"),
    ),
)]
#[get("/echo")]
```

```rs
    #[derive(OpenApi)]
    // ?insert more props on openapi?
    #[openapi(paths(echo))]
    struct ApiDoc;

    let mut openapi = ApiDoc::openapi();
    // ? insert more props on openapi?
    let mut file = std::fs::File::create("openapi.json")?;
    file.write_all(openapi.to_pretty_json().unwrap().as_bytes())?;
```

I would much rather build this file at compile time as well, but I can manage that on my end if there are no exposed means from this project.

Great freaking project btw, this all worked perfectly out of the box very quick to set up.

**Comment by juhaku** [comment]
In short, at the moment `x-properties` are not supported and there is no build in way to insert extension properties to the schema. 

Perhaps this is something that could be explored in future, and of course PR:s are welcome. :slightly_smiling_face:

**Comment by rlukata** [comment]
@coffeebe4code You can build the server object using [the modify trait](https://docs.rs/utoipa/latest/utoipa/trait.Modify.html).

**Comment by lucasgranberg** [comment]
https://github.com/juhaku/utoipa/pull/763
Are these the same x-properties? My PR is for openapi extensions

**Comment by juhaku** [comment]
@lucasgranberg Yes, 

@coffeebe4code `Info` block supports extensions now, but `Server` does not have support for those as of yet. Though adding that supports is quite quick
.

**Comment by lucasgranberg** [comment]
https://github.com/juhaku/utoipa/commit/b62efb45c7d75f539024306128d073e1e1cd7286

Pretty much this but my fork is too messed up to merge, better to do separately

**Comment by juhaku** [comment]
Right, 

It's worth to check https://spec.openapis.org/oas/latest.html which objects supports extensions and add on the same go the support for them if applicable. (I believe that not all objects can support in utoipa those extensions as of current state types.)
![image](https://github.com/user-attachments/assets/449c9bcf-8a0f-4847-97df-6869609d657d)

**Comment by juhaku** [comment]
This PR adds the extensions to types currently missing the field #1104.
