### ISSUE TITLE
For alias generic models the latest OpenAPI components overwrites previous

### ISSUE THREAD

**Issue by c-thiel** [juhaku/utoipa#644]
Sorry for the confusing headline, it's kind of hard to put in a sentence.

I have a class Animal using generics:
```rust
use serde::Serialize;
use utoipa::{OpenApi, ToSchema};

fn get_schema<T: for<'a> ToSchema<'a>>() -> utoipa::openapi::RefOr<utoipa::openapi::Schema> {
    let r = T::schema();
    r.1
}

#[derive(Serialize, ToSchema)]
#[schema(as = Cat)]
pub struct Cat {
    #[schema(example = "Garfield")]
    pub name: String,
    pub cat_type: String,
}

#[derive(Serialize, ToSchema)]
pub struct Dog {
    #[schema(example = "Toto")]
    pub name: String,
    pub dog_type: String,
}

#[derive(Serialize, ToSchema)]
#[aliases(CatModel = Animal<Cat>, DogModel = Animal<Dog>)]
pub struct Animal<T: for<'a> ToSchema<'a>> {
    id: String,
    #[serde(flatten)]
    #[schema(schema_with=get_schema::<T>)]
    object: T,
    #[schema(read_only)]
    read_only: String,
}

#[derive(utoipa::OpenApi)]
#[openapi(
    info(title = "Petstore API", version = "2023-03-26",),
    paths(),
    components(schemas(DogModel, CatModel),)
)]
pub struct ApiDoc;
```

Looking now at the two resulting aliases' schemas yields the correct results:
```rust
fn main() {
    // ----------- The schemas are correct! ------------
    println!(
        "Dog Schema: {}",
        serde_json::to_string_pretty(&DogModel::schema()).unwrap()
    );
    println!(
        "Cat Schema: {}",
        serde_json::to_string_pretty(&CatModel::schema()).unwrap()
    );
}
```

However, when looking at the resulting openapi class, the schema is wrong.
While both cat and dog are present, the last one specified in `components` at the OpenApi derive Macro, overwrites the schema of the other. I assume the generic parameter simply isn't taken into account?

It feels like this should be a relatively quick fix, as we already have the correct schemas available. Is there maybe a workaround?

Here is the full example demonstrating the problem:
```rust
use serde::Serialize;
use utoipa::{OpenApi, ToSchema};

fn get_schema<T: for<'a> ToSchema<'a>>() -> utoipa::openapi::RefOr<utoipa::openapi::Schema> {
    let r = T::schema();
    r.1
}

#[derive(Serialize, ToSchema)]
#[schema(as = Cat)]
pub struct Cat {
    #[schema(example = "Garfield")]
    pub name: String,
    pub cat_type: String,
}

#[derive(Serialize, ToSchema)]
pub struct Dog {
    #[schema(example = "Toto")]
    pub name: String,
    pub dog_type: String,
}

#[derive(Serialize, ToSchema)]
#[aliases(CatModel = Animal<Cat>, DogModel = Animal<Dog>)]
pub struct Animal<T: for<'a> ToSchema<'a>> {
    id: String,
    #[serde(flatten)]
    #[schema(schema_with=get_schema::<T>)]
    object: T,
    #[schema(read_only)]
    read_only: String,
}

#[derive(utoipa::OpenApi)]
#[openapi(
    info(title = "Petstore API", version = "2023-03-26",),
    paths(),
    components(schemas(DogModel, CatModel),)
)]
pub struct ApiDoc;

fn main() {
    // ----------- The schemas are correct! ------------
    println!(
        "Dog Schema: {}",
        serde_json::to_string_pretty(&DogModel::schema()).unwrap()
    );
    println!(
        "Cat Schema: {}",
        serde_json::to_string_pretty(&CatModel::schema()).unwrap()
    );
    // ------------ This is wrong, both cat and dog are the same! ------------
    // Apparently the latest model in the components() list takes precedence
    let api_doc = ApiDoc::openapi();
    println!(
        "API Doc: {}",
        serde_json::to_string_pretty(&api_doc).unwrap()
    );
}
```

Any help would be greatly appreciated :)

**Comment by nkovacs** [comment]
I looked into this a little more.

Unfortunately, the way schema generation is implemented means that it needs to know the concrete types. I wanted to reimplement `aliases` like this:

```
    fn aliases() -> Vec<(&'__s str, utoipa::openapi::schema::Schema)> {
        [
            (
                "FormFieldString",
                FormField::<String>::schema().1,
            ),
...
    }
```

Unfortunately, this won't work. The generated `schema` method is useless because it contains a ref to a type called "T". And even if that wasn't the case (e.g. it could instead use `T::schema().0`), schema doesn't know if T is a struct (which would need a ref) or a primitive like String, which is not a ref.

**Comment by juhaku** [comment]
That is, the fact that the `utoipa` is compile time library, moreover macro compile time library. The schema will be evaluated when macro's are being executed and not when they are declared in runtime code. The proc macros does not have access to outside world and is only able to read the context they are declared in as a token stream. All the information need exists in that token stream what is needed for schema generation. It does now know if the type decorated with `ToSchema` derive macro is used somewhere else and with what arguments if any.

**Comment by nkovacs** [comment]
@juhaku The generics-actix example in the repo doesn't work either:
![image](https://github.com/juhaku/utoipa/assets/2269242/d8039718-7dd5-4f2a-b893-a8144394b435)

I know proc macros have limitations, I've struggled with them in my own macros. But I think it is possible to use traits to solve this, PartialSchema seems like a good candidate for this. For example, if the generated `ToSchema::schema` method used PartialSchema for every field, the derive macro would no longer need to know what the type is, it could just blindly call `PartialSchema::schema` on everything and get the correct result. And then `FormField<String>::schema()` and `FormField<i64>::schema()` would return the correct schema for that variant, since the schema method would call the correct `String::schema` and `i64::schema`. To make this work for ToSchema types, a blanket `impl PartialSchema for ToSchema` could be used. Or alternatively, ToSchema could generate a PartialSchema impl as well, and then the ToSchema impl would just call that.

**Comment by JMLX42** [comment]
I thought I could workaround this by using a newtype:

```rust
struct Relationship<T> {
    data: T,
    links: RelationshipLinks,
}

#[derive(ToSchema)]
struct BufferResourceRelationshipToOne(
    #[schema(inline)] Relationship<BufferResourceIdentifierObject>,
);
#[derive(ToSchema)]
struct BufferResourceRelationshipToMany(
    #[schema(inline)] Relationship<Vec<BufferResourceIdentifierObject>>,
);
```

But it doesn't work. Two problems:

1. Despite inlining the `Relationship<BufferResourceIdentifierObject>` schema, `Ref::from_schema_name()` is used.
2. As described before in this thread, the type parameter is fixed to "T".

IMHO 1. and 2. are to separate problem. 1. could be solved separately. As to 2., could we update `ToSchema::schema()` to take the actual generic type(s) (schema(s)) as an optional argument?

**Comment by JMLX42** [comment]
>  could we update ToSchema::schema() to take the actual generic type(s) (schema(s)) as an optional argument?

Something like:

```rust
trait ToSchema {
  fn schema(params: Option<Vec<utoipa::openapi::Ref>>) -> (
      &'static str,
      utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>,
  );
}
```

```rust
impl<T> ToSchema for Relationship<T> {
    fn schema(
        params: Option<Vec<utoipa::openapi::Ref>>,
    ) -> (
        &'static str,
        utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>,
    ) {
        (
            "Relationship",
            utoipa::openapi::ObjectBuilder::new()
                .property(
                    "data",
                    params
                        .and_then(|params| params.get(0).cloned())
                        .unwrap_or_else(|| utoipa::openapi::Ref::from_schema_name("T")),
                )
                .required("data")
                .property(
                    "links",
                    utoipa::openapi::Ref::from_schema_name("RelationshipLinks"),
                )
                .required("links")
                .into(),
        )
    }
}
```
