### ISSUE TITLE
Add ServiceConfig to avoid redundancy.

### ISSUE THREAD

**Issue by afidegnum** [juhaku/utoipa#657]
Can you please guide on adding `ServiceConfig` instead of manually list the routes to avoid erroneous repetitions? 

the Configuration is already established at 
[looking at ](https://github.com/juhaku/utoipa/blob/master/examples/todo-actix/src/todo.rs#L18)
we only need to pass that `ServiceConfig` to paths instead of [manually list the routes](https://github.com/juhaku/utoipa/blob/master/examples/todo-actix/src/main.rs#L33) which could be tedious. Could there be a macro or anything you can suggest?

**Comment by juhaku** [comment]
At the moment there is no build in solution for this. But others might have build some sort of macro rules to mitigate the overhead of double definition. Also there is a thrid-party crate that might be useful: https://github.com/juhaku/utoipa/discussions/635 and there is one issue that has collected several relative issues together that touches the same topic https://github.com/juhaku/utoipa/issues/662.

**Comment by juhaku** [comment]
Related #121
