### ISSUE TITLE
Relax #[schema(inline)] requirement for generic types.

### ISSUE THREAD

**Issue by wuerges** [juhaku/utoipa#658]
I'm using utoipa in one of my projects, and we have paginated data like this:

```
#[derive(Serialize, ToSchema)]
pub struct PagedData<T> {
    pub info: PageInfo,
    #[schema(inline)]
    pub data: T,
}
```

This fail to compile, since T does not satisfy ToSchema<'_>.

Would it be possible to remove the requirement for T in the struct declaration, and add it only to the ToSchema trait implementation?

**Comment by jongiddy** [comment]
I expect that you need to ensure that `T` satisfies `ToSchema` and probably `Serialize` too.
```
#[derive(Serialize, ToSchema)]
pub struct PagedData<T: Serialize + ToSchema> {
    pub info: PageInfo,
    #[schema(inline)]
    pub data: T,
}
```
But perhaps I do not understand your question correctly?

**Comment by wuerges** [comment]
It's not really a question. Sorry. It is a polite request.

The schema type constraint doesnt need to be added to the definition.

This is important when you are developing an API. 

If you add the constraint to the struct, any crate that uses the struct will need to add utoipa as a dependency.

If you leave it out of the struct definition, and only add it in the implementation, crates that use the type but dont need utoipa won't need to import utoipa.

It is the same for Serialize/Deserialize. If you don't use them, you don't need to add serde as a dependency.

**Comment by wuerges** [comment]
It looks like full generic support solves this issue.
