### ISSUE TITLE
ToSchema on an enum with a documented unit variant does not produce a description

### ISSUE THREAD

**Issue by lithiumFlower** [juhaku/utoipa#679]
If I create an enum with unit variants that derives from ToSchema I'm unable to use docstrings to generate descriptions for the unit variants. For example:

```rust
/// top level doc for My enum
#[derive(ToSchema)]
pub enum MyEnum {
            /// unit variant doc
            UnitVariant,

            /// non unit variant doc
            NonUnitVariant(String),
}
```

generates the following openapi json:
```json
      "MyEnum": {
        "oneOf": [
          {
            "type": "string",
            "enum": [
              "UnitVariant"
            ]
          },
          {
            "type": "object",
            "required": [
              "NonUnitVariant"
            ],
            "properties": {
              "NonUnitVariant": {
                "type": "string",
                "description": "non unit variant doc"
              }
            }
          }
        ],
        "description": "top level doc for My enum"
      },
```

**Comment by juhaku** [comment]
True that, just checked and in fact that support has not been implemented. Seems like it has been forgotten somehow :smile: 

Need investigate in future what kind of effort would it be to get this support done.

**Comment by juhaku** [comment]
I boldly guess this is related to the #681.

**Comment by juhaku** [comment]
@lithiumFlower  Is this now something  that can be closed?

**Comment by lithiumFlower** [comment]
Yes, this is complete :)

**Comment by arifd** [comment]
If the enum contains only unit variants, no documentation is created.

this code:
```rs
use std::{error::Error, net::Ipv4Addr};

use actix_web::{App, HttpServer};
use utoipa::{ToSchema, OpenApi};
use utoipa_swagger_ui::{SwaggerUi, Url};

#[derive(ToSchema)]
pub enum MyEnum {
            /// unit variant doc
            UnitVariant,

            /// non unit variant doc
            NonUnitVariant(String),
}

#[derive(ToSchema)]
pub enum AllUnits {
        /// unit variant doc
        UnitA,

        /// another unit variant doc
        UnitB
}

#[actix_web::main]
async fn main() -> Result<(), impl Error> {
    #[derive(OpenApi)]
    #[openapi(components(schemas(MyEnum, AllUnits)))]
    struct ApiDoc;

    HttpServer::new(move || {
        App::new()
            .service(SwaggerUi::new("/swagger-ui/{_:.*}").urls(vec![
                (
                    Url::new("api", "/api-docs/openapi.json"),
                    ApiDoc::openapi(),
                ),
            ]))
    })
    .bind((Ipv4Addr::UNSPECIFIED, 8080))?
    .run()
    .await
}
```

produces this:
```json
{
  "openapi": "3.0.3",
  "info": {
    "title": "actix-web-multiple-api-docs-with-scopes",
    "description": "Simple actix-web with multiple scoped api docs",
    "contact": {
      "name": "Example",
      "email": "example@example.com"
    },
    "license": {
      "name": "MIT"
    },
    "version": "0.1.0"
  },
  "paths": {},
  "components": {
    "schemas": {
      "AllUnits": {
        "type": "string",
        "enum": [
          "UnitA",
          "UnitB"
        ]
      },
      "MyEnum": {
        "oneOf": [
          {
            "type": "string",
            "description": "unit variant doc",
            "enum": [
              "UnitVariant"
            ]
          },
          {
            "type": "object",
            "required": [
              "NonUnitVariant"
            ],
            "properties": {
              "NonUnitVariant": {
                "type": "string",
                "description": "non unit variant doc"
              }
            }
          }
        ]
      }
    }
  }
}
```

Which shows descriptions for `MyEnum` (the original enum in this issue), but not `AllUnits` which contains only unit variants

**Comment by niklaskorz** [comment]
> If the enum contains only unit variants, no documentation is created.
> 
> this code:
> 
> ```rust
> use std::{error::Error, net::Ipv4Addr};
> 
> use actix_web::{App, HttpServer};
> use utoipa::{ToSchema, OpenApi};
> use utoipa_swagger_ui::{SwaggerUi, Url};
> 
> #[derive(ToSchema)]
> pub enum MyEnum {
>             /// unit variant doc
>             UnitVariant,
> 
>             /// non unit variant doc
>             NonUnitVariant(String),
> }
> 
> #[derive(ToSchema)]
> pub enum AllUnits {
>         /// unit variant doc
>         UnitA,
> 
>         /// another unit variant doc
>         UnitB
> }
> 
> #[actix_web::main]
> async fn main() -> Result<(), impl Error> {
>     #[derive(OpenApi)]
>     #[openapi(components(schemas(MyEnum, AllUnits)))]
>     struct ApiDoc;
> 
>     HttpServer::new(move || {
>         App::new()
>             .service(SwaggerUi::new("/swagger-ui/{_:.*}").urls(vec![
>                 (
>                     Url::new("api", "/api-docs/openapi.json"),
>                     ApiDoc::openapi(),
>                 ),
>             ]))
>     })
>     .bind((Ipv4Addr::UNSPECIFIED, 8080))?
>     .run()
>     .await
> }
> ```
> 
> produces this:
> 
> ```json
> {
>   "openapi": "3.0.3",
>   "info": {
>     "title": "actix-web-multiple-api-docs-with-scopes",
>     "description": "Simple actix-web with multiple scoped api docs",
>     "contact": {
>       "name": "Example",
>       "email": "example@example.com"
>     },
>     "license": {
>       "name": "MIT"
>     },
>     "version": "0.1.0"
>   },
>   "paths": {},
>   "components": {
>     "schemas": {
>       "AllUnits": {
>         "type": "string",
>         "enum": [
>           "UnitA",
>           "UnitB"
>         ]
>       },
>       "MyEnum": {
>         "oneOf": [
>           {
>             "type": "string",
>             "description": "unit variant doc",
>             "enum": [
>               "UnitVariant"
>             ]
>           },
>           {
>             "type": "object",
>             "required": [
>               "NonUnitVariant"
>             ],
>             "properties": {
>               "NonUnitVariant": {
>                 "type": "string",
>                 "description": "non unit variant doc"
>               }
>             }
>           }
>         ]
>       }
>     }
>   }
> }
> ```
> 
> Which shows descriptions for `MyEnum` (the original enum in this issue), but not `AllUnits` which contains only unit variants

Running into this as well, I suppose we should open a new issue for this
