### ISSUE TITLE
utoipa 3.4.0 removed from crates.io

### ISSUE THREAD

**Issue by DannyGoldberg** [juhaku/utoipa#687]
Hello! It looks like utoipa 3.4.0 was removed from crates.io -- was that intentional?

Poking around, I don't see anything in the issues nor discussions referencing this

https://crates.io/crates/utoipa/3.4.0

<img width="635" alt="image" src="https://github.com/juhaku/utoipa/assets/8419161/3ae16ef5-618e-42d5-b28a-9f6b58575e69">

**Comment by juhaku** [comment]
Yes, related to discussion on this thread #675, In nut shell the 3.4.0 is a bit incomplete in `IntoParams` derive, path and query parameter support. While it is not a problem for all, but may cause issues for major part of users. It's probably better to first improve the implementation before making another release.

**Comment by juhaku** [comment]
The old paramete behavior is now restored an the "fix" release is coming soon https://github.com/juhaku/utoipa/issues/675#issuecomment-1646608089.
