### ISSUE TITLE
Remove License

### ISSUE THREAD

**Issue by Narven** [juhaku/utoipa#689]
How can I remove License? If I don't set anything, it just puts a "License" text. Can it be removed? 
I think this was an issue already resolve by the Swagger docs by default... if not mistaken.

**Comment by juhaku** [comment]
I assume that it should be possible with manually setting the `license` field to `None`. https://github.com/juhaku/utoipa/blob/0073541e7cc4fca97e17c75bef20df3681225c78/utoipa/src/openapi/info.rs#L120
https://github.com/juhaku/utoipa/blob/0073541e7cc4fca97e17c75bef20df3681225c78/utoipa/src/openapi/info.rs#L65

You can either use `Modify` trait or directly edit the generated api.

**Comment by ncmbch** [comment]
Yes, I have it removed this way:

```rust
#[derive(OpenApi)]
#[openapi(
    info(
        title = "..."
    ),
    modifiers(&LicenseModifier)
)]
struct ApiDoc;

struct LicenseModifier;

impl Modify for LicenseModifier {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        openapi.info.license = None;
    }
}
```

**Comment by juhaku** [comment]
Closing due inactivity, I presume this is as solved.
