### ISSUE TITLE
Trouble creating schema for structs with Arc

### ISSUE THREAD

**Issue by zajko** [juhaku/utoipa#691]
Hi,
I'm trying to use utoipa with my project, and I stumbled with an issue when trying to use ToSchema with a struct that uses `Arc`. A way to reproduce the issue would be:
```
use std::sync::Arc;
use serde_json;
use utoipa::ToSchema;

#[derive(ToSchema)]
struct B {
    a: u32,
    b: String,
}

#[derive(ToSchema)]
pub struct A {
    z: Arc<B>,
    zz: Arc<String>,
}

fn main() {
    let z = &A::schema().1;
    println!("{}", serde_json::to_string(z).unwrap());
}
```
which produces:
`{"type":"object","required":["z","zz"],"properties":{"z":{"$ref":"#/components/schemas/Arc"},"zz":{"$ref":"#/components/schemas/Arc"}}}`

I'm assuming that's not by design? I took the liberty of proposing a change to treat Arc's as Box or RefCell:
https://github.com/juhaku/utoipa/pull/690
maybe it could get included in the next release? :)

**Comment by juhaku** [comment]
It is not by design, but somehow it has been unnoticed all this time. :smile: Design was to allow all typical `Send` trait implementing types to be allowed.

> maybe it could get included in the next release?

Sure, there is just few things I need to finish before the next release can be released.

**Comment by juhaku** [comment]
@zajko BTW why is the `Arc` support needed? The `Arc` needs manual implementation for `Serialize` trait.
