### ISSUE TITLE
make request_body allow multiple content types like responses do

### ISSUE THREAD

**Issue by EmmFloClax** [juhaku/utoipa#692]
`#[utopia::path(request_body(content = MyObject, content_type = ["application/json", "application/vnd.apache.arrow.stream"])` 
is not allowed, I can only declare one content_type but by functions allows data of both types to be accepted. I can have multple content_types for the response, can we have this feature for request_body?

**Comment by juhaku** [comment]
Yeah, that is has not been implemented for `request_body`. Surely this could also be implemented for `request_body` in future if it supports this format by OpenAPI spec.
