### ISSUE TITLE
Support for "anyOf" container

### ISSUE THREAD

**Issue by zajko** [juhaku/utoipa#707]
Hi
I'm using utoipa with my types having fields defined in an external (closed for me) library. That external library offers json schema for it's types, but it serialises schema using schemars, and schemars uses `anyOf` quite heavily.
I'm proposing to add the possibility of deserializing a schema from string that uses anyOf by introducing such variant in the `Schema` enum (https://github.com/juhaku/utoipa/pull/706).

If this enhancement "makes sense" I can implement all the alternatives that json schema offers - not to use it exclusively in utoipa, but so that anyone can use a pre-existing json schema string and deserialize it to utoipa schema with less massaging.

**Comment by juhaku** [comment]
Sounds good, I allready merged this change. If you have things to add just make a PR. :slightly_smiling_face:
