### ISSUE TITLE
Add option to make schema name a fully qualified name

### ISSUE THREAD

**Issue by gzp79** [juhaku/utoipa#710]
I'm using ToSchema, ToResponse to decorate my types. Unfortunately it seems as the name for the schema is the name of the structure by defaultl, but as I have multiple schemas with the same name in different moduls, they are conflicting.
I'm decorating the structs like this:

```
#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
struct Response {
    #[schema(schema_with = schema_name_ref::<DBState>)]
    pub postgres: DBState,
    #[schema(schema_with = schema_name_ref::<DBState>)]
    pub redis: DBState,
}

fn swagger_name<T: ?Sized>() -> String {
    type_name::<T>().replace("::", ".")
}

pub fn schema_name_ref<T: ?Sized>() -> Ref {
    Ref::from_schema_name(swagger_name::<T>())
}

```

Which seems to be working, but adding them to all the nested types makes it really hard to maintain the code.

Is there some other utility for this.

(Note In my case only the IntoParams, ToSchema and ToResponse derives are used and I'm constructing the path by hand with the path builder pattern, to keep the routing and doc in sync without duplication.
- endpoint description: https://github.com/gzp-crey/shine-service-rs/blob/e762dde4014b79c1f663d7809fabd92ecc65a959/shine-service/src/axum/openapi.rs#L53
- utility to add endpoint to routes: https://github.com/gzp-crey/shine-service-rs/blob/e762dde4014b79c1f663d7809fabd92ecc65a959/shine-service/src/axum/openapi.rs#L199)

**Comment by juhaku** [comment]
If I understand your need correctly you may use the `as = ` attribute on `ToSchema` derive macro https://docs.rs/utoipa/3.5.0/utoipa/derive.ToSchema.html. Then make sure you reference your schemas with the fully qualified name in path operation e.g. in request body.
