### ISSUE TITLE
Ref description

### ISSUE THREAD

**Issue by wackazong** [juhaku/utoipa#715]
I have a recursive JSON structure which is interpreted by utoipa by using `Ref`, which is the way to go. But AFAIK it is perfectly fine (and it makes sense) to have a description for a field which references its own type. Unfortunately, doc comments for this field are not rendered into a description into the OpenAPI json. The `Ref` struct does not contain a `description` field which I think it should. 

Workaround: add the description to the json data that utoipa produces. That is very cumbersome and brittle.

**Comment by juhaku** [comment]
This is duplicate to this #137. In OpenAPI spec 3.0 the `$ref` does not have support for description field. And thus cannot be directly added there.

**Comment by wackazong** [comment]
Ok, thanks for clearing that up. I use Rapidoc which accepts a description there. I think it already supports OpenAPI 3.1. BTW, I find Rapidoc far superior to Swagger UI.
