### ISSUE TITLE
IMPORTANT: September Update

### ISSUE THREAD

**Issue by juhaku** [juhaku/utoipa#726]
I am travelling the whole september and thus not able to do any contributions to the utoipa project during that time. This also includes replying to issues and checking PRs, as most of the time I am not going to be near computer nor would I have access to the Github most likely. 

Before this I try to contribute as much as possible and make releases when needed. All the breaking changes if introduced to the master will have to wait for release at least after the September. 

Thanks
-Juha

**Comment by jayvdb** [comment]
hi @juhaku , looks like you're back on deck. When do you expect to be cutting the next release?

**Comment by juhaku** [comment]
Hey @jayvdb, yeah I am back. 

Frankly speaking I was planning to still do some major changes to the library before the next release including providing an alternative to the OpenApi derive macro which would be builder based but still leverage macros with hopes to better support scoping / sub modules for handlers. Though I could make a new release basically anytime now if needed. There is only one breaking change that changes the `Path` trait's `path()` method return type.

**Comment by jayvdb** [comment]
I am keen to see https://github.com/juhaku/utoipa/pull/756 released, and I am sure there are projects waiting on the other merged features.

I've done a build of my project using utoipa `master` and all is well for me.

**Comment by juhaku** [comment]
I could make a release in these coming days indeed. Most people won't see difference only those who manually have implemented the `Path` trait will see breaking behavior but that is relatively rare case I assume.
