### ISSUE TITLE
`#[schema(inline)]` for enums like for structs

### ISSUE THREAD

**Issue by smndtrl** [juhaku/utoipa#727]
After digging through `utoipa-gen` tests, I was wondering, if there's a possibility for using sth like `#[schema(inline)]` for `enum`s so that definitions that were otherwise end up being referenced are inlined.

```rust
enum Auth {
    #[schema(inline)] 
    BasicAuth(BasicAuth),
    ClientCertAuth { certificate: Vec<u8> },
}
```

would end up being a schema without any `$ref`. Maybe it would make sense to move the `#[schema(inline)]` to the actual type like this `BasicAuth(#[schema(inline)] BasicAuth)`

We have another system that doesn't handle `$ref` too well. Having the `#[schema(inline)]` for structs, it would be nice for enums as well.

**Comment by juhaku** [comment]
Pretty good idea. Surely this is something that could be explored in future and if possible added to the library as well. Also PRs are welcome if there is enough interest on implementing this feature.

**Comment by JMLX42** [comment]
@juhaku if that's still on the table I'll try to do it.

**Comment by JMLX42** [comment]
@juhaku @smndtrl PR: #963

**Comment by juhaku** [comment]
@JMLX42 great, all the help is welcome :slightly_smiling_face:

**Comment by juhaku** [comment]
Done in the PR @JMLX42 pointed above
