### ISSUE TITLE
todo-axum example, do not work for query parameters

### ISSUE THREAD

**Issue by mygitcsv** [juhaku/utoipa#728]
TODO example for axum does not work.
The generated page for Query parameters is not correct.
utoipa = "3.4.4"
utoipa-swagger-ui = { version = "3.1.5", features = ["axum"] }
![L{XABJE)O7ULFUA2H6DKC6H](https://github.com/juhaku/utoipa/assets/139714571/0b8df47f-4391-4060-b88f-dce42a48e9f5)

**Comment by juhaku** [comment]
@GunnarMorrigan that is the solution. However I believe that you have `axum_extras` feature flag enabled from `utoipa` and handler that looks like this:
```rust
#[derive(IntoParams)]
struct Params {...}

async fn handler(query: Query<Params>) {...}
```
You should be see those parameters in query parameters by default. But if not the adding `#[into_params(parameter_in = Query)]` fill set those fields as query parameters.

**Comment by juhaku** [comment]
Considered complete, but if issues arises could be reopened.
