### ISSUE TITLE
Can't host the SwaggerUi on a nested endpoint with axum 

### ISSUE THREAD

**Issue by stusmall** [juhaku/utoipa#734]
I have an axum service that is made to support multiple versions of the API.  Each version of the API is contained in its own module and then a router it returned from the only public  method from the module, so like:

```
pub fn build_router<DAO: Dao>() -> Router<DAO, Body> {
    Router::new()
        .route("/message", get(get_messages::get_messages::<DAO>))
       ....
}
```

This is done to keep the implementation of each version well isolated from each other since they often have similar named structs and methods.

This module is then nested to the larger app by nesting it, so:
```
let app = Router::new()
        .nest("/api/v1", handlers::v1::build_router::<DAO>())
        .nest("/api/v2", handlers::v2::build_router::<DAO>())
        .with_state(dao)
```

The problem comes up when I want to add a swagger UI.  I want to add it to the `build_router` method. So something like:
```
pub fn build_router<DAO: Dao>() -> Router<DAO, Body> {
    Router::new()
        .merge(SwaggerUi::new("/swagger-ui").url("/openapi.json", ApiDoc::openapi()))
        .route("/message", get(get_messages::get_messages::<DAO>))
}
```

The swagger UI would then be served at "/api/v1/swagger-ui" and by default try to load the openapi.json from "/openapi.json" but it is actually being served from "/api/v1/openapi.json".  I can't find a way to make this work.

As a work around I'm making the ApiDoc public from the module, added directly to the root router like this:
```
    let app = Router::new()
        .merge(SwaggerUi::new("/api/v1/swagger-ui").url("api/v1/openapi.json", handlers::v1::ApiDoc::openapi()))
        .merge(SwaggerUi::new("/api/v2/swagger-ui").url("api/v2/openapi.json", handlers::v2::ApiDoc::openapi()))
        .nest("/api/v1", handlers::v1::build_router::<DAO>())
        .nest("/api/v2", handlers::v2::build_router::<DAO>())
        .with_state(dao)
```
This works and isn't the end of the world, but it would nice to be able to use nest on SwaggerUi

**Comment by haithngn** [comment]
The utopia is now able to work on nested routers already, you need to provide a correct config.
eg.
```
let config = Config::from("/v1/api-docs/openapi.json");
let mut router = Router::new()
        .merge(SwaggerUi::new("/swagger-ui")
            .url("/api-docs/openapi.json", ApiDoc::openapi())
            .config(config)
        )
```

**Comment by juhaku** [comment]
Yup thats the way to solve this.
