### ISSUE TITLE
What to do if there are two functions with the same name in two different files

### ISSUE THREAD

**Issue by UVUUUVUU** [juhaku/utoipa#735]
What to do if there are two functions with the same name in two different files, but the paths of the OpenAPI do not allow the existence of functions with the same name

**Comment by jayvdb** [comment]
Does this work?
```rust
use mod1::foo as foo1;
use mod2::foo as foo2;
```

**Comment by UVUUUVUU** [comment]
yeah, thanks for your answer！

**Comment by jayvdb** [comment]
Great. Could you please close the issues that have been resolved?
