### ISSUE TITLE
how to write responses(body=)

### ISSUE THREAD

**Issue by UVUUUVUU** [juhaku/utoipa#737]
`#[utoipa::path(
    responses(
        (status = 200, description = "OK", body = Value)
    )
)]
#[get("/health")]
pub async fn health(_request: HttpRequest) -> HttpResult {
    Ok(HttpResponse::Ok().json(json!({"status":0})))
}`
Hello, I want to ask a question: How should a body be defined for the above code? Thank you!

**Comment by jayvdb** [comment]
You would create a struct to describe the body `{"status":0}`, and then use it in the `utoipa::path` macro call
```rust
...
responses(
    (status = 200, body = MyStatusStruct, description = "Provides the health check status"),
),
...
```

**Comment by UVUUUVUU** [comment]
ok，got it. Thanks！
