### ISSUE TITLE
Cannot add ToSchema macro for  rust type

### ISSUE THREAD

**Issue by ziqiangai** [juhaku/utoipa#751]
If I have the following rust type:

```rust
pub type FieldMapSO = HashMapExt<String, FieldSO>;
```
I can't add this type to the APIDoc's schema arra like this.

```rust

#[derive(ToSchema)]
pub type FieldMapSO = HashMapExt<String, FieldSO>; // error
```

What should be the best practice？

**Comment by jayvdb** [comment]
The error is
```rust
error[E0774]: `derive` may only be applied to `struct`s, `enum`s and `union`s
  --> foo.rs:67:5
   |
67 |     #[derive(ToSchema)]
   |     ^^^^^^^^^^^^^^^^^^^ not applicable here
68 |     type MyHashMap = HashMap<String, String>;
   |     ----------------------------------------- not a `struct`, `enum` or `union`

For more information about this error, try `rustc --explain E0774`.
```
https://doc.rust-lang.org/error_codes/E0774.html

More info on type aliases at https://doc.rust-lang.org/reference/items/type-aliases.html and https://doc.rust-lang.org/1.30.0/book/second-edition/ch19-04-advanced-types.html#creating-type-synonyms-with-type-aliases

The simplest approach is to use a [newtype](https://doc.rust-lang.org/rust-by-example/generics/new_types.html) pattern to wrap the type.
```rust
#[derive(ToSchema)]
pub struct FieldMapSO(HashMapExt<String, FieldSO>);
```

If you cant do that, the following will allow use of the type alias as part of other data types.
```rust
type MyHashMap = HashMap<String, String>;

#[derive(ToSchema)]
struct MyStruct {
    #[schema(value_type=HashMap<String, String>)]
    map: MyHashMap,
}
```

**Comment by jayvdb** [comment]
related, I found that adding the following to `schema_derive_test.rs` doesnt have a compile failure

```rust
#[test]
fn derive_map_type_using_type() {
    type MyHashMap = HashMap<String, String>;
    let map = api_doc! {
        struct Map {
            map: MyHashMap,
        }
    };

    assert_value! { map=>
        "properties.map.additionalProperties.type" = r#""string""#, "Additional Property Type"
    };
}
```
result is
```
thread 'derive_map_type_using_type' panicked at 'assertion failed: `(left == right)`
  left: `"null"`,
 right: `"\"string\""`: Additional Property Type: properties.map.additionalProperties.type expected to be: "string" but was: null', utoipa-gen/tests/schema_derive_test.rs:74:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Exclamation-mark** [comment]
Thank you for telling me this way.

```rust
#[derive(ToSchema)]
pub struct FieldMapSO(HashMapExt<String, FieldSO>);
```

**Comment by juhaku** [comment]
@jayvdb Yeah it cannot recognize types from aliases, however generics will be fully supported with the coming #1034 PR. The alias in your test example creates an "object" I assume.

**Comment by juhaku** [comment]
Closing this for now, but this can be opened again if deemed necessary.
