### ISSUE TITLE
example on file uploads

### ISSUE THREAD

**Issue by beckend** [juhaku/utoipa#753]
Did not want to necrobump https://github.com/juhaku/utoipa/issues/154

However I cannot find these derives

```rust
#[derive(Component)]
#[component(format = ComponentFormat::Binary)]
```

**Comment by juhaku** [comment]
That examples is before 2.0.0 release. The `Component` is `ToSchema` nowadays and `ComponentFormat` is `SchemaFormat`. 

Here is the links to the docs: 
* https://docs.rs/utoipa/3.5.0/utoipa/openapi/schema/index.html https://docs.rs/utoipa/3.5.0/utoipa/openapi/schema/enum.SchemaFormat.html 
* https://docs.rs/utoipa/3.5.0/utoipa/derive.ToSchema.html 

And link to the discussion about change that was made earlier: https://github.com/juhaku/utoipa/discussions/181

**Comment by beckend** [comment]
ok for actual examples:

```rust
#[derive(Deserialize, Debug, Clone, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct InputWithFiles {
  #[schema(value_type = String, format = Binary)]
  file_cv: Vec<u8>,
  #[schema(value_type = String, format = Binary)]
  file_cover_letter: Option<Vec<u8>>,
}

```
