### ISSUE TITLE
object propertyNames support

### ISSUE THREAD

**Issue by jnicholls** [juhaku/utoipa#755]
OpenAPI v3.1 supports the ability to configure an object schema with `propertyNames` that can restrict the property keys allowed for an object. A common case is where an `enum` schema is used as the list of available properties on an object.

See this StackOverflow article for instance: https://stackoverflow.com/questions/46552863/how-to-write-openapi-3-swagger-specification-for-property-name-in-map-object/46553255#46553255

I notice that there is no ability to configure `propertyNames` in the `ObjectBuilder`, and I also notice that the `ToSchema` derive macro does not properly handle the case of an object or map type such as `HashMap<MyEnum, MyValue>` where the key type is a Rust `enum` of unit variants. Adding in the support for `propertyNames` into the spec implementation first would be a good start, followed by the proper handling of the `ToSchema` derive macro for a type that looks like this (notice the new usage of `additional_properties` too, to handle Refs and not just FreeForm):

```
#[derive(ToSchema)]
enum MyEnum {
    VariantOne,
    VariantTwo,
}

#[derive(ToSchema)]
struct MyValue {
    x: i32,
    y: i32,
}

#[derive(ToSchema)]
struct MySchema {
    #[serde(flatten)]
    #[schema(additional_properties = MyValue)]
    properties: HashMap<MyEnum, MyValue>,
}
```

which generates an object schema that looks like this:

```
{
  "type": "object",
  "propertyNames": {
    "enum": ["VariantOne", "VariantTwo"]
  },
  "additionalProperties": {
    "$ref": "#/components/schemas/MyValue"
  }
}
```

**Comment by ctron** [comment]
I am running into a similar situation, where I end up with:

```yaml
my-field:
  type: object
  additionalProperties:
    $ref: '#/components/schemas/BTreeSet'
```

And it seems there's no way to override the of `additionalProperties`.

**Comment by joshbenz** [comment]
This would be nice to have. Or is there a  way to achieve something similar? I am trying to use a HashMap<MyEnum, bool>

**Comment by juhaku** [comment]
Since utoipa is moving to OpenAPI 3.1 from 5.0.0 version onwards this seems to be quite reasonable thing to implement to further enhance map support.
