### ISSUE TITLE
How to use DateTime type in structs

### ISSUE THREAD

**Issue by bangbaew** [juhaku/utoipa#760]
I can't find it in the document, tried to use chrono::Datetime<FixedOffset> but ToSchema is not satisfied.

**Comment by jayvdb** [comment]
https://github.com/juhaku/utoipa/pull/758 has two examples, one without actix, and the other with actix.

**Comment by bangbaew** [comment]
> #758 has two examples, one without actix, and the other with actix.

Thank you!
