### ISSUE TITLE
[feature] qol with merge

### ISSUE THREAD

**Issue by mortifia** [juhaku/utoipa#776]
update this Implementations
pub fn [merge](https://docs.rs/utoipa/4.0.0/utoipa/openapi/struct.OpenApi.html#method.merge)(&mut self, other: [OpenApi](https://docs.rs/utoipa/4.0.0/utoipa/openapi/struct.OpenApi.html))

to 
pub fn [merge](https://docs.rs/utoipa/4.0.0/utoipa/openapi/struct.OpenApi.html#method.merge)(&mut self, other: [OpenApi](https://docs.rs/utoipa/4.0.0/utoipa/openapi/struct.OpenApi.html)) -> [OpenApi](https://docs.rs/utoipa/4.0.0/utoipa/openapi/struct.OpenApi.html)

or 
pub fn [merge](https://docs.rs/utoipa/4.0.0/utoipa/openapi/struct.OpenApi.html#method.merge)(&mut self, other: [OpenApi](https://docs.rs/utoipa/4.0.0/utoipa/openapi/struct.OpenApi.html)) -> Self

why ?

to avoid creating a mutable var 

```rust
    // with axum
   
    let mut api_doc = ApiDoc::openapi();
    api_doc.merge(advertisements::ApiDoc::openapi());
    
    let app = Router::new()
        .route("/", get(hello_world))
        .nest("/advertisement", advertisements_routes())
        .merge(SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json", api_doc));
        
    //to
    
    let app = Router::new()
        .route("/", get(hello_world))
        .nest("/advertisement", advertisements_routes())
        .merge(SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json",
            ApiDoc::openapi()
                .merge(advertisements::ApiDoc::openapi())
            );
```

**Comment by juhaku** [comment]
Perhaps we could add another API that supports this behavior. E.g. `merge_from`.
