### ISSUE TITLE
Support expression in further macro args, in particular in openapi::tags::name

### ISSUE THREAD

**Issue by hseeberger** [juhaku/utoipa#780]
#762 introduced expressions in some macro args. For me that is fantastic.

Yet some macro args do not yet support expressions. One that I'd like to see is `openapi::tags::name`, because then one could use the same constant for that `name` as well as the already possible `utoipa::path::tag`.

**Comment by juhaku** [comment]
Sure, more attributes with expression support can be added in future. This is something that can be addressed in future and should be quite simple task.

**Comment by hseeberger** [comment]
Fantastic, thanks!
