### ISSUE TITLE
BTreeSet support

### ISSUE THREAD

**Issue by ctron** [juhaku/utoipa#789]
To me it looks like `BTreeSet` isn't supported.

**Comment by juhaku** [comment]
True, there is no support for it as of now. Though PRs are welcome. If it needs to behave like a Vec the support should be quite trivial to implement.

**Comment by ctron** [comment]
Sure, I just tried to get started. But I guess I need a pointer where the basic types are located, so that I can take a look.

**Comment by juhaku** [comment]
Sure, currently the crate is basically formed from 2 parts. (That should be evaluated a bit probalby) The `utoipa` contains the OpenAPI types, non-complete set though. `utoipa-gen` does the heavy lifting by implementing the proc macro for generating the OpenAPI docs. 

In `utoipa-gen` the part that you are particularly interested is the `component.rs` and maybe `component_type.rs`. Then you can add another test for schema generation to `utoipa-gen/tests/schema_derive_test.rs` This is a massive file and it contains quite a few test for different variations of the schema.
