### ISSUE TITLE
Adding headers with Swagger

### ISSUE THREAD

**Issue by EvilWatermelon** [juhaku/utoipa#796]
After adding the `Header` param nothing changed. The `ServiceRequest` didn't showed my header. Do I have to do something on `actix_web` side?

```rust
#[utoipa::path(
    context_path = "/tools",
    tag = "tools",
    params(
        ("url", 
            description = "URL that should be scanned for fingerprints.", 
            example = "https://example.com"
        ),
        ("Authorization" = String, Header, description = "JWT")
    ),
    responses(
        (status = 200, description = "JSON output of the blacklight collector.", body = String),
        (status = 400, description = "Wrong URL.", body = String)
    )
)]
#[get("/blacklight/{url}")]
pub async fn blacklight(
    path: web::Path<String>, 
    claims: Option<web::ReqData<Claims>>
) -> impl Responder {
    let url: String = path.into_inner();

    match url_check::is_url(url.as_str()) {
        true => {
            if let Some(claims) = claims {
                publish_service::publisher(claims.sub.clone(), &url);
            }

            HttpResponse::Ok().json("Ok")
        },
        false => HttpResponse::BadRequest().body("ProtocolError: Cannot navigate to invalid URL")
    }
}
```

**Comment by juhaku** [comment]
The Swagger UI itself does not allow `Authorization` and some other headers to be manually added to the schema. Instead you need to use security schema for that. You can browse through the acitx-web todo example for a reference.

**Comment by EvilWatermelon** [comment]
But what is this `Header` in `params()` for?

**Comment by EvilWatermelon** [comment]
But how can I enforce this? I want this token as a requirement for all endpoints with the security argument.

**Comment by juhaku** [comment]
> But how can I enforce this? I want this token as a requirement for all endpoints with the security argument.

You can define same `security` attributes for `OpenApi` trait as for `utoipa::path` attribute macro. By defining it on `OpenApi` will enforce the attributes for all the endpoints of the API. https://docs.rs/utoipa/latest/utoipa/derive.OpenApi.html#openapi-openapi-attributes

Here is the example on path of how to define security attributes. The same syntax works for `OpenApi` as well. https://docs.rs/utoipa/latest/utoipa/attr.path.html#examples

Excerpt of the docs:
```
security(
       (), // .. <--- this makes the authentication optional
       ("my_auth" = ["read:items", "edit:items"]),
       ("token_jwt" = [])
   )
```

**Comment by aminya** [comment]
I found the documentation and examples lacking here. 
You will need to implement
```rs
#[derive(OpenApi)]
#[openapi(
	....,
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;


struct SecurityAddon;

impl Modify for SecurityAddon {
  fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
    if openapi.components.is_none() {
      openapi.components = Some(Components::new());
    }

    openapi.components.as_mut().unwrap().add_security_scheme(
      "bearerAuth",
      SecurityScheme::Http(
        HttpBuilder::new()
          .scheme(HttpAuthScheme::Bearer)
          .bearer_format("JWT")
          .build(),
      ),
    );
  }
}

```

Then add  security to every path handler:
```rs
#[utoipa::path(
	...,
    security(
      ("bearerAuth" = [])
    ),
)]
```


This article explains it all:
https://codevoweb.com/add-swagger-ui-redoc-and-rapidoc-to-a-rust-api
