### ISSUE TITLE
Using invalid Rust type in path/responses/body does not lead to a Rust compile error

### ISSUE THREAD

**Issue by audunhalland** [juhaku/utoipa#801]
I tried to use the `path` macro like this:

```rust
#[derive(serde::Serialize, utoipa::ToSchema)]
pub(super) struct MyJson {
    // some fields
}

#[utoipa::path(
    get,
    path = "/some/path",
    responses(
        (
            status = StatusCode::OK,
            body = MyBogusType // <------ problem
        )
    )
)]
async fn some_function(..) -> () { .. }
```

I expect this to _not_ compile, but it compiles. The bug here is that the macro does not treat `MyBogusType` as an identifier referring to a real rust type, but instead it's directly converted to a string literal.

I didn't expect this behaviour. My expectation was that when the macro accepts an identifier, it will actually be treated as an identifier.

If the macro instead used the identifier through some trait (to acquire the string-representation of the type's name, like `ToSchema`), then we'd have better compile-time verification of the resulting spec. Also, if one uses rust-analyzer for refactoring and change the name of my struct from e.g. `OldJson` to `NewJson`, the identifier in the macro body would also automatically updated.

edit: By the way, thanks for working on utoipa, we'll likely use this instead of hardcoded/external openapi.yaml file. Utoipa is already an immense improvement on keeping documentation close to implementation!

**Comment by juhaku** [comment]
This is duplicate to: https://github.com/juhaku/utoipa/issues/500
