### ISSUE TITLE
Add support for overriding description (and summary) for `path` and `ToSchema` macros

### ISSUE THREAD

**Issue by clechasseur** [juhaku/utoipa#802]
`utoipa` derive macros as well as `#[utoipa::path]` use doc comments for OpenAPI description (and, in the case of `path`, also summary). For [`IntoResponses`](https://docs.rs/utoipa/4.1.0/utoipa/derive.IntoResponses.html) and [`ToResponse`](https://docs.rs/utoipa/4.1.0/utoipa/derive.ToResponse.html), it is possible to override this via a `description` attribute, but not for others.

I would suggest adding support for such a `description` (and `summary`) overrides for two other macros:
- [`path`](https://docs.rs/utoipa/4.1.0/utoipa/attr.path.html)
- [`ToSchema`](https://docs.rs/utoipa/4.1.0/utoipa/derive.ToSchema.html)

(It could also be possible to override field-level descriptions, although I see this as less useful personally.)

I volunteer to submit a PR for this if this is deemed an acceptable feature.

(This references #781 and #439; I wanted to open a fresh new issue since I volunteer, so that it has its own tracking issue.)

**Comment by juhaku** [comment]
Sure, go ahead.. Less work for me the better :laughing:.

**Comment by juhaku** [comment]
#948 Adds support for the `description` and `summary` attributes for `path` macro.

**Comment by juhaku** [comment]
#949 adds the `description` support for `ToSchema`
