### ISSUE TITLE
Feature request: add support for adding multiple security requirements.

### ISSUE THREAD

**Issue by abs0luty** [juhaku/utoipa#803]
As described in https://swagger.io/docs/specification/authentication/:

Some REST APIs support several authentication types. The security section lets you combine the security requirements using logical OR and AND to achieve the desired result. security uses the following logic:
```
security:    # A OR B
  - A
  - B
security:    # A AND B
  - A
    B
security:    # (A AND B) OR (C AND D)
  - A
    B
  - C
    D
```

I think, the previous example can be implemented this way:

```rs
#[utoipa::path(
  ..,
  security(
    ("a" = ["test"], "b" = ["test"]), // (A AND B) OR (C AND D)
    ("c" = [], "d" = []),
  ),
  ..
)
async fn test() {}
```

**Comment by juhaku** [comment]
Sure this could be added in future releases. The discussion earlier related to this https://github.com/juhaku/utoipa/discussions/625 seemingly indicates that there is a valid need for this support.

**Comment by abs0luty** [comment]
I'll take it. Already implemented the codegen part.
