### ISSUE TITLE
SwaggerUI dont work with axum 0.7.x

### ISSUE THREAD

**Issue by dayvejones** [juhaku/utoipa#808]
Hello !

I updated axum version from 0.6.20 to 0.7.1 and got the problem. 

```
axum = "0.7.1"
utoipa = { version = "4.1.0", features = ["axum_extras", "chrono", "preserve_path_order"] }
utoipa-swagger-ui = { version = "4.0.0", features = ["axum"] }
```

```
Router::new()
    .merge(SwaggerUi::new("/swagger-ui").url("/api-doc/openapi.json", ApiDoc::openapi()))
```

problem:

```
the trait bound `Router<StateData>: From<SwaggerUi>` is not satisfied
required for `SwaggerUi` to implement `Into<Router<StateData>>
```

thank you for super useful crate!

**Comment by arshia-gh** [comment]
Yep I'm having the same issue

**Comment by juhaku** [comment]
> @juhaku Is it possible to get a new release with this fix?

Sure, I make the release shortly. It will be a breaking change for the `utoipa-swagger-ui` and `utoipa-redoc` and `utoipa-rapidoc`.

**Comment by asyncfncom** [comment]
@juhaku @Libbum Thank you!
