### ISSUE TITLE
Support #[serde(deny_unknown_fields)]

### ISSUE THREAD

**Issue by jayvdb** [juhaku/utoipa#812]
[`#[serde(deny_unknown_fields)]`](https://serde.rs/container-attrs.html#deny_unknown_fields) on a struct should result in `additionalProperties: false` in the outputted schema.

c.f. https://json-schema.org/understanding-json-schema/reference/object#additionalproperties

**Comment by juhaku** [comment]
Great, good that you took the initiative to implement the feature. Recently I have had close to no time to invest in the utoipa.
