### ISSUE TITLE
Aliases for generic enum in body

### ISSUE THREAD

**Issue by javihc** [juhaku/utoipa#817]
I am writting an API with Axum and I am using and enum to recevibe o single value or a list of values. For that I am using a Enum with a generic type  `T`

```rust
pub enum OneOrMany<T> {
    /// A single value
    One(T),
    /// A list of values
    Many(Vec<T>),
}
```

To generate the OpenAPi I use aliases `aliases(StringOneOrMany = OneOrMany<String>)` and when I generate the openapi.json it serialize as 
```json
"StringOneOrMany": {
    "oneOf": [
        {
            "$ref": "#/components/schemas/T"
        },
        {
            "type": "array",
            "items": {
                "$ref": "#/components/schemas/T"
            },
            "description": "A list of values"
        }
    ]
},
```

How can I generate the schema correctly without using `value_type=`

```rust
pub enum OneOrMany<T> {
    #[schema(value_type = String)]
    /// A single value
    One(T),
    #[schema(value_type = Vec<String>)]
    /// A list of values
    Many(Vec<T>),
}
```

With `schemars` the is no problem.

**Comment by wuerges** [comment]
Hey. In my project, I've implemented the `ToSchema` trait manually. I added a constraint for T:

```
impl<'a, T: ToSchema<'a>> ToSchema<'a> for OneOrMany<T> {
    // here goes your manual implementation
```

**Comment by wuerges** [comment]
Thank you very much!
