### ISSUE TITLE
OIDC Authorization token in cookie

### ISSUE THREAD

**Issue by bangbaew** [juhaku/utoipa#826]
Is it possible to change `In` of OIDC token from `Authorization` header to a custom cookie?, I only see api key auth in the documentation that supports cookie, wondering if I can do that in OpenID Connect too.

**Comment by juhaku** [comment]
@bangbaew To be honest I am not that familiar with the Open id connect specification.  What comes to `utoipa` it only implements the types that OpenAPI specification supports regarding authentication. It itself does not have anything to do with the authentication itself. Instead that authentication is done elsewhere. E.g. the Swagger UI itself will initiate the authentication request toward the configured OIDC server. And your server application needs to be configured to handle the authentication itself.  The Swagger UI here just behaves as a client according to the specification and what the developers has implemented in it.

I think this is a non actionable issue for `utoipa` and is not in scope of `utoipa` itself.
