### ISSUE TITLE
Swagger-UI and default petstore example

### ISSUE THREAD

**Issue by clearydude** [juhaku/utoipa#83]
This lib is awesome but I'm having a hard time getting the swagger-ui part to do what I need. Is there any configuration I can set so that the `swagger-ui` [endpoint](https://github.com/juhaku/utoipa/blob/master/examples/todo-actix/src/main.rs#L55) displays my generated swagger doc vs displaying the petstore example? I've been able to see my generated swagger-ui by using the explore button and navigating to the path but I'd really like to serve my doc up by default and I'm not sure if I can do that with this lib. Thanks!

ETA: I have tried `swagger-ui/api-doc/openapi.json` but that just gets me a 404

**Comment by juhaku** [comment]
Yeah maybe the docs are not as clear as they could be and would need some care but it actually is and it is super simple :sweat_smile: 
```rust
            .service(
                SwaggerUi::new("/swagger-ui/{_:.*}")
                    .url("/api-doc/openapi.json", ApiDoc::openapi()),
            )
```
The url provided to `SwaggerUI::new("...")` exposes Swagger UI from root of the server.
Similarly the `url("/api-doc/openapi.json" ...)` exposes `openapi.json` from root of the server.

So if server runs at `localhost:8080` then the swagger-ui is `localhost:8080/swagger-ui/` and the openapi.json is `localhost:8080/api-doc/openapi.json`

But weird thing is that it shows the petstore example. It should initially show the correct schema in the Swagger UI. Atleast if I run the example it does so. You can also make sure the run `cargo clean` and update to latest versions available from `utoipa` `utoipa-gen` and `utoipa-swagger-ui`.

![image](https://user-images.githubusercontent.com/26358664/163475229-ccbe9a98-da6d-49bf-81d7-2108a4251dd1.png)

**Comment by clearydude** [comment]
I tried to run `cargo clean` and then run the example again and for some reason I'm still getting the petstore page as default. This is both for my own project and when just trying to run the `todo-actix` example in this repo. 
![Screen Shot 2022-04-18 at 11 25 50 AM](https://user-images.githubusercontent.com/6622501/163832019-ee3da2fb-140c-4a3d-a7f4-b567b5c43823.png)
![Screen Shot 2022-04-18 at 11 28 19 AM](https://user-images.githubusercontent.com/6622501/163832024-07a08873-7665-44e2-ba20-890544f889a9.png)

**Comment by juhaku** [comment]
Have you tried to remove the cache from your browser? Or with incognito mode? Because that is just surreal :O There might have been a glitch in some of my releases where the swagger-ui is not loaded with correct config but it should be fine with current releases.

Or is there issue with the utoipa-swagger-ui `build.rs` itself? Oh snap.. Which system are you running? I just remembered that the utoipa-swagger-ui `build.rs` needs `sed` in your system. freak I need to remove the need for it I'll do it asap.

**Comment by juhaku** [comment]
This PR should fix the issue you are encountering. Sorry for inconvenience.

**Comment by juhaku** [comment]
You can try now with newest versions from master and to run the todo-actix example.

**Comment by clearydude** [comment]
@juhaku Definitely fixed now! Thanks :)
