### ISSUE TITLE
Generated openapi properties is not in order

### ISSUE THREAD

**Issue by marcustut** [juhaku/utoipa#832]
I have the following struct

```rs
    #[derive(Debug, Default, serde::Deserialize, utoipa::ToSchema)]
    pub struct CreateBucketObjectRequest {
        pub path: String,
        #[schema(format = Binary)]
        pub file: Vec<u8>,
    }
```

Because this is used for `multipart/form-data`, I need the `file` property to be the last. However, when the OpenAPI specs was generated, `file` became the first and `path` became the last. This caused RapiDoc to render the `file` field at first.

```json
      "CreateBucketObjectRequest": {
        "type": "object",
        "required": [
          "path",
          "file"
        ],
        "properties": {
          "file": {
            "type": "string",
            "format": "binary"
          },
          "path": {
            "type": "string"
          }
        }
      },

```

<img width="968" alt="Screenshot 2024-01-03 at 6 58 41 PM" src="https://github.com/juhaku/utoipa/assets/59773847/ebf0e918-7509-479e-93bf-46e8cbfb07fe">

**Comment by juhaku** [comment]
Do you have the feature flag `preserve_order` enabled? That should actually do the trick for schema properties.

**Comment by marcustut** [comment]
Thanks! That indeed solved the issue for me, sorry for not noticing this feature flag in the first place, closing this now
