### ISSUE TITLE
utopia-swagger-ui tainted by MPL-2

### ISSUE THREAD

**Issue by neoeinstein** [juhaku/utoipa#834]
Hello, I wanted to raise a note that this crate currently has a transitive dependency on `option-ext`. That library is MPL-2, a copyleft license. The `option-ext` dependency is brought in via `rust-embed` > `shellexpand` > `dirs`. The maintainer of `dirs` has [explicitly stated](https://github.com/dirs-dev/dirs-sys-rs/issues/21) that they added a dependency on `option-ext` for the express purpose of tainting the use of `dirs` with MPL-2, which thus taints any use of `utopia-swagger-ui`. I have [filed a ticket with shellexpand](https://gitlab.com/ijackson/rust-shellexpand/-/issues/10) to recommend using an alternate dependency such as `etcetera`, which does not suffer from this tainting issue, and [an issue with rust-embed](https://github.com/pyrossh/rust-embed/issues/231) so that they can depend on a non tainted version when available.

**Comment by juhaku** [comment]
Oh snap, good for noticing, I'll hope that it will get fixed in the upstream. Otherwise there is a need to find some sort of alternatives for the support of Swagger UI.

**Comment by juhaku** [comment]
Though master has a version which does not rely on `interpolate-folder-path` feature flag any more thus there will not be `shellexpand` dependency either in the tree. I guess this makes this resolved.

**Comment by juhaku** [comment]
This solves the issue https://github.com/juhaku/utoipa/pull/828.

**Comment by neoeinstein** [comment]
Wonderful! Glad to hear that removes the transitive dependency.
