### ISSUE TITLE
Deserialising specification files fails everytime

### ISSUE THREAD

**Issue by auguwu** [juhaku/utoipa#843]
I'm trying to deserialize a [`OpenApi`](https://docs.rs/utoipa/*/utoipa/openapi/struct.OpenApi.html) object to build a crate that will generate types from a OpenAPI spec file, I tried with different specs (even one generated from this crate):

* https://youtrack.jetbrains.com/api/openapi.json
* https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json
* https://raw.githubusercontent.com/charted-dev/charted/main/assets/openapi.json - this one was generated with utoipa.

and it fails with:

```shell
# data did not match any variant of untagged enum RefOr
```

or

```shell
# missing field `headers`
```

I made a [reproduction repository](https://github.com/auguwu/utopia-refor-repro) that the maintainers can try and see what is going on?

**Comment by juhaku** [comment]
@auguwu 
The utoipa 4.x.x had at least issues with deserializing back already serialized openapi.json. This hopefully has been "fixed" with utoiopa 5.0.0 release.

**Comment by auguwu** [comment]
@juhaku I’ll try it again with utopia v5 and see if any issues arise.

**Comment by juhaku** [comment]
Thanks, hope it does solve the issues, but if not I'll take a look at schemas and see if there is something that can be done to fix this. These kinds of issues are a bit annoying and hard to debug because it radiates from serde which silently just allows json to be deserialized even if it did encounter issues on the way.

**Comment by auguwu** [comment]
So far, both of the OpenAPI documents I wanted to use are only OpenAPI 3.0 and utoipa 5 doesn't support it so I'll close this for now, but one project that I do use utopia will fail if no `type` is avaliable for `RefOr`, which I have made an issue in #1192, so I'll close this issue.
