### ISSUE TITLE
Add flexibility to `utoipa-swagger-ui`  build process

### ISSUE THREAD

**Issue by oscar6echo** [juhaku/utoipa#844]
First I would like to stress how much I appreciate this lib and the effort put in it :pray: 

It is great and I have been experimenting and adapting it to a corporate context.  
Doing so I found that the build process could be made more flexible in order to:
+ allow other versions of [swagger-ui](https://github.com/swagger-api/swagger-ui/tags)
+ allow overwrite of files in `swagger-ui/dist`

While not everybody needs that sort of flex, it would certainly help some users, like me, while keeping the defaults unchanged.  
To propose a solution, I'll make a PR.

**Comment by oscar6echo** [comment]
Here is the PR: https://github.com/juhaku/utoipa/pull/845

Happy to discuss it.

Pls note that in the meantime it is already used in a corp environment :+1:

**Comment by juhaku** [comment]
This good addition, I have actually been wondering that something like this could be good addition but just haven't gone the extra mile to implement it.
