### ISSUE TITLE
Swagger UI returns 404 when renaming the package

### ISSUE THREAD

**Issue by TxMat** [juhaku/utoipa#847]
Hi,

I found this issue while renaming one of my package that was using a placeholder name. I've also renamed the folder it was in changing the path. Oddly enough rapidoc and redoc are not affected.

This is a minor issue but worth mentioning.

The fix was to totally delete target and recompile from scratch as recompilation of the bin even with changes does not fix the issue.

**Comment by juhaku** [comment]
`utoipa-swagger-ui` will use `build.rs` to setup and configure stuff for itself. It might be that the rust compiler keeps hold of some cached values from target dir even in case of renaming a package. Thus this indeed might happen. Though yes `cargo clean` should do the trick. 

Nevertheless good shout out if someone else wonders as well. Yet this issue itself is a non actionable and there is nothing that could be done for this.
