### ISSUE TITLE
SwaggerUI routing for subpath

### ISSUE THREAD

**Issue by dvu714** [juhaku/utoipa#856]
Is there a setting for me to set to properly route to swagger ui hosted in a subpath of a domain with utoipa swagger ui for axum?  SwaggerUI seems to route calls for` /api-docs/openapi.json` to the root domain, i.e. `https://domain.com/api-docs/openapi.json`.

My api service is hosted in a subpath of a domain, i.e. `https://domain.com/foo/`. 
I'm looking for swagger ui to get `/api-docs/openapi.json` from `https://domain.com/foo/api-docs/openapi.json`

**Comment by juhaku** [comment]
You should be able to provide a custom path for the api docs urls via config for the Swagger UI:
```rust
let config = Config::from("/api/foobar/api-docs/openapi.json");
let swagger = SwaggerUi::new("/swagger-ui/{_:.*}")
     .url("/api-docs/openapi.json", ApiDoc::openapi())
     .config(config); // <-- change the default config
```
See more details here: https://github.com/juhaku/utoipa/issues/731#issuecomment-1688043311

**Comment by juhaku** [comment]
Closing as solved. Also this issue might be useful: #842. There is lot of discussion about serving the `utoipa` via reverse proxy. This can be opened if there is more to this.
