### ISSUE TITLE
Could utoipa support nesting of ApiDoc definitions?

### ISSUE THREAD

**Issue by qrilka** [juhaku/utoipa#872]
axum support nesting for routers - https://docs.rs/axum/latest/axum/struct.Router.html#method.nest and it helps to structure large APIs a bit. But if we use utopia for the same API one needs to pass every path and nested type into #[derive(OpenApi)] in `#[openapi]`. Or is it intentional that API doc is describe as a whole?

**Comment by qrilka** [comment]
Some way around this is to use https://docs.rs/utoipa/latest/utoipa/openapi/struct.OpenApi.html#method.merge but that means that:
* modifiers will need to be invoked manually as derive macros is not used anymore
* merging shouldn't be done in top-level API doc if one wants to use spec info generated from Cargo data

**Comment by qrilka** [comment]
And one extra detail: one needs to repeat higher level route prefix in the `path` part of `#[utoipa::path(..)]`

**Comment by justin13888** [comment]
I'm also facing the exact use case as @qrilka with Axum and Utoipa. By any chance, is there any resolution currently by any chance while using nest() method in the Axum router?

**Comment by AceofSpades5757** [comment]
I'm also struggling to overcome these issues with nesting.

**Comment by juhaku** [comment]
Related to #445

**Comment by juhaku** [comment]
Now there is coming implementation for nesting feature that allows nesting `OpenApi`s similarly to the axum nest function in PR #930

**Comment by LucasOe** [comment]
Has the the `nest(...)` method been removed? It is not listd in the [docs](https://docs.rs/utoipa/latest/utoipa/derive.OpenApi.html) and I can't get it to work.
