### ISSUE TITLE
Allow multiple tags

### ISSUE THREAD

**Issue by Sytten** [juhaku/utoipa#880]
Hi!
Right now we can only have one `tag = "something"` per path, but the spec is an array so there is no spec reason not to allow multiple.
We could add a `tags = ["1", "2"]` or multiple `tag = "1", tag = "2"`. Unsure what would be better.

**Comment by juhaku** [comment]
Sure this could be allowed. I have been thinking this but it just have never got there to be implemented.

**Comment by juhaku** [comment]
@Sytten Now there is one implementation available for this that behaves according to the needs of: https://github.com/juhaku/utoipa/issues/792 where the `tags` attribute allows providing additional tags, where the default tag does not get overridden.
