### ISSUE TITLE
[Feature Request] Custom Args and More

### ISSUE THREAD

**Issue by i007c** [juhaku/utoipa#884]
this is a very nice crate. however it lacks some feature such as adding custom variables to the schema and using them to add or remove items from the schema during the modify step. for example i put all of the user api in a file like `api/user.rs`. and every path in this file
will be under the `/user` path. so its kind of wired to add `context_url` for all the paths. its way nicer to just use a modifier.

im currently using the first servers values as my context url

```rs
#[derive(OpenApi)]
#[openapi(
    tags((name = "api::user")),
    paths(login, user_get), 
    components(schemas(User)),
    servers((url = "/user")),
    modifiers(&UpdatePaths)
)]
pub struct ApiUserDoc;
```

and i also add the `ApiUserDoc` tags to all the paths under it.

some custom arguments would be very use full for automaticly adding or removing thigs from each path or the hole schmea

**Comment by juhaku** [comment]
Like what you have in mind? In the coming 5.0.0 release other OpenApis can be nested to single one with context path and additionally provided with tags for the OpenApi to be nested. Modifier is exactly the way to provide some custom args which does not have macro syntax support. Also the modifier syntax could be made available for paths and schemas maybe :thinking:

**Comment by i007c** [comment]
to be honest that was like 7 months ago. and at that time i already made a "work around" so i dont how any issue anymore.
