### ISSUE TITLE
Is it possible to accept multiple content-types for requests?

### ISSUE THREAD

**Issue by rodorgas** [juhaku/utoipa#896]
OpenAPI 3 allows describing multiple accepted content-types for a request ([first example on this link](https://swagger.io/docs/specification/describing-request-body/)).

Is it possible using utoipa?

I'd like to make an endpoint accepting both `application/json` and `application/x-www-form-urlencoded`. I implemented it in Actix using two handlers and guards, but I don't see how to document it in utoipa.

**Comment by LockedThread** [comment]
I am also interested in this

**Comment by juhaku** [comment]
This is a missing feature, that has been implemented for responses but not for request body. This is something that should be added.

**Comment by LockedThread** [comment]
@rodorgas I was porting over my old Go Gin-based api to Rust using Axum. By default, Gin can accept multipart or json body for all requests. 

By any chance, do you have code for Axum that does something similar? I was looking at using a Tower service to handle this but the dev experience overhead would be too high.

**Comment by juhaku** [comment]
As a matter of fact, I had forgotten about this but there is a PR for the functionality: https://github.com/juhaku/utoipa/pull/876, it just needs some polish and it is done.
