### ISSUE TITLE
Can't derive `ToSchema` for maps whose value type is an `Option<Enum>`

### ISSUE THREAD

**Issue by swwu** [juhaku/utoipa#897]
E.g. the following fails with a compile error:

```rust
#[derive(utoipa::ToSchema)]
pub enum InnerEnum {
    A(String),
    B(f64),
}

// this works
#[derive(utoipa::ToSchema)]
pub struct OkOuter1 {
    map: Option<InnerEnum>,
}
// this works
#[derive(utoipa::ToSchema)]
pub struct OkOuter2 {
    map: HashMap<String, InnerEnum>,
}

// this fails
#[derive(utoipa::ToSchema)]
pub struct BadOuter {
    map: HashMap<String, Option<InnerEnum>>,
}
```
The (presumably) same issue also occurs for `BTreeMap<String, Option<InnerEnum>>`.

This seems to be a particular edge case of jsonschema type composition, as this workaround, which would describe an identical JSON-serialized document, works fine:

```rust
pub struct OptionInnerEnum(Option<InnerEnum>);
#[derive(utoipa::ToSchema)]
pub struct WorkaroundOuter {
    map: HashMap<String, OptionInnerEnum>,
}
```

**Comment by juhaku** [comment]
@swwu Ah, I guess there is no default `ToSchema` implementation for type `Map<Key, Option<T>>` this could be added in future and is super simple to add.
