### ISSUE TITLE
Schema name configuration

### ISSUE THREAD

**Issue by squadgazzz** [juhaku/utoipa#899]
According to [the docs](https://docs.rs/utoipa/latest/utoipa/derive.ToSchema.html#struct-optional-configuration-options-for-schema), there is no way to use a different from the struct name in the openaapi doc, like:
```
#[derive(ToSchema)]
#[schema(name = "Dog")]
pub struct DogSchema;
```
Which should generate schema `Dog` instead of `DogSchema`.

**Comment by juhaku** [comment]
> According to [the docs](https://docs.rs/utoipa/latest/utoipa/derive.ToSchema.html#struct-optional-configuration-options-for-schema), there is no way to use a different from the struct name in the openaapi doc, like:
> 
> ```
> #[derive(ToSchema)]
> #[schema(name = "Dog")]
> pub struct DogSchema;
> ```
> 
> Which should generate schema `Dog` instead of `DogSchema`.

True, there is no separate attribute for that but `as = Dog` should be possible. E.g.
```rust
#[derive(ToSchema)]
#[schema(as = Dog)]
pub struct DogSchema;
````

**Comment by juhaku** [comment]
Closing due inactivity. Can be reopened if deemed necessary.
