### ISSUE TITLE
Shouldn't `merge` take Operations into account?

### ISSUE THREAD

**Issue by jcrossley3** [juhaku/utoipa#907]
https://github.com/juhaku/utoipa/blob/19fb23ccb57dbb3fd9b103963464d6a4a6c2157a/utoipa/src/openapi.rs#L182

It seems like I should be able to merge a doc with the same path as long as the operation doesn't conflict. I should be able to have `/api/v1/foo` for both a POST and a GET, right?

**Comment by juhaku** [comment]
Most likely yes. It might be that that logic hasn't thought fully when it was first implemented.
