### ISSUE TITLE
Can't leak crate-private type error

### ISSUE THREAD

**Issue by andresmargalef** [juhaku/utoipa#918]
<img width="1017" alt="image" src="https://github.com/juhaku/utoipa/assets/6145226/1602be63-45f5-40bb-bc15-afb2b7cb8ccc">

**Comment by juhaku** [comment]
Remove that package from the index, and run `cargo update` on your project.

**Comment by andresmargalef** [comment]
The fix was upgrading from rust 1.70 to 1.78

**Comment by juhaku** [comment]
Also seems to work at least on master with 1.75 at master. This seems to be related to #926 #908
