### ISSUE TITLE
Build script should respect the Cargo `http.cainfo`

### ISSUE THREAD

**Issue by ranger-ross** [juhaku/utoipa#934]
When fetching Swagger UI in the [`build.rs`](https://github.com/juhaku/utoipa/blob/master/utoipa-swagger-ui/build.rs#L173) I think we should configure the reqwest client to respect the Cargo [`http.cainfo`](https://doc.rust-lang.org/cargo/reference/config.html#httpcainfo) setting.
This would be useful as sometimes various security software deployed by companies will use their own CA.

I think this should be a fairly small change and I would be happy to open a PR if you are up for it.

**Comment by juhaku** [comment]
Yeah, this is probably a good idea. Though should be optional if possible.
