### ISSUE TITLE
utoipa-swagger-ui Release 7.0.2

### ISSUE THREAD

**Issue by mklntf** [juhaku/utoipa#937]
Hello,

I wonder if we could have a release 7.0.2 of utoipa-swagger-ui  which allows specifying the `SWAGGER_UI_DOWNLOAD_URL` starting with `file://`. At the moment I can't upgrade to 7.0.1 since I package my application with the nix package manager, which doesn't allow downloads during build. But I could hand over the downloaded zip to the build process using `file://`.

This functionality was added in the recent change https://github.com/juhaku/utoipa/pull/923

Thank you.

**Comment by juhaku** [comment]
Sure, I was wondering that same thing actually that the release could be made from the `utoipa-swagger-ui`.

**Comment by juhaku** [comment]
https://github.com/juhaku/utoipa/releases/tag/utoipa-swagger-ui-7.0.2 Should be available shortly :gift:

**Comment by mklntf** [comment]
Great, working for me! Thanks!

**Comment by juhaku** [comment]
Anytime, FYI there is now also a vendored version of Swagger UI. I noticed that there is a need for such since the docs.rs is a sandbox and does not resolve names outside the specific addresses like crates.io.
