### ISSUE TITLE
Redoc invalid reference token with generics

### ISSUE THREAD

**Issue by scott-wilson** [juhaku/utoipa#939]
I'm running into a weird issue. When I go to the Redoc page for my API, I see the following error:

```
Invalid reference token: crate.api.v1.auth.Device
```

Here's the dependencies.

`Cargo deps`

```toml
axum = "0.7.5"
utoipa = { version = "4.2.3", features = ["chrono", "uuid", "axum_extras"] }
utoipa-redoc = { version = "4.0.0", features = ["axum"] }
```

`ApiDoc`

```rust
#[derive(OpenApi)]
#[openapi(
    paths(
        ...
    ),
    components(
        schemas(
            ...
            api::v1::auth::Device,
            ...
            db::entities::types::DevicePagination,
            ...
        )
    ),
)]
struct ApiDoc;
```

`Device`

```rust
#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize, ToSchema)]
pub struct Device {
    pub id: DeviceId,
    pub ip: IpAddr,
    pub is_blocked: bool,
    pub blocked_until: chrono::DateTime<chrono::FixedOffset>,
}
```

`Pagination`

```rust
pub trait Id:
    serde::Serialize + for<'a> serde::Deserialize<'a> + for<'a> utoipa::ToSchema<'a>
{
}

pub trait Entity:
    serde::Serialize + for<'a> serde::Deserialize<'a> + for<'a> utoipa::ToSchema<'a>
{
    type Id: Id;

    fn id(&self) -> Self::Id;
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[aliases(DevicePagination = Pagination<crate::api::v1::auth::Device>)]
pub struct Pagination<T: Entity> {
    pub next_id: Option<T::Id>,
    #[serde(bound(deserialize = "Vec<T>: Entity"))]
    pub data: Vec<T>,
}
```

I'm doing something wrong, but not sure what. I've added the `crate::api::v1::auth::Device` to the schema for the API doc, and that doesn't seem to improve it. Any help is appreciated.

**Comment by scott-wilson** [comment]
So, I think part of the problem is that while I can do the following:

```rust
#[derive(..., ToSchema)]
#[schema(as = api::v1::Foo)]
struct Foo {
    ...
}
```

It doesn't look like I can do the same with generics with aliases. I feel like if I'm able to somehow do something along the lines of

```rust
#[derive(..., ToSchema)]
#[schema(as = api::v1::Pagination)]
#[aliases(DevicePagination = Pagination<Device>)]
pub struct Pagination<T> {
    ...
}
```

Then this might work, but I've tried some variations of, and no dice so far.

**Comment by juhaku** [comment]
Oh, indeed you could use the `as = ..` attribute to alter the name under which it should be recognized within the OpenAPI spec. Here is link to example how it should work: https://github.com/juhaku/utoipa/issues/435#issuecomment-1405448818. In short if `as = ...` is used to change the name then that name must be used to refer to it wherever used. 

Though I am not sure how well it plays with the generic and the `#[aliases(...)]` thing. That probably is a one good issue worth investigating. And if I remember right while `aliases` allows path expression on right hand side it wont really be used in name resolution. Also the left hand side `name` attribute just creates a `type ...` alias with that name thus not really allowing path expression there either.

The generics are bit of a pain in the ass when it come to the `utoipa`s architectural decisions. But perhaps in future these also can be improved.

**Comment by juhaku** [comment]
> It looks like the alias is both used for the Rust side for the type alias, and also for the OpenAPI namespace. I guess I'm expecting that the types would be responsible for the namespace, and everything else would use those namespace instead of guessing based off of Rust path.

Yeah, the possibility of namespace being resolved directly without one writing it manually in referencing places could be investigated sometime in future. Hard part of that is that because response and request bodies can primitive types as well an they do not implement `ToSchema`  trait.

**Comment by juhaku** [comment]
There is new work coming up with correct generics implementation #1034

**Comment by juhaku** [comment]
> I think I figured it out. I imported Device in the same namespace as the Pagination, then removed the crate::api::.... It looks like the alias is both used for the Rust side for the type alias, and also for the OpenAPI namespace. I guess I'm expecting that the types would be responsible for the namespace, and everything else would use those namespace instead of guessing based off of Rust path.

This is changed in the PR above, and later on the types are responsible for the possible prefix.
