### ISSUE TITLE
Schema title not supported on basic enums

### ISSUE THREAD

**Issue by scrous** [juhaku/utoipa#954]
I would like to add some title descriptions to enum values, however it only works on enum structs not basic enum values.

For example, if I try this:
```rust
#[derive(ToSchema)]
pub enum SomeEnum {
    #[schema(title="title")]
    A,
    B,
    C
}
```

I get `unexpected attribute: title, expected any of: rename`

But if I have:
```rust
#[derive(ToSchema)]
pub enum SomeEnum {
    #[schema(title="title")]
    A,
    B(String),
    C
}
```

Then I get the following options: `any of: title, rename_all, rename, example`

Would it be possible to add title to the first example. We have a list of abbreviations as enums and it would be helpful to add what each field means.

**Comment by juhaku** [comment]
Sure, can be added. Also PR:s are welcome.

**Comment by juhaku** [comment]
@scrous As I took a further look on this matter. It is not possible because unit type enums are represented in OpenAPI as enums known to OpenAPI spec and JSON schema. See here: https://json-schema.org/understanding-json-schema/reference/enum. 

That is the enum typically is a single value of predefined constants but in Rust this this not necessary the case. Thus the so called complex enum type does translate to OpenAPI OneOf type which in itself does support different kind of attributes.

In order to achieve this functionality there would be a need to completely change the representation of the enum based on presence of the `title` attribute which is not very feasible.

**Comment by scrous** [comment]
@juhaku Thanks for looking into this. 
Ah okay, that is unfortunate, I see there has been much discussion around this topic: https://github.com/json-schema-org/json-schema-spec/issues/57 , but the only current solution is to use oneOf + const, which will need a big rework.

However, then I found this recommending putting the information in the enum's description. https://swagger.io/docs/specification/data-models/enums/ which looks like a nicer workaround, without impacting the enum.

I think this can remain closed. But here is a workaround for displaying the enum descriptions in the description if someone stumbles on this issue:
_You need itertools and strum for this to work, you can also replace enum debug + format with strum display_
```rust
use itertools::Itertools;
use serde_json::json;
use strum::{EnumMessage, IntoEnumIterator};
use strum_macros::{EnumIter, EnumMessage};
use utoipa::openapi::ObjectBuilder;

#[derive(EnumIter, EnumMessage, Debug)]
pub enum SomeEnum {
    #[strum(message = "Alpha")]
    A,
    #[strum(message = "Bravo")]
    B,
    #[strum(message = "Charlie")]
    C,
}

impl<'__s> utoipa::ToSchema<'__s> for SomeEnum {
    fn schema() -> (
        &'__s str,
        utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>,
    ) {
        let values = SomeEnum::iter()
            .map(|v| (format!("{v:?}"), v.get_message().unwrap_or("")))
            .collect::<Vec<_>>();

        let descriptions = values
            .iter()
            .map(|(v, description)| format!("* {v} - {description}"))
            .join(" \n ");

        (
            "SomeEnum",
            ObjectBuilder::new()
                .schema_type(utoipa::openapi::SchemaType::String)
                .description(Some(format!("List of possible values: \n {descriptions}")))
                .enum_values(Some(values.into_iter().map(|(v, _)| v)))
                .into(),
        )
    }
}
```

Which outputs as follows using scalar:
![image](https://github.com/user-attachments/assets/61b24f8e-f9e8-4ee3-adce-ca9a5230c7b1)
