### ISSUE TITLE
Content type not seted

### ISSUE THREAD

**Issue by Cheban1996** [juhaku/utoipa#965]
I have the next response `(status = 200, description = "Successfully download", content_type = "application/octet-stream"),`
but content_type not exist
<img width="435" alt="image" src="https://github.com/juhaku/utoipa/assets/11075696/9eea7af8-bb17-45b8-b4e2-284bd8284329">

But i expected
```
"200": {
     "description": "Successfully download",
     "content":
          "application/octet-stream": {}
}
```

**Comment by juhaku** [comment]
@Cheban1996 I assume this is due to it requiring some body before the type will actually render. This though probably needs some tuning in order to support just setting the `content-type` without the body itself.

**Comment by juhaku** [comment]
Duplicate for #779
