### ISSUE TITLE
examples  todo-actix can't run

### ISSUE THREAD

**Issue by zhengpanone** [juhaku/utoipa#967]
I copied the todo-actix demo, but it couldn't run. Cargo build couldn't be compiled. The error was **unexpected attribute, expected any of: handlers, components, modifiers, security, tags, external_docs, servers**, **no function or associated item named `openapi` found for struct `ApiDoc` in the current scope**
<img width="1119" alt="image" src="https://github.com/juhaku/utoipa/assets/32032104/d4d08b90-866f-4d21-b854-e2283ea52719">

**Comment by LucasOe** [comment]
The `nest` attribute has been added in the `5.0.0-alpha` version. The LTS is still 4.3.2, that's why you can't use it.

**Comment by BimaAdi** [comment]
@zhengpanone try use example based on your utoipa version, by changing tag on github repo
![utoipa tag](https://github.com/user-attachments/assets/2e6bc748-4603-44eb-befa-ce6c45dae64b)
