### ISSUE TITLE
Extension support for OpenApi struct e.g. x-tagGroups for redoc

### ISSUE THREAD

**Issue by michelbieleveld** [juhaku/utoipa#968]
Hello, how would I be able to make use of the x-tagGroups in combination with redoc ? 

[x-tagGroups](https://redocly.com/docs/api-reference-docs/specification-extensions/x-tag-groups)

**Comment by juhaku** [comment]
@michelbieleveld Unfortunately not at the moment, there is no extension field in OpenApi struct. This could be added in future though.
