### ISSUE TITLE
Utoipa path derive has conflict with axum-valid Valid for form

### ISSUE THREAD

**Issue by 1g0rkR** [juhaku/utoipa#971]
Hi there,

I am using both utoipa derive path and axum_valid::Valid for form. They both cannot work together.
```proc-macro panicked: called `Option::unwrap()` on a `None` valuerust-analyzer[macro-error](https://rust-analyzer.github.io/manual.html#macro-error)
custom attribute panicked
message: called `Option::unwrap()` on a `None` valuerustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B1%5D?******************)
utoipa_gen
proc_macro path
```

I would appreciate any support on it.

**Comment by juhaku** [comment]
@1g0rkR There is now at master a change #977 that might fix this issue as well. The PR fixes a similar issue https://github.com/juhaku/utoipa/issues/976.
