### ISSUE TITLE
Nullable $ref's should include type: object

### ISSUE THREAD

**Issue by JanzenJohn** [juhaku/utoipa#973]
when using an Option<T> in a struct with a custom type like this

```rs
#[derive(ToSchema)]
struct MyComponent {
  content: Option<MySubComponent>
}
```
it results in the the following openapi spec getting generated

```yaml
MyComponent:
  type: object
  properties:
    content:
      allOf:
      - $ref: '#/components/schemas/MySubComponent'
      nullable: true
```

but when trying use MyComponent in an example and verify the spec, i get the error `oas3-valid-media-example "nullable" cannot be used without "type"` which is fixed by changing the generated code to look like this

```yaml
MyComponent:
  type: object
  properties:
    content:
      type: object
      allOf:
      - $ref: '#/components/schemas/MySubComponent'
      nullable: true
```

**Comment by juhaku** [comment]
This issue will be solved in next coming version `5.0.0`.
