### ISSUE TITLE
Conditional nested APIs based on features

### ISSUE THREAD

**Issue by BSteffaniak** [juhaku/utoipa#975]
Hi, I'm trying to set up utoipa with an api that could have varying sub-apis, depending on the features that are enabled.

For example (rust pseudo code),
```
#[derive(utoipa::OpenApi)]
#[openapi(
    nest(
        #[cfg(feature = "auth-api")]
        (path = "/auth", api = auth::api::Api),
        #[cfg(feature = "downloader-api")]
        (path = "/downloader", api = downloader::api::Api),
        #[cfg(feature = "library-api")]
        (path = "/library", api = library::api::Api),
    ),
)]
struct ApiDoc;
```

Is there any way to achieve this capability?

I attempted to reverse engineer the #openapi macro to get what I needed using OpenApiBuilder, but hit a wall with the NestedApiConfig part of it.

Thanks!

**Comment by juhaku** [comment]
Macros cannot have nested macros. In order to nest conditionally based on feature flag you should have constant API to nest which is changed based on feature flag.
```rust
#[cfg(feature = "auth-api")]
#[derive(utoipa::OpenApi)]
#[openapi()]
struct NestedApi;

#[cfg(feature = "downloader-api")]
#[derive(utoipa::OpenApi)]
#[openapi()]
struct NestedApi;

#[derive(utoipa::OpenApi)]
#[openapi(
    nest(
        (path = "/api", api = NestedApi),
    ),
)]
struct ApiDoc;
```

Another way to do it is completely manually using the `OpenApi::nest` method. 

Or perhaps you could try to have all the APIs nested but the feature flag defines whether empty one will be nested instead of the one with all the paths and schemas.

```rust
#[cfg(feature = "auth-api")]
#[derive(utoipa::OpenApi)]
#[openapi(
    components(....),    
    paths(...),
)]
struct AuthApi;

#[cfg(not(feature = "auth-api"))]
#[derive(utoipa::OpenApi)]
#[openapi()]
struct AuthApi;

#[derive(utoipa::OpenApi)]
#[openapi(
    nest(
        (path = "/auth", api = AuthApi),
    ),
)]
struct ApiDoc;
```

**Comment by BSteffaniak** [comment]
The reason a constant API with flags to determine the nested API would not work very well for my use case is because I would have to define every permutation of the 12 APIs that would be able to be enabled (i.e. allow for enabling `downloader-api, auth-api, player-api`, but not the other 9).

The `OpenApi::nest` is exactly what I was looking for.

I was able to achieve the result I wanted like this:
```
let api = ApiDoc::openapi();

#[cfg(feature = "auth-api")]
let api = api.nest("/auth", auth::api::Api::openapi());
#[cfg(feature = "downloader-api")]
let api = api.nest("/downloader", downloader::api::Api::openapi());
#[cfg(feature = "player-api")]
let api = api.nest("/player", player::api::Api::openapi());

...
```

Thanks!
