### ISSUE TITLE
Problems with multiple generics in actix?

### ISSUE THREAD

**Issue by DenuxPlays** [juhaku/utoipa#976]
Hey,

I recently wanted to use a new validation library in my backend.
Unfortunately Utopie panics when executing the path macro.

I do not know if the issue is here or at the 3rd party library.
More information and an example to reproduce can be found here: https://github.com/ranger-ross/actix-web-validation/issues/16

**Comment by juhaku** [comment]
Fix is on the way for this good finding and thanks for reporting it here as well.

**Comment by DenuxPlays** [comment]
> Fix is on the way for this good finding and thanks for reporting it here as well. 

Thanks 
Hope a new version is released soon

**Comment by juhaku** [comment]
@DenuxPlays heres the next pre-release with the fix: https://github.com/juhaku/utoipa/releases/tag/utoipa-5.0.0-alpha.1
