### ISSUE TITLE
[Unexpected] Examples are rerendered

### ISSUE THREAD

**Issue by bhoudebert** [juhaku/utoipa#98]
I added some data examples on my manual schema (Uuid, type Alias etc) through the `impl Modify` behavior, one of this example could be something like this    
```Rust
/// random values, could even be generated from proptest/quickcheck for struct
uuid_p.example = Some(serde_json::Value::String(Uuid::new_v4().to_string()));
```

Surprisingly I found that each time I requested the `openapi.json` file, my examples are differents (this could come from the use of `Modify` I did not dig that deeper).

IMHO this is not a `big` issue but still it should not be the case.

**Comment by juhaku** [comment]
If you have api doc struct like following
```rust
#[derive(OpenApi)]
#[openapi(...modifiers(&MyModifier)....)]
struct ApiDoc;
```
And everytime `ApiDoc::openapi()` function gets called the `MyModifier` and similarly all modifiers gets called again. 

According to examples in in `utoipa/examples` this situation should not occur in `todo-actix` and `rocket-todo` but `warp` and `tide` examples indeed have this issue. 

If you want to have the schema be same always then you need to store it to local variable first `let doc = ApiDoc::openapi()` and then use the stored variable to serve the spec.

**Comment by bhoudebert** [comment]
Ok my bad, I did tried this but I misplace the `let doc` inside the `HttpServer::new(move || {` and after few tests I discover this result in one `apidoc generation` per worker (maybe interesting to be mentioned or updated in the tests?)

Glad to discover that anything inside the HttpServer is called once per worker!

Thanks.

**Comment by juhaku** [comment]
True.. This is indeed actix-web specific thing with that `HttpServer::new(...)` closure thing. I'll update the example also to mention this later on before next release.
