### ISSUE TITLE
Not possible to use `x-internal` flag

### ISSUE THREAD

**Issue by IvanProg00** [juhaku/utoipa#980]
I have 2 types of APIs: _internal_ and _external_. In Redoc, there is [an `x-internal` flag](https://redocly.com/docs/cli/guides/hide-apis), but I haven't found a way to add this flag in `utoipa`.

Do you have any plans to add it?

**Comment by juhaku** [comment]
The path operation supports extensions as seen in the docs: https://docs.rs/utoipa/latest/utoipa/openapi/path/struct.Operation.html#structfield.extensions but there is no way to add them via `#[utoipa::path]` macro call. You must modify the generated API manually before serving it as shown in the README.md https://github.com/juhaku/utoipa?tab=readme-ov-file#modify-openapi-at-runtime.
