### ISSUE TITLE
`ToSchema` not implemented for primitive if the primitive is behind a type alias

### ISSUE THREAD

**Issue by r0ck37c0d3r** [juhaku/utoipa#984]
You could test this trivially in an example from the repo:

`utoipa/examples/todo-axum/src/main.rs`: modify 
```rust
    /// Item to do.
    #[derive(Serialize, Deserialize, ToSchema, Clone)]
    pub(super) struct Todo {
        id: i32,
        #[schema(example = "Buy groceries")]
        value: String,
        done: bool,
    }
```

to 
```rust
    type OurNumber = u32;

    /// Item to do.
    #[derive(Serialize, Deserialize, ToSchema, Clone)]
    pub(super) struct Todo {
        id: OurNumber,
        #[schema(example = "Buy groceries")]
        value: String,
        done: bool,
    }
```

First, Swagger Docs will throw an error
```
Could not resolve reference: Could not resolve pointer: /components/schemas/OurNumber does not exist in document
```
and `Todo` will show a missing Schema component for its `id` field

If you try to add new type alias to the `ApiDoc` annotation like this:
```
        components(
            schemas(todo::Todo, todo::TodoError, todo::OurNumber)
        ),
```

you'll get
```rust
error[E0277]: the trait bound `u32: ToSchema<'_>` is not satisfied
   --> src/main.rs:31:50
    |
31  |             schemas(todo::Todo, todo::TodoError, todo::OurNumber)
    |                                                  ^^^^ the trait `ToSchema<'_>` is not implemented for `u32`
```

Expected behaviour: well I'd expect `ToSchema` to be implemented for primitives. 

Is there a way to work around this?

**Comment by juhaku** [comment]
This is not possible as explained in the README.md file: https://github.com/juhaku/utoipa?tab=readme-ov-file#how-to-use-rusts-type-aliases. 

That would need some mechanism to provide custom registry for type mapping before the macro executes. But as of now there is no such way to do that.

**Comment by juhaku** [comment]
@r0ck37c0d3r There is now coming a new PR which adds global type aliases for `utoipa` #1048.
