### ISSUE TITLE
Using utoipa-swagger-ui with rocket 0.4.10

### ISSUE THREAD

**Issue by Boscop** [juhaku/utoipa#99]
Hi,
when using `utoipa-swagger-ui` with rocket 0.4.10, I'm getting an error:
```
error[E0277]: the trait bound `Vec<Route>: std::convert::From<SwaggerUi>` is not satisfied
   --> web/src/cli/web.rs:486:13
    |
484 |         rocket.mount(
    |                ----- required by a bound introduced by this call
485 |             "/",
486 |             SwaggerUi::new("/swagger-ui/<_..>").url("/api-doc/openapi.json", ApiDocV1::openapi()),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<SwaggerUi>` is not implemented for `Vec<Route>`
    |
    = help: the following implementations were found:
              <Vec<T, A> as std::convert::From<VecDeque<T, A>>>
              <Vec<T, A> as std::convert::From<std::boxed::Box<[T], A>>>
              <Vec<T> as std::convert::From<&[T]>>
              <Vec<T> as std::convert::From<&mut [T]>>
            and 9 others
    = note: required because of the requirements on the impl of `Into<Vec<Route>>` for `SwaggerUi`
note: required by a bound in `rocket::Rocket::mount`
   --> /usr/src/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.10/src/rocket.rs:515:21
    |
515 |     pub fn mount<R: Into<Vec<Route>>>(mut self, base: &str, routes: R) -> Self {
    |                     ^^^^^^^^^^^^^^^^ required by this bound in `rocket::Rocket::mount`
```
I see that `utoipa-swagger-ui` depends on rocket 0.5.0-rc.1:
https://github.com/juhaku/utoipa/blob/6cec1029f57e3fd81d6b2c7e4680c34e482060e6/utoipa-swagger-ui/Cargo.toml#L22

Is it still possible to use it with rocket 0.4.10 somehow?

I tried 
```toml
[patch.crates-io]
rocket = "0.4.10"
```
to replace the dependency, but I'm still getting the same error.

**Comment by juhaku** [comment]
Yes rocket version `0.4.x` is not supported unfortunately at the moment with the `utoipa-swagger-ui` Also it is not super straightforward to add support for  version`0.4` since there are breaking changes between the `0.4.x` and `0.5.x`. It would require double work to have support for both of release trains and honestly would be quite cumbersome.

**Comment by juhaku** [comment]
FYI @Boscop 

Now there is an hello world example with  rocket `0.4` version. It is possible to use `utoipa` and `utoipa-swagger-ui` with rocket `0.4` serie but it needs bit more manual work. The simple syntax sugar (`.mount("/", SwaggerUI::new(...))`) wont be supported for rocket version `0.4` see the reasoning below.

See the example here: https://github.com/juhaku/utoipa/tree/master/examples/rocket-0_4-hello. 

**Reasoning**
1. It is impossible to define multiple versions simultaneously in cargo from one specific dependency.
2. Most of the rocket users seems to be using the 0.5 serie at least according to amount of downloads.
3. Between `0.4` and `0.5` there are breaking changes in rocket framework itself.
