### ISSUE TITLE
SecurityScheme: Logical OR for OAuth2

### ISSUE THREAD

**Issue by KristinaB162** [juhaku/utoipa#992]
As described here https://github.com/OAI/OpenAPI-Specification/discussions/3001#discussioncomment-3456275, scopes can be expressed in different ways to illustrate logical relationships in an OpenApi Spec.

It is currently not possible to generate a logical OR in the permissions with the utoipa generator. When specifying multiple permissions in the path attribute macro, these are always linked to a logical AND.

I tried: 
`security(("OAuth2" = ["A", "B"]))`

and 
```
security(("OAuth2" = ["A"]))
security(("OAuth2" = ["B"]))
```

What I get:
```
security:
  - oauth2:
    - A
    - B
```

What I want:

```
security:
  - oauth2:
    - A
  - oauth2:
    - B
```

</br>
Is there a way to generate the logical OR? 

Thanks in advance!

**Comment by juhaku** [comment]
This should be possible, and is added here 7493c331c1e8ae93f80c97c44d6ab834bebb42e5 #813. It seems that it is not well documented in the docs.

**Comment by KristinaB162** [comment]
But I need the permissions under the same security scheme, i.e. both under OAuth2, just linked as a logical OR. Otherwise the authentication with the Swagger UI is not work properly.

**Comment by juhaku** [comment]
> But I need the permissions under the same security scheme, i.e. both under OAuth2, just linked as a logical OR. Otherwise the authentication with the Swagger UI is not work properly.

So if I understand right, the Swagger UI does require the name of the security schema to be the same in order the Oauth2 authentication work properly. That is not possible due to the current way of implementation and would require technical changes in order to allow "duplicate" keys.

**Comment by KristinaB162** [comment]
I'm sorry, I used the Swagger UI more as an example.

But my main point is that it is spec-compliant with the duplicate keys and that expresses a logical OR. I would appreciate it if you would add a function that allows me to generate this.

**Comment by juhaku** [comment]
Right, sure this is something that can be experimented in future. But if landed it will come to the next stable release which eventually will be 5.0.0. However there will be time to time new beta releases of the coming 5.0.0 version. 

PR:s are welcome if one wants to contribute to the development of the utoipa :slightly_smiling_face:

**Comment by juhaku** [comment]
@KristinaB162 This is possible by the current implementation already. Take for example following code:
```rust
    #[derive(Default, OpenApi)]
    #[openapi(security(
            ("oauth" = ["a"]),
            ("oauth" = ["b"]),
        ))]
    struct ApiDoc;
```
You get the output:
```json
{
  "info": {
  },
  "openapi": "3.1.0",
  "paths": {},
  "security": [
    {
      "oauth": [
        "a"
      ]
    },
    {
      "oauth": [
        "b"
      ]
    }
  ]
}
```
