### ISSUE TITLE
Uint8 format lead to macro error

### ISSUE THREAD

**Issue by so-schen** [juhaku/utoipa#996]
## version v4.2.2

utoipa = { version = "4.2", features = ["preserve_order", "non_strict_integers"] }

error: unexpected format: UInt8, expected one of: Int32, Int64, Float, Double, Byte, Binary, Date, DateTime, Password
  --> sosmr/src/lifecycle/epoch_id.rs:42:23
   |
42 |     #[schema(format = UInt8)]

**Comment by juhaku** [comment]
@so-schen Ah, it seems that the parsing side of the format for non strict integers has never been implemented. I'll fix this.
